### ISSUE TITLE
[SR-125] Add rotate algorithm

### ISSUE THREAD

**Issue by gribozavr** [swiftlang/swift#42747]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-125      |
   |Radar             | rdar://problem/19055052         |
   |Original Reporter | @gribozavr      |
   |Type              | Improvement    |
   |Status            | Reopened        |
   |Resolution        |     |
        
   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Standard Library    |
   |Labels            | Improvement, NewAPIRequest, StarterBug        |
   |Assignee          | HarieshJay (JIRA)      |
   |Priority          | Medium      |

   

   md5: ccc424105bba16b3f829a36e196fe08d

  </details>

**Issue Description:**

Swift needs a rotate algorithm, equivalent to `std::rotate()` in C++.

**Comment by MartinSandeCosta** [comment]
@natecook1000 I have taken a look at your [Swift Evolution proposal](https://github.com/apple/swift-evolution/blob/main/proposals/0078-rotate-algorithm.md). This seems like a pretty interesting issue to start with! Would you be ok with me picking this up where you left it? I would love to apply another proposal taking into account all the feedback received in the [review](https://forums.swift.org/t/review-se-0078-implement-a-rotate-algorithm-equivalent-to-std-rotate-in-c/2440)

**Comment by AnthonyLatsis** [comment]
See earlier comments for tips. This needs an evolution proposal, by the way. If you are interested, I suggest reading though the previous proposal and its review stages.
