### ISSUE TITLE
[SR-146] Move the swift indentation mechanism from SourceKit to libIDE and utilize it for a 'swift-format' tool

### ISSUE THREAD

**Issue by akyrtzi** [swiftlang/swift#42768]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-146      |
   |Radar             | None         |
   |Original Reporter | @akyrtzi      |
   |Type              | New Feature    |
   |Status            | Resolved        |
   |Resolution        | Done    |
        
   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 3         |
   |Component/s       | Source Tooling    |
   |Labels            | New Feature, StarterBug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 9dbc0cc9b44435dff437b44922a6c8dd

  </details>

**is blocked by**:  
* [SR-2188](https://bugs.swift.org/browse/SR-2188) Xcode closure auto-indentation is hard to read with some styles  

**Issue Description:**

SourceKit contains indentation logic that is not exposed in the libIDE library; this is not desirable because SourceKit is not cross-platform. Here are some steps to improve on this:

-   Move the indentation logic from SourceKit to libIDE. Have SourceKit just expose the functionality contained in libIDE.

-   Start a 'swift-format' tool that uses the indentation mechanism from libIDE; given a file and source range it auto-indents it.

-   See prior work for 'clang-format' (<http://clang.llvm.org/docs/ClangFormat.html)> for investigation on how to specify and provide formatting options.

**Comment by AnthonyLatsis** [comment]
For posterity: https://github.com/apple/swift-format
