### ISSUE TITLE
[SR-453] Structs, Protocols and casting

### ISSUE THREAD

**Issue by swift-ci** [swiftlang/swift#43070]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-453      |
   |Radar             | None         |
   |Original Reporter | flashspys (JIRA User)      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, LanguageFeatureRequest        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 973efe727beed10b6f2ae35767f6d7b6

  </details>

**Issue Description:**

I don't like the way how Swift handles structs which implements protocols:

Simple demonstration:

``` java
protocol Prot {}
struct A : Prot {}

let arr = [A(), A()] // 1: ok
let arr2 = [A(), A()] as [Prot] // 2: ok
let arr3 = arr as [Prot] // 3: compile error
let arr4 = arr2 as! [A] // 4: runtime error
```

It was discussed [here](http://stackoverflow.com/questions/34457202/swift-structs-an-protocols-not-work-as-expected/34457781#34457781). I think it's mandatory to support casting here and should not be a language limitation. I really like structs in swift but it is very hard to implement sth. like a hierarchy of structs cause they can't inherit from each other and it's hard to work with protocols as you see above.

Does anyone feels similar ?

**Comment by AnthonyLatsis** [comment]
We got test coverage for this [here](https://github.com/apple/swift/blob/main/test/Interpreter/collection_casts.swift)—expect for the `arr4` case, which expectedly works, but I am going to add for the record anyway before closing.
