### ISSUE TITLE
[SR-481] Can not retrieve Optinals from [String:Any] Dictionary

### ISSUE THREAD

**Issue by swift-ci** [swiftlang/swift#43098]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-481      |
   |Radar             | None         |
   |Original Reporter | deggert (JIRA User)      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

% swift --version  
Apple Swift version 2.2-dev (LLVM 3ebdbb2c7e, Clang f66c5bb67b, Swift 1f2908b4f7)  
Target: x86_64-apple-macosx10.9

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 1         |
   |Component/s       | Compiler    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: c2eb4f13cf4cd3284a0acf11ec69bd95

  </details>

**Issue Description:**

After storing `nil as Int?` into a `[String:Any]` the retrieved value can not be downcast (back) to `Int?`:

``` java
Welcome to Apple Swift version 2.2-dev (LLVM 3ebdbb2c7e, Clang f66c5bb67b, Swift 1f2908b4f7). Type :help for assistance.
  1> let d: [String:Any] = ["foo": (nil as Int?)]
d: [String : Any] = 1 key/value pair {
  [0] = {
    key = "foo"
    value = {
      payload_data_0 = 0x0000000000000000
      payload_data_1 = 0xffffffffff000001
      payload_data_2 = 0x0000000100601390
      instance_type = 0x00000001004f6028
    }
  }
}
  2> let v = d["foo"]
v: Any? = Some {
  payload_data_0 = 0x0000000000000000
  payload_data_1 = 0x0000000000000001
  payload_data_2 = 0x0000000000000000
  instance_type = 0x00000001004f6028
}
  3> v! as Int?
repl.swift:3:2: error: cannot convert value of type 'Any' (aka 'protocol<>') to type 'Int?' in coercion
v! as Int?
~^
```

**Comment by AnthonyLatsis** [comment]
The coercion in the original example is diagnosed correctly—you cannot coerce from `Any` to a concrete type. Even though the output differs, nothing seems to suggest that there was an issue with downcasting the value instead.

The output is back to normal now, but I wonder: was it a mirroring issue or something else, and how do we test for the expected output? @lorentey Would be most appreciative of any tips.

**Comment by tbkka** [comment]
Use `as?` or `as!` for runtime dynamic type checking.

**Comment by AnthonyLatsis** [comment]
@tbkka Sorry, I should have expressed myself more clearly. I am willing to add a regression test before closing this and was asking where to look at.

**Comment by adrian-prantl** [comment]
> The output is back to normal now, but I wonder: was it a mirroring issue or something else, and how do we test for the expected output? @lorentey Would be most appreciative of any tips.

It looks like that would have been an LLDB data formatting bug.

**Comment by adrian-prantl** [comment]
REPL tests are here: https://github.com/apple/llvm-project/tree/next/lldb/test/Shell/SwiftREPL
