### ISSUE TITLE
[SR-1040] Meta: This JIRA doesn't support Swift code formatting.

### ISSUE THREAD

**Issue by swift-ci** [swiftlang/swift#43652]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-1040      |
   |Radar             | None         |
   |Original Reporter | josh (JIRA User)      |
   |Type              | Improvement    |

Attachment: [Download](https://user-images.githubusercontent.com/2727770/164961255-49955f56-bde4-40d5-8b94-3007c294f91b.gz)

      
   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 3         |
   |Component/s       | Project Infrastructure    |
   |Labels            | Improvement        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: f9e1f3f80478ac927be70af1d6edb4a5

  </details>

**is duplicated by**:  
* [SR-7580](https://bugs.swift.org/browse/SR-7580) Jira should support Swift code blocks: {code:swift}  

**relates to**:  
* [SR-144](https://bugs.swift.org/browse/SR-144) Markdown Support in Jira  

**Issue Description:**

This JIRA doesn't support a

    {code:swift}

tag.

Since many people are posting Swift code here, maybe implementing this could be useful?

**Comment by AnthonyLatsis** [comment]
Closing since issues are now tracked on GitHub.
