### ISSUE TITLE
[SR-1365] Use proper names for Android NDK and SDK locations

### ISSUE THREAD

**Issue by swift-ci** [swiftlang/swift#43974]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-1365      |
   |Radar             | None         |
   |Original Reporter | ewmailing (JIRA User)      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       |     |
   |Labels            | Bug, Android, StarterBug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 7e49de116e0b50836f6d239adca7376b

  </details>

**Issue Description:**

This bug may already be out of date as it looked like ANDROID_NDK_HOME was being phased out, but I wanted to point this out because it looks like it still exists in the code base and I believe the variable is wrong.

If anything, it should be ANDROID_NDK_ROOT, not ANDROID_NDK_HOME. Last time I pinned the Android folks down on these, they didn’t want to say any of these were official, but this is the explanation:

This was from David Turner from the Android team:  
\[quote\]

ANDROID_NDK_ROOT -\> installation dir of NDK  
ANDROID_SDK_ROOT -\> installation dir of SDK  
ANDROID_SDK_HOME -\> location of SDK-related user files, defaults to  
\~/.android/ on Unix.

These variables are essentially used by the platform and SDK tools  
themselves, so are your best bet.

There is no ANDROID_NDK_HOME.

They are also used by the Chromium build for Android.  
\[/quote\]

If Swift is going to continue using a variable, ANDROID_NDK_HOME should be changed to ANDROID_NDK_ROOT.

**Comment by finagolfin** [comment]
No response to the changed names, closing.
