### ISSUE TITLE
[SR-1362] Android: Swift/Android on Mac OS X

### ISSUE THREAD

**Issue by swift-ci** [swiftlang/swift#43971]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-1362      |
   |Radar             | None         |
   |Original Reporter | ewmailing (JIRA User)      |
   |Type              | New Feature    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 2         |
   |Component/s       |     |
   |Labels            | New Feature, Android        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: c091be8aa105e78bcfc51eebe814940e

  </details>

**Issue Description:**

It would be really nice to be able to use Swift for Android on OS X. Considering the origins of Swift, it seems almost absurd that we have to use Linux to develop Swift on Android.

**Comment by finagolfin** [comment]
This has worked well for years, closing.
