### ISSUE TITLE
[SR-1504] RFE: index(of:) but starting from end

### ISSUE THREAD

**Issue by ddunbar** [swiftlang/swift#44113]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-1504      |
   |Radar             | None         |
   |Original Reporter | @ddunbar      |
   |Type              | New Feature    |
   |Status            | Resolved        |
   |Resolution        | Done    |
        
   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Standard Library    |
   |Labels            | New Feature        |
   |Assignee          | @natecook1000      |
   |Priority          | Medium      |

   

   md5: 2e4233e0695a5d1edce92ed2ae1572d9

  </details>

**Issue Description:**

It is sometimes desirable to get the forward index of an element but searching from the end of a bidirectionally iterable collection. For example, consider finding the string suffix following the last period.

This is similar to C++'s \`find_last_of\` or Python's \`rindex\`.

**Comment by AnthonyLatsis** [comment]
Proposal: SE-0204
