### ISSUE TITLE
[SR-2022] Better fixit for type checking in switch statements

### ISSUE THREAD

**Issue by karwa** [swiftlang/swift#44631]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-2022      |
   |Radar             | None         |
   |Original Reporter | @karwa      |
   |Type              | Improvement    |
   |Status            | In Progress        |
   |Resolution        |     |
        
   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Improvement, DiagnosticsQoI, Parser, StarterBug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 9b53adc1e41e34c46ad044ffe4bfbac9

  </details>

**Issue Description:**

```swift
switch myVariable {
    case let intValue as? Int: print("Hello, I'm an int: \(intValue)")
    case let stringValue as? String: print("Hello, I'm a string: \(stringValue)")
    default: print("Some other value...")
}
```

Gives you an error on the casting lines saying "Invalid pattern". It would be better if it told you to make the casts non-conditional, I.e.:

```swift
switch myVariable {
    case let intValue *as Int*: print("Hello, I'm an int: \(intValue)")
    case let stringValue *as String*: print("Hello, I'm a string: \(stringValue)")
    default: print("Some other value...")
}
```

**Comment by gregomni** [comment]
In the last 5 years the error message has improved here:
```
 8 |     case let intValue as? Int: print("Hello, I'm an Int: \(intValue)")
   |                           `- error: expression pattern of type 'Int?' cannot match values of type 'any IntOrString'
```
I think that's clear enough what's happening.

**Comment by karwa** [comment]
I still don't think it's very good, to be honest. Testing on 5.10:

```swift
protocol IntOrString {}

extension Int: IntOrString {}
extension String: IntOrString {}

func foo(bar: IntOrString) {
  switch bar {
    case let intValue as? Int: print("Hello, I'm an Int: \(intValue)")
    case let stringValue as? String: print("Hello, I'm a String: \(stringValue)")
    default: print("Some other value...")
  }
}
```

```
<source>:8:14: error: pattern variable binding cannot appear in an expression
    case let intValue as? Int: print("Hello, I'm an Int: \(intValue)")
             ^
<source>:8:27: error: expression pattern of type 'Int?' cannot match values of type 'any IntOrString'
    case let intValue as? Int: print("Hello, I'm an Int: \(intValue)")
             ~~~~~~~~~~~~~^~~
<source>:9:14: error: pattern variable binding cannot appear in an expression
    case let stringValue as? String: print("Hello, I'm a String: \(stringValue)")
             ^
<source>:9:30: error: expression pattern of type 'String?' cannot match values of type 'any IntOrString'
    case let stringValue as? String: print("Hello, I'm a String: \(stringValue)")
             ~~~~~~~~~~~~~~~~^~~~~~
```

I think that at the very least, there should be an explicit suggestion (e.g. a fix-it) that the developer turn the `as?` in to an `as`.

**Comment by Jamezzzb** [comment]
Hi @karwa, I was investigating this and thought of 2 other ways in which it could occur:
```swift
let maybeInt: Any = 1

// 1
switch maybeInt {
case let intValue as? Int:
  print(intValue)
default:
  break
}

// 2
if case let intValue as? Int = maybeInt {
  print(intValue)
}

let maybeInts: [Any] = [1, 2, 3]

// 3
for case let intValue as? Int in maybeInts {
  print(intValue)
}

```

In 1 and 3 I think your suggested fix-it would be ideal. However, in the second case, I think it might be better to suggest changing it to:
```swift
if let intValue = maybeInt as? Int {
  print(intValue)
}
```

Any thoughts on this?

**Comment by jameesbrown** [comment]
I have started working on a fix for this.

**Comment by karwa** [comment]
Awesome, thank you @jameesbrown !
