### ISSUE TITLE
[SR-2960] Better Document utils/run-test

### ISSUE THREAD

**Issue by swift-ci** [swiftlang/swift#45550]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-2960      |
   |Radar             | None         |
   |Original Reporter | Beingessner (JIRA User)      |
   |Type              | Task    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 1         |
   |Component/s       |     |
   |Labels            | Task, StarterBug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: ba31e0f5995fad19b727242ff79320fa

  </details>

**Issue Description:**

Neither `build-script -h` nor `docs/Testing.rst` mention the existence of utils/run-test, but they should. This is the best way to run a subset of the tests, and a huge quality-of-life improvement for working on the compiler or standard library.

**Comment by AnthonyLatsis** [comment]
Now documented [here](https://github.com/swiftlang/swift/blob/2fd182acdcf88491175a90c6986a18f191f6afd8/docs/Testing.md#using-utilsrun-test).
