### ISSUE TITLE
[SR-3963] Swift compiler fails with incorrect error when assigning Int*Int to a TimeInterval

### ISSUE THREAD

**Issue by swift-ci** [swiftlang/swift#46548]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-3963      |
   |Radar             | None         |
   |Original Reporter | gilfeig (JIRA User)      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, DiagnosticsQoI, TypeChecker        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 740cda1eaabc1c2932ad0ea624aec40f

  </details>

**Issue Description:**

This snippet fails to compile with the following incorrect error:  
Binary operator '\*' cannot be applied to two 'Int' operands.

``` java
        private static let secondsPerMinute = 60
        private static let secondsPerHour = 60 * secondsPerMinute

        // TimeInterval is always specified in seconds.
        // Standard options: 20 minutes, 1 hour, 3 hours, 6 hours, 24 hours
        static let standard: [TimeInterval] = [
            20 * secondsPerMinute,
            1 * secondsPerHour,
            3 * secondsPerHour,
            6 * secondsPerHour,
            24 * secondsPerHour
        ]
```

**Comment by gregomni** [comment]
Long fixed!

**Comment by AnthonyLatsis** [comment]
Duplicate of #44815.
