### ISSUE TITLE
[SR-4709] SRP source breakage: error: expression was too complex

### ISSUE THREAD

**Issue by lplarson** [swiftlang/swift#47286]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-4709      |
   |Radar             | rdar://problem/31845712         |
   |Original Reporter | @lplarson      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, SourceCompatibility, TypeChecker        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 2e50e5ee9e8bcd730cb2398f9fb6cf42

  </details>

**is blocked by**:  
* [SR-4864](https://bugs.swift.org/browse/SR-4864) error: expression was too complex to be solved in reasonable time  

**Issue Description:**

To reproduce:  
1. Install latest GM/Beta Xcode  
2. $ git clone git@github.com:apple/swift-source-compat-suite.git  
3. $ cd swift-source-compat-suite

To build Swift from scratch before testing:  
4. $ ./reproduce.py master --project-path SRP

Or if you've already built Swift:  
4. $ ./reproduce.py master --project-path SRP --swiftc path/to/swiftc

SipHasher.swift:161:17: error: expression was too complex to be solved in reasonable time; consider breaking up the expression into distinct sub-expressions  
\| (UInt64(buffer\[i + 7\]) \<\< 56)

**Comment by AnthonyLatsis** [comment]
No longer XFAILed, closing.
