### ISSUE TITLE
[SR-5534] Memberwise initializers with any number of optional properties

### ISSUE THREAD

**Issue by swift-ci** [swiftlang/swift#48106]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-5534      |
   |Radar             | rdar://problem/16021750         |
   |Original Reporter | Bear (JIRA User)      |
   |Type              | Improvement    |
   |Status            | Resolved        |
   |Resolution        | Done    |
        
   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 3         |
   |Component/s       | Compiler    |
   |Labels            | Improvement, LanguageFeatureRequest        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: f7949e46c502a72e96387d53c13e0a96

  </details>

**is duplicated by**:  
* [SR-5921](https://bugs.swift.org/browse/SR-5921) Default constructor for structs with default values don't have argument with default value  

**relates to**:  
* [SR-5714](https://bugs.swift.org/browse/SR-5714) Memberwise initializer should adopt struct access control  

**Issue Description:**

Currently, if we don't have our own initializer for the structure, its default *memberwise initializer* allows to provide values of all properties. If we assign a default value for all of our properties, additional initializer in shape of `init()` becomes available to use.

It would be a lot more convenient to make structure initializer behave more like a function with default values.

Example:

``` java
struct S {
    var a: Int
    var b = 1
    var c: Int
}

var s1 = S(a: 0, c: 2)
var s2 = S(a: 10, b: 11, c: 12)
```

Are there any potential problems with such behavior?

**Comment by AnthonyLatsis** [comment]
Duplicate of #43955
