### ISSUE TITLE
[SR-5921] Default constructor for structs with default values don't have argument with default value

### ISSUE THREAD

**Issue by NachoSoto** [swiftlang/swift#48480]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-5921      |
   |Radar             | None         |
   |Original Reporter | @NachoSoto      |
   |Type              | Improvement    |
   |Status            | Resolved        |
   |Resolution        | Duplicate    |
        
<details>
  <summary>Environment</summary>

Swift version 4.0 (swiftlang-900.0.63 clang-900.0.37)

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Improvement        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 105944886c15424a8e6da2a6070408e9

  </details>

**duplicates**:  
* [SR-5534](https://bugs.swift.org/browse/SR-5534) Memberwise initializers with any number of optional properties  

**Issue Description:**

Consider this struct:

``` java
struct A {
    let a1: String
    let a2: Int = 0
}
```

This works:

``` java
_ = A(a1: "") // a2 is 0
```

However, this doesn't:

``` java
error.swift:7:15: error: extra argument 'a2' in call
_ = A(a1: "", a2: 1)
              ^
```

This is unintuitive. One would expect the default constructor for this struct to be defined as:

``` java
init(a1: String, a2: Int = 0) {
    self.a1 = a1
    self.a2 = a2
}
```

And not what currently seems to be defined as:

``` java
init(a1: String) {
    self.a1 = a1
    self.a2 = 0
}
```

**Comment by AnthonyLatsis** [comment]
duplicate of #43955
