### ISSUE TITLE
[SR-5939] Type nested in function cannot satisfy operator protocol requirement

### ISSUE THREAD

**Issue by swift-ci** [swiftlang/swift#48498]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-5939      |
   |Radar             | None         |
   |Original Reporter | Vermeulen (JIRA User)      |
   |Type              | Bug    |
   |Status            | Resolved        |
   |Resolution        | Duplicate    |
        
<details>
  <summary>Environment</summary>

Tested on both Swift 3 and Swift 4

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 1         |
   |Component/s       | Compiler    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   md5: 1170f2070dc965029c6af37799d7125f

  </details>

**duplicates**:  
* [SR-3092](https://bugs.swift.org/browse/SR-3092) Function-level nested types cannot conform to Equatable  

**Issue Description:**

```swift
func foo() {
    struct Foo: Equatable { // error: type 'Foo' does not conform to protocol 'Equatable'
        static func == (left: Foo, right: Foo) -> Bool { return true }
    }
}
```

The problem seems to lie with operators. Instance function or static function requirements work fine.

**Comment by AnthonyLatsis** [comment]
Duplicate of #45682.
