### ISSUE TITLE
[SR-6362] Raw escaping in string literals

### ISSUE THREAD

**Issue by johnno1962** [swiftlang/swift#48912]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-6362      |
   |Radar             | rdar://problem/47725014         |
   |Original Reporter | @johnno1962      |
   |Type              | New Feature    |
   |Status            | Closed        |
   |Resolution        | Done    |
        
   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | New Feature, LanguageFeatureRequest        |
   |Assignee          | @johnno1962      |
   |Priority          | Medium      |

   

   md5: 0d6a3785983c156c861de08a567e4986

  </details>

**Issue Description:**

Often it is inconvenient and opaque entering string literals that are in tended as regex patterns into a swift source.

Taking the lead from python it perhaps a new syntax `r"\w+\s+\w"` could be added to the swift language. This would be equivalent to `" w+ s+ w"`. The specification required would be that if a string literal is preceded by r then unknown escapes are passed though to the literal as-is including the back-slash character rather than going an error. This would be a very minor change confined to Lexer.cpp that I'll work on tomorrow and present to swift-evolution.

**Comment by AnthonyLatsis** [comment]
Proposal: SE-0200
