### ISSUE TITLE
[SR-6909] libSyntax doesn't know about operator precedence

### ISSUE THREAD

**Issue by dabrahams** [swiftlang/swift#49458]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-6909      |
   |Radar             | None         |
   |Original Reporter | @dabrahams      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Source Tooling    |
   |Labels            | Bug, Syntax        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 2493838608afee26863c2c17f96fb301

  </details>

**Issue Description:**

If you want to line-break an expression, you want to break it near lower-precedence operators, so you end up with

``` java
longThing1 * longThing2
+ longThing3 * longThing4
```

rather than

``` java
longThing1 * longThing2 + longThing3
   * longThing4
```

or worse:

``` java
longThing1
    * longThing2 + longThing3
    * longThing4
```

But libSyntax is flattening all of that into `SequenceExprSyntax` so that information is lost. I realize that file-at-a-time processing can't always do this reliably, but... it could <u>try</u>. And it could know about the precedences in the standard library.

**Comment by AnthonyLatsis** [comment]
libSyntax was removed in #62145 and succeeded by [swift-syntax](https://github.com/apple/swift-syntax).
