### ISSUE TITLE
[SR-7629] Wrong fixit when the type doesn't conform to a public protocol

### ISSUE THREAD

**Issue by swift-ci** [swiftlang/swift#50171]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-7629      |
   |Radar             | None         |
   |Original Reporter | sriharims (JIRA User)      |
   |Type              | Bug    |
   |Status            | In Progress        |
   |Resolution        |     |
        
<details>
  <summary>Environment</summary>

Xcode 9.3, Swift 4.1

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, DiagnosticsQoI, StarterBug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 54986872b23e84cdf4f86614e935c40e

  </details>

**Issue Description:**

This is my code without the protocol conformance 

```swift
public struct Numbers: OptionSet
{

     public let rawValue: Int

     

     static let one = Numbers(rawValue: 1)

     static let two = Numbers(rawValue: 2)
}
```
 

The error message - `Initializer 'init(rawValue:)' must be declared public because it matches a requirement in public protocol 'OptionSet'` is correct, but the fixit inserts  'public'  after 'struct' like this - 

```
public struct public Numbers: OptionSet
```

**Comment by AnthonyLatsis** [comment]
Duplicate of #45593
