### ISSUE TITLE
[SR-8672] Hashable struct in function

### ISSUE THREAD

**Issue by swift-ci** [swiftlang/swift#51186]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-8672      |
   |Radar             | rdar://problem/43963469         |
   |Original Reporter | Max (JIRA User)      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, TypeChecker        |
   |Assignee          | None      |
   |Priority          | Medium      |

   md5: 7b3ca9a11387440e866eac5a2c2b0cdc

  </details>

**relates to**:  
* [SR-13040](https://bugs.swift.org/browse/SR-13040) Set collection not working as expected   
* [SR-8696](https://bugs.swift.org/browse/SR-8696) Types nested in functions and their operator functions.   

**Issue Description:**

Link to Swift forum discussion : [link](https://forums.swift.org/t/hashable-struct-in-function/15705)

 Hello ! I would like to have some clarifications about why `Set` does not interact properly with a `Hashable` struct declared in a function.

Here I have a struct `Hello` that conforms to `Hashable` and only needs its `id` for the `hashValue`. Because structs need to have `Equatable` custom conformance to have custom hash behavior, so a `==` function is declared.
I first declare a `Set` with an identifier `123` and the I try to insert another struct having the same identifier with different "value". It does not insert the new element because it is considered as the same by the equality. 

```swift
struct Hello: Hashable {
    let id: Int
    let value: String    var hashValue: Int {
        return id.hashValue
    }    init(id: Int, value: String) {
        self.id = id
        self.value = value
    }    static func == (lhs: Hello, rhs: Hello) -> Bool {
        return lhs.id == rhs.id
    }
}

func testFunc() {
    var set = Set<Hello>([Hello(id: 123, value: "Hello")])
    // Set is now `[Hello #&#8203;1 in __lldb_expr_104.testFunc() -> ()(id: 123, value: "Hello")]`
    set.insert(Hello(id: 123, value: "World"))
    // Set is still `[Hello #&#8203;1 in __lldb_expr_104.testFunc() -> ()(id: 123, value: "Hello")]`.
}

testFunc()
```

Here I have a struct `Hello` that conforms to `Hashable` and only needs its `id` for the `hashValue` and it is declared in a function. The struct is the same as the previous example but it does not work, the set keep inserting it while the `id` is the same. The custom comparison operand is not used so I suspect that the default implementation is called instead.

```swift
func testFunc() {    

    struct Hello: Hashable {
        let id: Int
        let value: String        
        var hashValue: Int {
            return id.hashValue
        }

        init(id: Int, value: String) {
            self.id = id
            self.value = value
        }

        static func == (lhs: Hello, rhs: Hello) -> Bool {
            return lhs.id == rhs.id
        }
    }

    var set = Set<Hello>([Hello(id: 123, value: "Hello")])
    // Set is now `[Hello #&#8203;1 in __lldb_expr_104.testFunc() -> ()(id: 123, value: "Hello")]`
    set.insert(Hello(id: 123, value: "World"))
    // Set is now [Hello #&#8203;1 in __lldb_expr_115.testFunc() -> ()(id: 123, value: "Hello"), Hello #&#8203;1 in __lldb_expr_115.testFunc() -> ()(id: 123, value: "World")]
}

testFunc()
```

**Comment by AnthonyLatsis** [comment]
Duplicate of #45682
