### ISSUE TITLE
[SR-9060] Associated type inference fails for types declared in an inherited protocol

### ISSUE THREAD

**Issue by swift-ci** [swiftlang/swift#51561]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-9060      |
   |Radar             | None         |
   |Original Reporter | emw (JIRA User)      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, AssociatedTypeInference        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 96255997c5321af97ef5c09686ab89d8

  </details>

**Issue Description:**

Associated type inference works when the same protocol both declares an `associatedtype` and has requirements of that type. For example, the compiler correctly infers a `typealias T = Int` here: 

```swift
protocol P { }

protocol Q: P {
  associatedtype T
  func f() -> T
}

struct S: Q {
  func f() -> Int {
    return 0
  }
}
```

But if I move the associated type declaration to the inherited protocol `P`, the typealias inference breaks:

```swift
protocol P { 
  associatedtype T
}

protocol Q: P {
  func f() -> T
}

struct S: Q {
  // error: type 'S' does not conform to protocol 'P'
  // note: protocol requires nested type 'T'; do you want to add it?
  func f() -> Int {
    return 0
  }
}
```

My guess is that this has the same underlying cause as #51199 and #44842, although those issues cover cases where an associate type is both inherited and specialized.

**Comment by slavapestov** [comment]
Dupe of https://github.com/swiftlang/swift/issues/44842
