### ISSUE TITLE
[SR-12200] swift test --filter shouldn't spawn a new process for every test case

### ISSUE THREAD

**Issue by swift-ci** [swiftlang/swift#54625]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-12200      |
   |Radar             | rdar://problem/59496030         |
   |Original Reporter | Tainnor (JIRA User)      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       |     |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: a8bae54f74d0eec10cbf521fd0b1193f

  </details>

**Issue Description:**

this makes testing unnecessarily slow compared to not using "–filter".

See <https://forums.swift.org/t/swift-test-filter-is-slow-or-how-to-run-tests-fast-on-ci/32315/5>

**Comment by grynspan** [comment]
Yes, this has been resolved.
