### ISSUE TITLE
[SR-13164] Link correctly against the C++ standard library on Windows

### ISSUE THREAD

**Issue by swift-ci** [swiftlang/swift#55607]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-13164      |
   |Radar             | rdar://problem/83423233         |
   |Original Reporter | MForster (JIRA User)      |
   |Type              | New Feature    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | New Feature, CxxInterop, Windows        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: d9d8ab51197f34ce89129369bc816236

  </details>

**Issue Description:**

<https://github.com/apple/swift/pull/30914> adds support for linking against the C++ standard library when C++ interop is enabled. We need to make sure that this works on Windows as well.

See [context here](https://github.com/apple/swift/pull/30914#pullrequestreview-410379636).

**Comment by compnerd** [comment]
Going to mark this as fixed for now.  We can re-open it if it is still an issue.  We should be linking properly due to the use of clang as the linker driver.
