### ISSUE TITLE
[SR-13188] Please support @ViewBuilder for properties

### ISSUE THREAD

**Issue by twostraws** [swiftlang/swift#55628]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-13188      |
   |Radar             | None         |
   |Original Reporter | @twostraws      |
   |Type              | New Feature    |
   |Status            | Resolved        |
   |Resolution        | Done    |
        
   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 1         |
   |Component/s       | Compiler    |
   |Labels            | New Feature, FunctionBuilder, TypeChecker        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 7cb2c7fde2a7f991ee63ebf387d335e3

  </details>

**Issue Description:**

I would like you consider adding support for @ViewBuilder to be used with properties, so that the memberwise initializer Swift generates for structs automatically gains that function builder.

As an example, if I wanted to implement a custom SwiftUI VStack right now, I might start with this:

``` swift
struct CustomVStack<Content: View>: View {
    let content: () -> Content

    var body: some View {
        VStack {
            // custom stuff here
            content()
        }
    }
}
```

However, that doesn't support @ViewBuilder, and so this kind of code would not work:

``` swift
CustomVStack {
    Text("Hello")
    Text("Hello")
}
```

To fix this, I need to define a custom initializer:

``` swift
init(@ViewBuilder content: @escaping () -> Content) {
    self.content = content
}
```

In this simple example it isn't a massive problem, but often that initializer has to copy in lots of values – it does exactly what the memberwise initializer did now just with @ViewBuilder for the single content property.

Ideally I'd like to be able to write something along these lines:

``` swift
struct CustomVStack<Content: View>: View {
    @ViewBuilder let content: () -> Content

    var body: some View {
        VStack {
            // do stuff
            content()
        }
    }
}
```

Thank you!

**Comment by AnthonyLatsis** [comment]
Implemented as part of SE-0289

**Comment by malhal** [comment]
Here is fixed link to [SE-0289](https://github.com/swiftlang/swift-evolution/blob/main/proposals/0289-result-builders.md) and we just need `Content` not `() -> Content`, e.g.
```
struct CustomHStack<Content: View>: View {
    @ViewBuilder let content: Content

    var body: some View {
        HStack {
            // custom stuff here
            content
        }
    }
}
```

The implicit memberwise initializer has the following definition:
```
init(@ViewBuilder content: () -> Content) {
    self.content = content()
}
```
