### ISSUE TITLE
[SR-13445] Replace uses of the word "accessor" in diagnostics with user-facing terminology

### ISSUE THREAD

**Issue by theblixguy** [swiftlang/swift#55887]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-13445      |
   |Radar             | None         |
   |Original Reporter | @theblixguy      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, DiagnosticsQoI, StarterBug        |
   |Assignee          | hafraz07 (JIRA)      |
   |Priority          | Medium      |

   

   md5: de44c3ba895e7552b1a30be2e8d5763f

  </details>

**Issue Description:**

We currently have a bunch of type-checker diagnostics that uses the word "accessor" instead of user-facing words such as "getter", "setter" or "observer". The word "accessor" is actually not used anywhere in user-facing documentation or [TSPL](https://docs.swift.org/swift-book/LanguageGuide/Properties.html).

It would be great to replace uses of "accessor" with words that the user is more likely to be familiar with, as mentioned above.

**Comment by theblixguy** [comment]
@iMostfa That's great, I have now assigned it to you. Let us know if you need any help!

**Comment by iMostfa** [comment]
@theblixguy Thanks for you, 
wanted to confirm from you if i should aim to replace all mentions of `accessor` to user-friendly words, or only those who might be replaced by any of: 
`"getter", "setter" or "observer"`


to explain more shall i update:

"'self' within init accessors can only be used to reference" 
to 
"'self' within init functions can only be used to reference" 

and so on ?

**Comment by iMostfa** [comment]
Hi, @theblixguy 
i opened a draft PR on my fork https://github.com/iMostfa/swift/pull/2
here, if all okay, i will open the PR in apple/swift

thanks a lot for your time revewing this

**Comment by iMostfa** [comment]
Hi, @theblixguy 

i opened my PR here https://github.com/apple/swift/pull/74462 for further discussions
