### ISSUE TITLE
[SR-13562] Type checking inconsistency with generic metatypes

### ISSUE THREAD

**Issue by swift-ci** [swiftlang/swift#56000]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-13562      |
   |Radar             | rdar://problem/69153123         |
   |Original Reporter | wangkun (JIRA User)      |
   |Type              | Bug    |

Attachment: [Download](https://user-images.githubusercontent.com/2727770/164963954-bf86c57c-a664-43af-95e6-251d782e10a5.gz)

      
<details>
  <summary>Environment</summary>

Xcode Version 12.0 (12A7209) build in toolchain  
Apple Swift version 5.3 (swiftlang-1200.0.29.2 clang-1200.0.30.1)  
Target: x86_64-apple-darwin19.5.0

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 16f605757d589eb4f960b3df34c9414a

  </details>

**Issue Description:**

There is an inconsistent behavior of the type checking primitives with generic metatypes.

When I use xcode 11.7 I don't have this problem, instead I have this problem with xcode 12

The code is available in the <a href="MyPlayground.playground.zip" class="attachment">MyPlayground.playground.zip</a>

``` swift
protocol Protocol { }
enum Enum: Protocol { case `case` }
struct Struct: Protocol { }
class Class: Protocol { }

let enumInstance: Any = Enum.case
let structInstance: Any = Struct()
let classInstance: Any = Class()

print(enumInstance is Protocol) // true, as expected
print(structInstance is Protocol) // true, as expected
print(classInstance is Protocol) // true, as expected

func instanceCheck<TheType>(_ instance: Any, _: TheType.Type) -> Bool {
    return instance is TheType
}

print(instanceCheck(enumInstance, Protocol.self)) // true, as expected
print(instanceCheck(structInstance, Protocol.self)) // true, as expected
print(instanceCheck(classInstance, Protocol.self)) // true, as expected

let enumType: Any.Type = Enum.self
let structType: Any.Type = Struct.self
let classType: Any.Type = Class.self

print(enumType is Protocol.Type) // true, as expected
print(structType is Protocol.Type) // true, as expected
print(classType is Protocol.Type) // true, as expected

func typeCheck<TheType>(_ type: Any.Type, _: TheType.Type) -> Bool {
    return type is TheType.Type
}

print(typeCheck(enumType, Protocol.self)) // false, surprisingly
print(typeCheck(structType, Protocol.self)) // false, surprisingly
print(typeCheck(classType, Protocol.self)) // false, surprisingly
```

Some discusstion on [forums](https://forums.swift.org/t/type-checking-inconsistency-with-generic-metatypes/23323)

**Comment by AnthonyLatsis** [comment]
Duplicate of #42749

**Comment by AnthonyLatsis** [comment]
The Xcode 11.7 behavior was a bug (another manifestation was #58367). The current behavior is correct (see duplicate).
