### ISSUE TITLE
[SR-13601] Boolean-valued case checking expressions

### ISSUE THREAD

**Issue by typesanitizer** [swiftlang/swift#56036]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-13601      |
   |Radar             | rdar://61035328         |
   |Original Reporter | @typesanitizer      |
   |Type              | New Feature    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | New Feature, StarterProposal        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 69379195ba792a711faff79b86aa3415

  </details>

**is duplicated by**:  
* [SR-4644](https://bugs.swift.org/browse/SR-4644) Create an expression for checking enum cases  

**Issue Description:**

Allowing code patterns like (strawman syntax, we could potentially use `~=` instead of `=`):

``` java
XCTAssertTrue(case .x(10) = expr1)
XCTAssertTrue(case .x(_) = expr2)
```

would make pattern checks more ergonomic.

The alternatives today are:

-   Use `==`: Doesn't work if the type is not Equatable, doesn't work for ignoring bindings as in the second example.

-   Use an immediately invoked function expression (IIFE) with a switch statement: much more verbose than the suggested syntax.

See also: <https://forums.swift.org/t/proposal-sanity-check-assigning-a-case-statement-to-a-boolean/40584>

**Comment by typesanitizer** [comment]
@AnthonyLatsis could you mention which issue this is a duplicate of?

**Comment by AnthonyLatsis** [comment]
Duplicate of #47221
