### ISSUE TITLE
[SR-13931] Excessive ARC when iterating collections containing Strings that access UTF8 views

### ISSUE THREAD

**Issue by Lukasa** [swiftlang/swift#56328]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-13931      |
   |Radar             | rdar://problem/71936108         |
   |Original Reporter | @Lukasa      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

Apple Swift version 5.3.1 (swiftlang-1205.0.14.1 clang-1205.0.16.1)  
Target: x86_64-apple-darwin20.4.0

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 62d476cfbbe9f18d0fea416527cc8bea

  </details>

**Issue Description:**

When iterating containers that contain Strings (or structs that contain Strings), using some operations (such as accessing the UTF-8 view) will emit ARC traffic that is not emitted by other, equivalent operations. This issue appears to manifest only when using the iterator: manual reimplementation of IndexingIterator makes this problem go away.

Here's a one-file reproduction:

``` java
extension String {
    internal func isEqualUTF8ViewElements(to: String) -> Bool {
        return self.utf8.elementsEqual(to.utf8)
    }
}

// The following combination of operations causes an unnecessary retain operation to be added:
//
// 1. Using an iterator on a collection
// 2. Where you use the UTF-8 view on a String stored in the collection, either as a scalar or on a struct.
public func matchBroken(name: String, haystack: [String]) -> Int? {
    var offset = 0
    for entry in haystack {
        defer {
            offset &+= 1
        }

        if entry.isEqualUTF8ViewElements(to: name) {
            return offset
        }
    }

    return nil
}

// Here we drop the call to the UTF-8 operation: no excess retain is added. This proves (2).
public func matchNoCaseInsensitiveCallWorks(name: String, haystack: [String]) -> Int? {
    var offset = 0
    for entry in haystack {
        defer {
            offset &+= 1
        }

        if entry == name {
            return offset
        }
    }

    return nil
}


// Here we remove the iterator and manually implement IndexingIterator: no excess retain is added. This proves (1).
public func matchManualIterationWorks(name: String, haystack: [String]) -> Int? {
    var offset = 0
    var index = haystack.startIndex
    while index < haystack.endIndex {
        defer {
            offset &+= 1
            haystack.formIndex(after: &index)
        }

        let entry = haystack[index]

        if entry.isEqualUTF8ViewElements(to: name) {
            return offset
        }
    }

    return nil
}
```

**Comment by meg-gupta** [comment]
Going through old issues. I don't see extra retain in `matchBroken` anymore. Tested with main branch 4993f4bf2254685b52f9fbcd17dad65ee9271585
