### ISSUE TITLE
[SR-14193] Class declared in function cannot conform to Equatable or Hashable

### ISSUE THREAD

**Issue by woolsweater** [swiftlang/swift#56571]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-14193      |
   |Radar             | rdar://problem/74274734         |
   |Original Reporter | @woolsweater      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

Apple Swift version 5.3.1 (swiftlang-1200.0.41 clang-1200.0.32.8)  
Target: x86_64-apple-darwin20.1.0

And

Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)  
Target: x86_64-apple-darwin19.6.0

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   md5: 79b7fe2de188a81981fa613c90dac987

  </details>

**Issue Description:**

A class can, naturally, conform to `Hashable` or `Equatable` (implementations irrelevant):

```swift
class C : Hashable {
    static func == (lhs: C, rhs: C) -> Bool { return false }
    func hash(into hasher: inout Hasher) {
        hasher.combine(0)
    }
}
```

But declaring that same class inside a function produces an error:

```swift
func hmm() {
    // error: type 'C' does not conform to protocol 'Equatable'
    class C : Hashable {
        static func == (lhs: C, rhs: C) -> Bool { return false }
        func hash(into hasher: inout Hasher) {
            hasher.combine(0)
        }
    }
}
```

Doing this in Xcode and taking the offered fixit just adds an identical stub for `==`:

```swift
static func == (lhs: C, rhs: C) -> Bool {
    <#code#>
}
```

which doesn't help the error.

**Comment by AnthonyLatsis** [comment]
Duplicate of #45682.
