### ISSUE TITLE
[SR-14216] Swift package manager generated Xcode project fails running the test target 

### ISSUE THREAD

**Issue by swift-ci** [swiftlang/swift#56594]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-14216      |
   |Radar             | rdar://problem/74356783         |
   |Original Reporter | martin9612 (JIRA User)      |
   |Type              | Bug    |
   |Status            | Resolved        |
   |Resolution        | Won't Do    |
        

Attachment: [Download](https://user-images.githubusercontent.com/2727770/164964087-d7b87252-a492-4027-884d-2c33fc141df5.gz)

      
<details>
  <summary>Environment</summary>

Swift 5.3.2 on macOS 10.15.7 with Xcode 12.4

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       |     |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 78aa763f09f7751bb9b166cb4979c9b3

  </details>

**Issue Description:**

Generating a swift package on the command line and generating an Xcode project file results in a project that fails to run the test target.

Package created via

-   swift package init

-   Updating package files

-   Removing files not required for macOS

-   Update code files

-   swift package generate-xcodeproj

Running test via swift test passes

Running the test via XCode fails

``` java
 2021-02-14 19:34:28.581714+1100 xctest[84732:1386172] Failed to create a bundle instance representing '/Users/xxx/PackageTesting/DerivedData/PackageTesting/Build/Products/Debug/PackageTestingTests.xctest'. Check that the bundle exists on disk.
///     Program ended with exit code: 1
```

The problem can also be observed when creating a project in XCode and adding a package via "New \| Swift package ..."

**Comment by gsantner** [comment]
@neonichu   
So it's deprecated. But how to build a .xcframework or .framework out of a SPM then? Previously you had to call `swift build --generate-xcodeproj` to make a `.xcodeproj` which you can run xcodebuild on. But when this way is gone, what is the alternative?

I'm specifically sitting here with a project that is also needed in objective-c (=Swift bridging .h headers from .framework), and the swift tool just errors without any notice of WHAT is wrong.

```
swift package generate-xcodeproj
warning: Xcode can open and build Swift Packages directly. 'generate-xcodeproj' is no longer needed and will be deprecated soon.
error: InternalError(description: "Internal error. Please file a bug at https://bugs.swift.org with this info. binary not supported")
```

**Comment by naviiidb** [comment]
@neonichu Could you solve this issue? Im getting the same error.
