### ISSUE TITLE
[SR-15310] Local lazy variables fail to compile in playgrounds

### ISSUE THREAD

**Issue by twostraws** [swiftlang/swift#57632]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-15310      |
   |Radar             | rdar://problem/84204302         |
   |Original Reporter | @twostraws      |
   |Type              | New Feature    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       |     |
   |Labels            | New Feature        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 19bce097fb55cd812fa50bd2788ae4c2

  </details>

**Issue Description:**

The following code compiles correctly in a regular Xcode project, but will not compile at all in a Swift playground:

``` java
func test() -> Bool {
    lazy var example = Bool.random()
    return example
}
```

The error given in the playground is as follows: "error: closure captures '$\_*lazy_storage*$\_example' before it is declared"

**Comment by devAYZ** [comment]
This issue is still open ... @swift-ci

**Comment by AnthonyLatsis** [comment]
@twostraws This runs fine with Swift 5.9 in an Xcode 15.0 playground. Could you confirm?

**Comment by twostraws** [comment]
Yes, this issue now seems to resolved – thank you!
