### ISSUE TITLE
[SR-15742] Unreachable "these types are always canonical" executed

### ISSUE THREAD

**Issue by ahoppen** [swiftlang/swift#58019]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-15742      |
   |Radar             | rdar://87684281         |
   |Original Reporter | @ahoppen      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, CompilerCrash, FoundByStressTester        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: ddd1211125b9d74d76168f30e67db9b1

  </details>

**Issue Description:**

The following test case fails with an llvm_unreachable `these types are always canonical` being executed.

``` java
// RUN: %sourcekitd-test -req=cursor -pos=5:36 %s -- %s

func fetch() {
  sryMap{ return try processResponse() }
  .napError{ parseError(reason: $0.abc()) }
}

func sryMap<String>(_ transform: () throws -> String) -> SryMap<String> {
  fatalError()
}

func processResponse() throws -> String { return "" }

func parseError(reason: String) {}

protocol MyError {}
extension MyError {
  func abc() -> String { return "" }
}

protocol MyProto {
  associatedtype Failure
}
extension MyProto {
  func napError(_ transform: (Self.Failure) -> Void) {}
}

struct SryMap<Output> : MyProto {
    typealias Failure = MyError
}
```

Bisecting determined that this was caused by <https://github.com/apple/swift/pull/40666> (specifically commit ee331a8c012d19c0334bdfbd78720dfa6c6298c9).

**Comment by hborla** [comment]
Oops, looks like I forgot to close this after the fix landed
