### ISSUE TITLE
[SR-15885] NS_SWIFT_UI_ACTOR isn't recognized on block typedefs

### ISSUE THREAD

**Issue by rjmccall** [swiftlang/swift#58150]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-15885      |
   |Radar             | None         |
   |Original Reporter | @rjmccall      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 1         |
   |Component/s       |     |
   |Labels            | Bug, StarterBug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: c804c21c1b5258c110b8fb340a9361b7

  </details>

**Issue Description:**

As reported by Aaron Sky on the forums:

<https://forums.swift.org/t/annotate-objective-c-block-type-with-ns-swift-ui-actor/55437>

This method ought to be imported as taking and return a `@MainActor` function type, but doesn't seem to be:

``` java
@import Foundation;

typedef void (^FooAction)(void) NS_SWIFT_UI_ACTOR;

@protocol Foo
@property (nonatomic, nullable) FooAction didDoFoo;
- (void)doFoo;
@end
```

**Comment by a-alhayek** [comment]
@rjmccall Hi, I would love to take on this issue as my first contribute to swift repo. Where to start on this?

**Comment by a-alhayek** [comment]
Some of the test cases are failing 
<img width="817" alt="Screen Shot 2022-07-07 at 9 27 48 AM" src="https://user-images.githubusercontent.com/64477568/177785179-d54f76c1-a207-44d3-9327-fb8ca6e7c269.png">

**Comment by wesleykebrown** [comment]
Hi @rjmccall,  I'm a part of a software development cohort. I would like to use this issue as my first contribution to swift repo. Which area can I begin in?

**Comment by xedin** [comment]
Unfortunately this issue has already been fixed by https://github.com/swiftlang/swift/pull/70693, sorry for the confusion!
