### ISSUE TITLE
`swift repl` fails when using a nightly toolchain

### ISSUE THREAD

**Issue by Frizlab** [swiftlang/swift#58750]
**Describe the bug**
Running `swift repl` with the latest toolchain (`org.swift.57202205041a`) fails with a `Library not loaded: @rpath/libswiftCore.dylib` error.

**To Reproduce**
1. On macOS, install the nightly toolchain (either from [main](https://download.swift.org/development/xcode/swift-DEVELOPMENT-SNAPSHOT-2022-05-04-a/swift-DEVELOPMENT-SNAPSHOT-2022-05-04-a-osx.pkg) or from [5.7 branch](https://download.swift.org/swift-5.7-branch/xcode/swift-5.7-DEVELOPMENT-SNAPSHOT-2022-05-04-a/swift-5.7-DEVELOPMENT-SNAPSHOT-2022-05-04-a-osx.pkg))
2. Run `xcrun --toolchain org.swift.57202205041a swift repl` in a Terminal

**Expected behavior**
The REPL should launch (if #58247 was properly fixed).

**Screenshots**
<img width="1221" alt="Screenshot 2022-05-09 at 00 05 14" src="https://user-images.githubusercontent.com/523041/167317654-e375d849-24ff-4202-869e-2b8823850d81.png">

**Environment (please complete the following information):**
 - OS: macOS 12.3.1 (21E258)
 - Xcode Version/Tag/Branch: 13.3.1 (13E500a)

**Additional context**
I tried to fix the problem myself by adding the missing lib to the rpath of LLDB (`sudo install_name_tool -add_rpath /Library/Developer/Toolchains/swift-5.7-DEVELOPMENT-SNAPSHOT-2022-05-04-a.xctoolchain/usr/lib/swift/macosx /Library/Developer/Toolchains/swift-5.7-DEVELOPMENT-SNAPSHOT-2022-05-04-a.xctoolchain/System/Library/PrivateFrameworks/LLDB.framework/Versions/A/LLDB`), and then resigning LLDB, but then I get another error
```
error: failed to launch REPL process: process exited with status -1 (attach failed (Not allowed to attach to process.  Look in the console messages (Console.app), near the debugserver entries, when the attach failed.  The subsystem that denied the attach permission will likely have logged an informative message about why it was denied.))
```
I suspect the problem comes from a non-authorised signature for LLDB, but not sure.

**Comment by AnthonyLatsis** [comment]
cc @shahmishal

**Comment by Frizlab** [comment]
This looks fixed now.
