### ISSUE TITLE
Opening Multiple NavigationLinks at once in a ForEach Loop.

### ISSUE THREAD

**Issue by ianfife** [swiftlang/swift#58765]
**Describe the bug**
I am using a ForEach loop which contains a NavigationLink, and if the user clicks 2 of the NavigationLinks at the same time, it opens the one that comes first in the ForEach loop, and if you swipe all the way back out of the view that was opened from the NavigationLink, all the NavigationLinks no longer work (don't open view if clicked). If you half swipe back and let the view go back to its un-swiped state, the view from the second NavigationLink that was clicked will show, and then if you swipe all the way back out of the view that was opened from the NavigationLink again, the NavigationLinks will work (open view if clicked). If the user clicks on 3 or more, the half swipe back action I mentioned earlier does not apply, but the NavigationLinks still no longer work.

**To Reproduce**
Simplified Example:
```
import SwiftUI
import UIKit

struct Letter: Identifiable {
    var id = UUID()
    var letter: String
}

struct ContentView: View {
    
    var letters = [Letter(letter: "A"), Letter(letter: "B"), Letter(letter: "C"), Letter(letter: "D")]
    
    var body: some View {
        NavigationView {
            VStack {
                ForEach(letters) { letter in
                    NavigationLink(destination: SecondView(letter: letter.letter).navigationBarHidden(true)) {
                        Text("Link \(letter.letter)")
                            .foregroundColor(Color.primary)
                            .padding()
                            .background(Color.accentColor)
                            .cornerRadius(10)
                    }
                }
            }
        }
    }
}

struct SecondView: View {
    
    var letter: String
    
    var body: some View {
        Text("View \(letter)")
    }
}

extension UINavigationController: UIGestureRecognizerDelegate {
    
    override open func viewDidLoad() {
        super.viewDidLoad()
        interactivePopGestureRecognizer?.delegate = self
    }
    
    public func gestureRecognizerShouldBegin(_ gestureRecognizer: UIGestureRecognizer) -> Bool {
        return viewControllers.count > 1
    }
}
```
1. Click multiple NavigationLinks at the same time
2. Swipe Back
3. Click a (or multiple) NavigationLinks

**Expected behavior**
Only one of the NavigationLinks should be opened, despite the user clicking on 2 or more (best solution), or all NavigationLinks should be dismissed properly if the user swipes back.

**Environment (please complete the following information):**
 - OS: iOS 15.4.1
 - Xcode Version/Tag/Branch: 13.3.1

**Additional context**
On the NavigationLink, `.navigationBarHidden(true)` was used
This appeared in the Xcode console while testing:
`SwiftUI encountered an issue when pushing aNavigationLink. Please file a bug.`

**Comment by AnthonyLatsis** [comment]
@ianfife I am sorry we missed this one. Was it resolved? If not, please report it via Feedback Assistant. This repository does not track issues with Swift frameworks.

**Comment by ianfife** [comment]
Appears to be resolved with NavigationStack and I do understand now that this repository is not for this haha
