### ISSUE TITLE
RHEL 8 (and soon 9) binaries and/or packages

### ISSUE THREAD

**Issue by einar-hjortdal** [swiftlang/swift#58833]
You target CentOS 7 but RHEL is the upstream distribution. I am sure you are aware. 

However because you target CentOS you seem to have dropped CentOS 8 as target.

CentOS 8 may be dead, but RHEL 8 is free to use with the developers license. Further, CentOS replacements that are rebuilds of RHEL have appeared.

I work with RHEL 8 as a developer and my company uses VzLinux 8 in production (another CentOS alternative). Many others are like me.

Please provide official binaries and/or RPM packages for RHEL 8 (and soon 9).

Perhaps consider flatpak

**Comment by AnthonyLatsis** [comment]
cc @swiftlang/platform-steering-group.

**Comment by al45tair** [comment]
> I give up

We do support (and provide binaries for) RHEL UBI9. I don't know whether UBI9 binaries will work on VzLinux.

If you're after RPMs, I think we have previously experimented with distributing Swift in that format, but I don't believe we have up to date RPMs or Debian packages for Swift (@shahmishal, do I have that right?)
