### ISSUE TITLE
Compiler crash in Swift 5.7

### ISSUE THREAD

**Issue by Frizlab** [swiftlang/swift#59738]
**Describe the bug**
Trying to compile [this repo at this tag](https://github.com/happn-app/officectl/releases/tag/__SWIFT_5.7_CRASHER__) crashes the compiler w/ the current preview of Swift 5.7 (see versions later).

When switching to tag `__SWIFT_5.7_CRASHER_WORKAROUND__` there are no crashes of the compiler anymore.

**To Reproduce**
1. Clone the repo https://github.com/happn-app/officectl.git and checkout the tag `__SWIFT_5.7_CRASHER__`
2. Try and compile w/ Swift 5.7 (either on macOS or Linux)

**Expected behavior**
The compilation should report errors or should pass. It should not crash.

**Environment**
 - OS: macOS 12.4 and Linux (Docker)
 - Xcode Version: 14.0 beta 2 (14A5229c)
 - Docker image: `swiftlang/swift:nightly-5.7-focal` (`5ea3ea9c2666`)

**Additional context**
I _think_ there are two bugs. There are two commits between `__SWIFT_5.7_CRASHER__ ` and `__SWIFT_5.7_CRASHER_WORKAROUND__`. One fixes the first issue, the other fixes the other issue.
I don’t know what the issues are though.

I tried reducing the crash but did not succeed.

**Comment by slavapestov** [comment]
I cannot reproduce the issue with a recent 14.0 beta. It may have been fixed. Do you have a crash log?

**Comment by Frizlab** [comment]
When compiling with **Xcode 14.0 beta 5 (14A5294e)**, I get this: https://gist.github.com/Frizlab/ce48383e4ef379b7f840eacd883ed632

**Comment by slavapestov** [comment]
Ah, looks like a SILGen bug.

**Comment by Frizlab** [comment]
Still occurring with Xcode 14.0 beta 6 (14A5294g).

**Comment by Frizlab** [comment]
Seems fixed (I did not get the crash) with toolchain `org.swift.57202208291a` (`Apple Swift version 5.8-dev (LLVM 03bd949eeee4761, Swift 2c40a850df6f409) - Target: arm64-apple-macosx13.0`).

**Comment by Frizlab** [comment]
Closing as I cannot reproduce anymore.
