### ISSUE TITLE
Compiler hangs for local lazy variable with `try`

### ISSUE THREAD

**Issue by vojtarylko** [swiftlang/swift#60129]
**Describe the bug**
Compiler hangs forever for the program below.

**Steps To Reproduce**
1. `swiftc test.swift` never finishes

**Environment (please fill out the following information)**
- swift-driver version: 1.60 Apple Swift version 5.7 (swiftlang-5.7.0.120.1 clang-1400.0.28.1)
- Target: x86_64-apple-macosx12.0

**Program**
```swift
func a() throws -> Int {
    return 1
}

func b() throws {
    lazy var x = try a()
    print(x)
}

try b()
```

**Comment by slavapestov** [comment]
With asserts enabled it crashes in SILGen:

```
error: compile command failed due to signal 6 (use -v to see invocation)
Assertion failed: (ThrowDest.isValid() && "calling emitThrow with invalid throw destination!"), function emitThrow, file SILGenStmt.cpp, line 1284.
```

@xedin Actually I don't think this has anything to do with concurrency. Sema effect checking either needs to reject this, or we need to make the lazy var getter 'throws' since the initializer gets moved into the getter's body.

**Comment by xedin** [comment]
Sorry I wanted to select ‘Compiler’, not ‘Concurrency’…

**Comment by vojtarylko** [comment]
Still an issue in `swift-driver version: 1.82.2 Apple Swift version 5.9 (swiftlang-5.9.0.114.6 clang-1500.0.27.1)`

**Comment by fritzt0** [comment]
This crash still occurs with Xcode 16 beta 1. Is there a chance to get this fixed?
