### ISSUE TITLE
Assertion `!type->hasTypeVariable()' with a primary associated type on a protocol

### ISSUE THREAD

**Issue by langtutheky** [swiftlang/swift#60547]
**Describe the bug**
The compiler crashes when building codes for existential protocol with primary associated types.

**Steps To Reproduce**
1. Open the attached project
2. Press the Build button

**Expected behavior**
I expected the compiler to successfully build the project.

**Actual behavior**
The compiler crashed with 
>/Users/admin/Works/ExistentialProtocolWithPrimaryAssociatedTypesCrash/Sources/ExistentialProtocolWithPrimaryAssociatedTypesCrash/ExistentialProtocolWithPrimaryAssociatedTypesCrash.swift error build: Command CompileSwift failed with a nonzero exit code

Notes: If replace the `ExistentialSubject()` on line 54 with `ConcreteSubject()` then the compiler can successfully build the project.

**Screenshots**

1. *Compiler crashes with`ExistentialSubject()` on line 54*

![CompilerCrashesWith`ExistentialSubject()`OnLine54](https://user-images.githubusercontent.com/9475206/184500417-c753ddc8-8f1c-4c8b-9f18-ea694ac6f287.png)

2. *Compiler builds successfully with `ConcreteSubject()` on line 54*

![CompilerBuildsWith`ConcreteSubject()`OnLine54](https://user-images.githubusercontent.com/9475206/184500416-16050b63-f798-4efd-a0ab-1788594c5738.png)

**Environment (please fill out the following information)**
 - macOS Ventura 13.0 Beta (22A5321d)
 - Xcode 14.0 Beta 5 (14A5294e)

**Sample project**
[ExistentialProtocolWithPrimaryAssociatedTypesCrash.zip](https://github.com/apple/swift/files/9331683/ExistentialProtocolWithPrimaryAssociatedTypesCrash.zip)

**Additional context**
[Apple Feedback Assistant Ticket 11240178](https://feedbackassistant.apple.com/feedback/11240178)

**Comment by slavapestov** [comment]
Reduced:

```swift
public protocol P<Value> {
  associatedtype Value
  func onValue(_ onValue: () -> Value) -> any P<Value>
}

struct S<Value>: P {
  func onValue(_ onValue: () -> Value) -> any P<Value> {
    return self
  }
}

public func makeP<Value>() -> any P<Value> {
  return S()
}

makeP().onValue { 0 }
```

**Comment by AnthonyLatsis** [comment]
> This is related to #64621

Yeah the same exact bug; well spotted.

**Comment by slavapestov** [comment]
Radar: rdar://106820674

**Comment by langtutheky** [comment]
As of Swift 5.9 and Xcode 15.2, the reduced snippet can compile if assign the returns to individual variables. Chaining still results in compiler crash.

```swift 
public protocol P<Value> {
  associatedtype Value
  func onValue(_ onValue: () -> Value) -> any P<Value>
}

struct S<Value>: P {
  func onValue(_ onValue: () -> Value) -> any P<Value> {
    return self
  }
}

public func makeP<Value>() -> any P<Value> {
  return S()
}

let x: any P<Any> = makeP()
let y = x.onValue { 2 }
let z = y.onValue { 3 }
```

**Comment by slavapestov** [comment]
Also rdar://106820674
