### ISSUE TITLE
Crash when using `any` in function parameter with default value in xcframeowrk. iOS 15 and lower

### ISSUE THREAD

**Issue by Siemian** [swiftlang/swift#62024]
**Describe the bug**
Using new `any` keyword syntax in a code that is later compiled to xcframework is causing a crash on iOS versions prior 16. Same code linked directly(no xcframework) is compiling and running properly there. Additionally the initial setup that crashes on iOS 15 is working fine on iOS 16, no crash there.
The code leading to a crash:
```swift
import Foundation

public protocol Provider<T> {
    associatedtype T: Decodable
    func fetchObject() -> T
}

public final class DefaultProvider: Provider {
    public typealias T = String

    public func fetchObject() -> String {
        "fixture"
    }
}

public final class AnyCrashTest {

    let provider: any Provider<String>

    public convenience init() {
        self.init(test: "")
    }

    init(test: String, provider: any Provider<String> = DefaultProvider()) {
        self.provider = provider
    }
}

```

**Steps To Reproduce**
I have prepared a simple demo project. There are two branches that are using the added framework in two different ways. [`main` branch](https://github.com/Siemian/AnyCrashDemo/tree/main) is linking the framework directly as a target. [`crash` branch ](https://github.com/Siemian/AnyCrashDemo/tree/crash) is linking the compiled version of the framework in a form of xcframework.
1. Use `crash` branch.
2. Run the code on iOS 14/15 simulator
3. Crash will happen

**Expected behavior**
The following code be working on all versions of iOS.

**Screenshots**
<img width="500" alt="Zrzut ekranu 2022-11-10 o 08 41 22" src="https://user-images.githubusercontent.com/1449108/201029353-5139b750-190e-4176-b726-8dab710d3b20.png">

**Environment**
 - iOS: 15 and lower
 - Xcode Version: 14.0, 14.1
 - Swift 5.7

**Additional context**

**Comment by AnthonyLatsis** [comment]
This must be the same availability bug as #62022. We are probably forgetting to look out for parameterized protocol types in type signatures.
