### ISSUE TITLE
"unable to type-check in reasonable time" error should suggest reporting a bug

### ISSUE THREAD

**Issue by AnthonyLatsis** [swiftlang/swift#62310]
The bug rate for this fallback error is too low compared to how often folks face it in the wild. The message should encourage people to report a bug as in "failed to produce diagnostic".

**Comment by XaurDesu** [comment]
So, should the final result of this be the compiler sending the error message `unable to type-check in reasonable time; please file a bug report` when the error is encountered, right?

**Comment by AnthonyLatsis** [comment]
What I quoted is just a chunk of the actual error message, but the idea’s correct.

**Comment by XaurDesu** [comment]
I've been checking the repo and it seems that the error message is defined in line 180 of `./include/swift/AST/DiagnosticsSema.def` as `the compiler is unable to type-check this expression in reasonable time;`, however i'm not sure if there are any other places that should be changed for this to be reflected. I'm pretty new to this repository so maybe i should read a bit more before making significant changes, however i could change the error message on this file, and then we could try and find other places that need adjustments.

**Comment by AnthonyLatsis** [comment]
Yeah, that’s the only place you need to modify in terms of compiler sources. You can grab the bug report message from `failed_to_produce_diagnostic`. You will also have to adjust any tests that verify the emission of this error message.

**Comment by XaurDesu** [comment]
Should the expression `SWIFT_BUG_REPORT_MESSAGE` go before or after `try breaking up the expression into distinct sub-expressions`?

Besides this, i've already found a few tests inside the repository where it is expected to fail with this error message, mainly `prioritize_solver_memory_threshold.swift`, which has commented the exact error found on it, some other files also reference it but don't show the error exactly as it is defined, should i change those comments?

**Comment by XaurDesu** [comment]
By the way, do you mind if i open a pull request so you can see the things i change?

**Comment by AnthonyLatsis** [comment]
> By the way, do you mind if i open a pull request so you can see the things i change?

Naturally, no need to ask!

**Comment by AnthonyLatsis** [comment]
> Should the expression `SWIFT_BUG_REPORT_MESSAGE` go before or after `try breaking up the expression into distinct sub-expressions`?

I’d place it at the end, like everywhere else.

**Comment by airspeedswift** [comment]
Before anyone spends time working on this: I think we need to be sure that this is worthwhile. I suspect this is motivated by “if only enough people generate enough bug reports, they’ll prioritize fixing it/have enough information to fix it” but that is not necessarily true.

Encouraging huge numbers of people to file bug reports against a hard problem that is actively being worked on, and that won't be helped by more bug reports, will only serve to make the people filing the reports unhappy that their report is not being addressed.

I'd be interested in @xedin and @hborla's take on the utility of encouraging bug reports in this area.

**Comment by AnthonyLatsis** [comment]
> It's possible more and more diverse reports of examples of slow expression checking would help direct efforts to produce different, more actionable, diagnostics

That’s the motivation. If the compiler takes more than 10 minutes, or 512MB, or 10^20 bindings, etc. to solve an expression that isn’t all that big, then it’s a bug that I believe we’d like to track. Not all of them are hopeless to the point that tuning the error message is the only remedy. More non-contrived examples will help us collect more proper testing material and direct our efforts to fixing what matters most. 

> Encouraging huge numbers of people to file bug reports against a hard problem that is actively being worked on, and that won't be helped by more bug reports, will only serve to make the people filing the reports unhappy that their report is not being addressed.

I don’t think it’s fair to say that the problem is actively being worked on and would not benefit from reports, given the diversity of origins and manifestations of such issues. Facing the error already makes people unhappy, though, thanks to the growing community, a lot of folks understand the problem is hard and don’t harbour hopes for a quick fix. We also have a workaround for most cases. I doubt stale bug reports would make a big difference in people’s attitude toward the language.

**Comment by AnthonyLatsis** [comment]
@xedin @hborla ping

**Comment by hborla** [comment]
>Encouraging huge numbers of people to file bug reports against a hard problem that is actively being worked on, and that won't be helped by more bug reports, will only serve to make the people filing the reports unhappy that their report is not being addressed.

I agree with this. We already have a lot of reports of too complex type checker behavior, and the code patterns that send the constraint system into its worst-case exponential behavior are well understood. I do not believe that more bug reports will change our approach to solving these issues, especially because filing a bug report with complete information for reproducing type checker performance issues is really difficult; either the programmer needs to attach their entire project with complete dependency information, or they need to reduce a test case. Both of these are a lot to ask for folks.

If the compiler could analyze the complex code and suggest a fix-it for breaking up the expression, that would be a much better programming experience, but that also may be a fairly difficult thing to implement because the constraint system cannot determine type information of the code to understand how to transform it such that it successfully complies.

**Comment by AnthonyLatsis** [comment]
Thanks for the feedback! It is the non-standard issues like [this one](https://github.com/apple/swift/issues/62390) that motivated this request. But I mostly get the point, and I trust in your judgment for the rest.


@XaurDesu Sorry for the bummer, I was not expecting this to boomerang.
