### ISSUE TITLE
[interop] Dispatch virtual method calls correctly

### ISSUE THREAD

**Issue by hyp** [swiftlang/swift#62354]
At the moment, virtual C++ method calls when made in Swift aren't actually dispatched virtually through the vtable, but instead generate a call to the underlying C++ function.

**Steps to reproduce**
$ cat test.h
```
#pragma once

struct MakeMe {
    virtual void callMe(int x) = 0;
};

MakeMe *testMe();
```
$ cat test.swift
```
import Testi

func test() {
    testMe().pointee.callMe(0);
}

test()
```
$ cat module.modulemap
```
module Testi {
  header "test.h"
  requires cplusplus
}
```

$ swift-frontend -c -enable-experimental-cxx-interop -I . -Onone test.swift -sdk  $SDK -emit-ir -o ir.ir

The IR contains direct call:
```
  %14 = bitcast i8* %13 to %TSo6MakeMeV*
  %15 = bitcast %TSo6MakeMeV* %14 to %struct.MakeMe*
  call void @_ZN6MakeMe6callMeEi(%struct.MakeMe* %15, i32 0)
```

**Expected behavior**
The IR should make the call using the vtable of the C++ value.

**Comment by egorzhdan** [comment]
Fixed in https://github.com/swiftlang/swift/pull/71994
