### ISSUE TITLE
Deprecated types aren't diagnosed when used as property wrappers

### ISSUE THREAD

**Issue by stephencelis** [swiftlang/swift#63139]
**Description**

When a type that can act as a property wrapper (such as a struct, or type alias to a struct) is deprecated, no warning shows up when used as an `@`-property wrapper.

**Steps to reproduce**

Paste the following into a Swift file:

```swift
@available(*, deprecated)
@propertyWrapper
struct A {
  var wrappedValue: Int
}

@available(*, deprecated)
typealias B = A

func f() {
  @A var x = 0                // No warning!
  var y = A(wrappedValue: 0)  // ⚠️ 'A' is deprecated

  @B var z = 0                // No warning!
  var w = B(wrappedValue: 0)  // ⚠️ 'B' is deprecated
}
```

**Expected behavior**

I expect both `@A` and `@B` lines to have deprecation warnings.

**Environment**
- Swift compiler version info `swift-driver version: 1.62.15 Apple Swift version 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51)`
- Xcode version info `Xcode 14.2 / Build version 14C18`

**Comment by stephencelis** [comment]
Worse, if marked `unavailable`, usages still compile:

```swift
@available(*, unavailable)
@propertyWrapper
struct A {
  var wrappedValue: Int
}

@available(*, unavailable)
typealias B = A

func f() {
  @A var x = 0                // Compiles!
  @B var z = 0                // Compiles!
}
```

**Comment by stephencelis** [comment]
Appears to be a duplicate of https://github.com/apple/swift/issues/57231

**Comment by stephencelis** [comment]
@tshortli Just got bit by this again and remembered I opened this 😅

Did you ever look into it?

**Comment by tshortli** [comment]
Not yet, but I will, thanks for the reminder.

**Comment by tshortli** [comment]
@stephencelis I added some tests [here](https://github.com/swiftlang/swift/pull/77573) in an attempt to reproduce the issue but I'm not able to on `main`. I'm also not able to reproduce with the original reproducer in Xcode 16. What version of the compiler were you using when you last saw this?

**Comment by stephencelis** [comment]
@tshortli Here's a reduction from a recent repro in Xcode 16.1:

```swift
@propertyWrapper struct P<V> {
  var wrappedValue: V
  var projectedValue: Self { self }
}

extension P: Equatable where V: Equatable {
  static func == (lhs: P, rhs: P) -> Bool {
    lhs.wrappedValue == rhs.wrappedValue
  }
}

@available(*, unavailable)
extension P: Hashable where V: Hashable {
  func hash(into hasher: inout Hasher) {
    fatalError()
  }
}

struct S: Hashable {
  @P var x = 1
}
```

A similar repro:

```swift
@propertyWrapper struct P<V> {
  var wrappedValue: V
  var projectedValue: Self { self }
}

@available(*, unavailable)
extension P: Encodable where V: Encodable {
  func encode(to encoder: any Encoder) throws {
    fatalError()
  }
}

@available(*, unavailable)
extension P: Decodable where V: Decodable {
  init(from decoder: any Decoder) throws {
    fatalError()
  }
}

struct S: Codable {
  @P var x = 1
}
```

**Comment by tshortli** [comment]
Ah, those examples are very different in nature than the original example this was filed with. Do you agree that the original examples no longer reproduce? Your new ones look like they may be demonstrating buts that are specifically in conformance synthesis, rather than availability checking.

**Comment by tshortli** [comment]
I don't think the bug you're demonstrating now is really specific to property wrappers either. This also reproduces it:

```
struct G<V> {
  var g: V
}

@available(*, unavailable)
extension G: Encodable where V: Encodable {
  func encode(to encoder: any Encoder) throws {
    fatalError()
  }
}

@available(*, unavailable)
extension G: Decodable where V: Decodable {
  init(from decoder: any Decoder) throws {
    fatalError()
  }
}

struct S: Codable {
  var x = G(g: 1)
}
```

**Comment by tshortli** [comment]
For the sake of clarity, I think this new problem should be tracked in a separate issue as the root cause is likely pretty unrelated. If you agree the original examples no longer reproduce, I'd like to close this issue.

**Comment by stephencelis** [comment]
@tshortli Done: https://github.com/swiftlang/swift/issues/77589

**Comment by stephencelis** [comment]
This has been fixed.
