### ISSUE TITLE
@objcMembers is not applied to inner classes or ObjC compatible enums

### ISSUE THREAD

**Issue by mildm8nnered** [swiftlang/swift#63441]
**Description**

In a class declared with @objcMembers (and that inherits from NSObject, see https://github.com/apple/swift/issues/52325), inner classes and ObjectiveC compatible enums will not automatically behave as though declared with @objc

**Steps to reproduce**

Given the code

```
#!/usr/bin/env swift

import Foundation

// This WILL be visible to ObjC
@objcMembers
class Foo: NSObject {
    // This WILL be visible to ObjC
    var a: Int = 0

    // @objc is	redundant here - this could be a warning
    @objc var b: Int = 0

    // This will NOT be visible to ObjC
    class Foo2: NSObject {
        var x: Int = 0
    }

    // This will NOT be visible to ObjC
    @objcMembers
    class Foo3: NSObject {
        var y: Int = 0
    }

    // This WILL be visible to ObjC
    @objc
    class Foo4: NSObject {
        var z: Int = 0
    }

    // This will NOT be visible to ObjC
    enum Bar: Int {
        case zero
    }

    // This WILL be visible to ObjC
    @objc enum Baz: Int {
        case zero
    }
}
```

`swiftc  -emit-objc-header-path header.h  Example.swift`

Will indicate that the various members are exposed in the ObjectiveC header as described in the comments.

**Expected behavior**

I would expect all of the above cases to appear in the ObjectiveC header, just as if they were declared with `@objc`

Ideally I would like a warning if `@objc` was redundant.

**Environment**

```
% swiftc --version
swift-driver version: 1.62.15 Apple Swift version 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51)
Target: arm64-apple-macosx12.0
```

 
- Xcode version info 
- Deployment target:

**Comment by AnthonyLatsis** [comment]
Duplicate of #63442
