### ISSUE TITLE
Failed to use swiftc to compile swift code with import foundation.

### ISSUE THREAD

**Issue by Chenxiangxie1996** [swiftlang/swift#63708]
**Description**

I have follwed the steps from this [doc](https://github.com/apple/swift/blob/main/docs/Android.md) and run hello on android.  But when I want to use swiftc to compile a swift within import foundation. Errors will occur.

```
date.swift:1:8  error: no such module 'Foundation'
import Foundation
```

**Steps to reproduce**

date.swift:
```swift
import Foundation
print("hello")
let time = Date()
print(time)
```

**Expected behavior**

I directly run this date.swift on x86_64. It can run successfully. 
But when I use swiftc  to compile it into a exec file on android. it cannot.
So how can I compile it successfully? Should I add some parameters on utils or swiftc? Please help me.

![image](https://user-images.githubusercontent.com/31364477/219290445-65cbe57a-458f-45e5-ae95-ac747ee53791.png)

**Environment**
- Swift compiler version info 
- Xcode version info 
- Deployment target:

**Comment by LucianoPAlmeida** [comment]
cc @buttaface

**Comment by buttaface** [comment]
The official docs currently only show building and using the stdlib, not Foundation. Try out [my Android SDK, that gives you Foundation and allows you to use the package manager too](https://github.com/buttaface/swift-android-sdk).

**Comment by finagolfin** [comment]
Closing, since the doc has never supported cross-compiling Foundation for Android, but once more patches get in, I will update this doc one day to show that too.
