### ISSUE TITLE
Interop: Use of c++20 type char8_t confuses the swift compiler and Xcode

### ISSUE THREAD

**Issue by ADKaster** [swiftlang/swift#68726]
**Description**

An imported cxx module (clang module) with a struct that uses the type char8_t has its char8_t member dropped on the floor.

**Steps to reproduce**

In this fork of the swift-cmake-examples:

https://github.com/ADKaster/swift-cmake-examples/tree/xcode-15/Interop

I have a CMake project that uses c++20, sets the interop flag to true, has a C++20-only feature in the C++ component (a char8_t member).

When I generate an Xcode project 
```
cmake -S Interop -B Xcode -GXcode
```
and open that Xcode project in Xcode Version 15.0 (15A240d), I can set the interop mode to C++, and set the C++ language standard to C++20 (or gnu++20), and the project builds.

```
cmake --build Xcode
```
or
 
Build in Xcode GUI

**Expected behavior**

Building and running the project gives an executable `E` that when run, prints `Version(major: 1, minor: 0, patch: 0)`

However, there are two bugs instead:

1. the major version is dropped on the floor

```
swift-cmake-examples/Interop$ ./Xcode/Sources/Swift/Executable/Debug/E
Version(minor: 0, patch: 0)
```

2. Xcode cannot parse the native module when ctrl+clicking on the module:

<img width="543" alt="image" src="https://github.com/apple/swift/assets/8388494/fb20d0d9-cb45-4379-aa56-bd77570b8b56">

<img width="591" alt="image" src="https://github.com/apple/swift/assets/8388494/258334a0-3f4c-44cf-8587-cdf3a743438e">

<img width="888" alt="image" src="https://github.com/apple/swift/assets/8388494/05f2fb33-9be9-4e62-8a82-67088d55b013">

**Environment**
- Swift compiler version info: swift-driver version:

1.87.1 Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)
Target: arm64-apple-macosx13.0

- Xcode version info:

Xcode 15.0
Build version 15A240d

- Deployment target: macOS 13.0 (running 13.6)

I reported this on apple developer a few months ago but didn't get a reply that actually helped.

https://developer.apple.com/forums/thread/735186

**Comment by egorzhdan** [comment]
Here's an old pull request that we should probably resurrect: https://github.com/swiftlang/swift/pull/26153.
