### ISSUE TITLE
C++ interop: fix  Interop/Cxx/class/safe-use-of-returned-reference-with-borrowing.swift

### ISSUE THREAD

**Issue by hyp** [swiftlang/swift#70340]
### Description

This test is disabled and should be re-enabled.

### Reproduction

n/a

### Expected behavior

Should pass.

### Environment

Main

**Comment by egorzhdan** [comment]
Fixed in https://github.com/swiftlang/swift/commit/7ce9cada2da8ec3182b9b3935e1e5df1c3568ca2
