### ISSUE TITLE
Contributor Experience: Automate the Xcode workspace generation process

### ISSUE THREAD

**Issue by AnthonyLatsis** [swiftlang/swift#70604]
### Description

Having to manually go through [the steps](https://github.com/apple/swift/blob/b01dbc5c9caeb4da2fc4676fa9900e3443ce6a89/docs/HowToGuides/GettingStarted.md#using-ninja-with-xcode) to create a workspace and add stuff to it is... unfortunate. It would be nice to have a separate command line tool that both generates projects via `build-script` and automates at least this part of the setup.

**Comment by hamishknight** [comment]
Going to consider this resolved by https://github.com/swiftlang/swift/pull/77406
