### ISSUE TITLE
Accessing non-mutating properties of a class's non-copyable property prevents compilation.

### ISSUE THREAD

**Issue by alphaArgon** [swiftlang/swift#70660]
### Description

As shown in the reproduction code, the bug occurs only when accessing non-mutating properties (regardless stored or computed) of a class's non-copyable property. For a struct (modified as necessary) there are no bugs.

### Reproduction

```swift
struct Factory: ~Copyable {

    public var property: Int {0}

    public var mutatingProperty: Int {
        mutating get {0}
    }
}


class Container {

    var factory = Factory()

    func test() {
        _ = factory.property  //  Error: Copy of noncopyable typed value. This is a compiler bug. Please file a bug with a small example of the bug
        _ = factory.mutatingProperty  //  OK
    }
}
```

### Expected behavior

Should not complain and pass compilation.

### Environment

Swift 5.9 shipped with Xcode 15.1

**Comment by kavon** [comment]
Thanks for reporting! This appears to have been fixed in Swift 5.10
