### ISSUE TITLE
C++ interop: Pointer to pointer imported as `?!` in Swift when using SWIFT_UNSAFE_REFERENCE

### ISSUE THREAD

**Issue by 0xpablo** [swiftlang/swift#70818]
### Description

I'm facing an issue with C++ interoperability when trying to use a class that comes from C++ in Swift due to importing a pointer to pointer as `?!` instead of unsafe pointers, which makes some C++ code impossible to use.

More context on this [swift forum post](https://forums.swift.org/t/pointer-to-pointer-in-c-is-imported-as-in-swift-when-using-swift-unsafe-reference/69101).

### Reproduction

```cpp
#include <swift/bridging>

class DB {
public:
   void openDB(DB**); 
} SWIFT_UNSAFE_REFERENCE;
```

is imported as
```swift
@available(macOS 13.3.0, *)
public class DB {   
    public func openDB(_: DB?!)
}
```

### Expected behavior

That the API is imported using unsafe pointers so that I can do this:

```swift
var db: DB = nil
openDB(&db)
```

### Environment

swift-driver version: 1.87.3 Apple Swift version 5.9.2 (swiftlang-5.9.2.2.56 clang-1500.1.0.2.5)

(I also tried with a 5.10  snapshot from Dec 19 with the same result).

**Comment by ravikandhadai** [comment]
This is fixed by https://github.com/swiftlang/swift/pull/73811
