### ISSUE TITLE
Compiler doesn't warn about unreachable call to method on Error in catch clause

### ISSUE THREAD

**Issue by juliand665** [swiftlang/swift#71053]
### Description

When calling a method defined on `Error` (necessarily as an extension) in a catch clause, the compiler doesn't seem to recognize if it's unreachable, silently accepting such a call after leaving the scope unconditionally. This is the first time I've seen such behavior, and this is what I've been able to reduce it to.

### Reproduction

```swift
func test() throws {}

extension Error {
    func foo() {}
}

func run() {
    do {
        try test()
    } catch {
        return; // semicolon to make sure we're not returning the void result of the method call
        error.foo() // <- no warning?
    }
}
```

### Expected behavior

a warning on `error.foo()` that it's unreachable

### Environment

swift-driver version: 1.87.3 Apple Swift version 5.9.2 (swiftlang-5.9.2.2.56 clang-1500.1.0.2.5)
Target: x86_64-apple-macosx14.0

**Comment by jamieQ** [comment]
this appears to be fixed on the currently nightly compiler ([compiler explorer repro](https://godbolt.org/z/qGaWEGrs7))

**Comment by juliand665** [comment]
sure does! very cool, thanks for the heads-up :)
