### ISSUE TITLE
Compiler issue with Swift 5.9 if and switch expressions in TCA's reducer

### ISSUE THREAD

**Issue by ong-yue-huei** [swiftlang/swift#71089]
### Description

I tried the new syntax of [if and switch expressions](https://github.com/apple/swift-evolution/blob/main/proposals/0380-if-switch-expressions.md) added in Swift 5.9 in a reducer's ([TCA](https://github.com/pointfreeco/swift-composable-architecture)) body and got the following error when trying to compile.

> Command SwiftCompile failed with a nonzero exit code.

Here's an example that return the above error when trying to compile:
```swift
var body: some ReducerOf<Self> {
    Reduce { state, action in
        switch action {
        case .update:
            let text = if .random() { "hoge" } else { "" } 
            return .none
        }
    }
}
```

Here're some examples that can be compiled without problem:
```swift
var body: some ReducerOf<Self> {
    Reduce { state, action in
        switch action {
        case .update:
            let text: String = if true { "hoge" } else { "" } 
            return .none
        }
    }
}
```
```swift
var body: some ReducerOf<Self> {
    Reduce { state, action in
        switch action {
        case .update:
            let text = { if .random() { "hoge" } else { "" } }()
            return .none
        }
    }
}
```

### Reproduction

```swift
import ComposableArchitecture

@Reducer
struct MyReducer {
    struct State: Equatable {}

    enum Action {
        case update
    }

    var body: some ReducerOf<Self> {
        Reduce { state, action in
            switch action {
            case .update:
                let text = if .random() { "hoge" } else { "" }
                return .none
            }
        }
    }
}
```

### Expected behavior

Able to compile

### Environment

swift-driver version: 1.87.3 Apple Swift version 5.9.2 (swiftlang-5.9.2.2.56 clang-1500.1.0.2.5)
Target: arm64-apple-macosx14.0

TCA version: 1.6.0
Xcode version: 15.2

**Comment by AnthonyLatsis** [comment]
I was able to reduce the test case to the following with a 5.9 compiler, but I could not reproduce the crash with a fresh compiler. Could you try out a recent snapshot?

```swift
struct Struct {
  init(_: () -> Void) {}
}

@resultBuilder
enum MyBuilder {
  static func buildBlock(_ s: Struct) -> Struct { s }
}

struct Test {
  @MyBuilder
  var body: Struct {
    Struct {
      let text = if .random() { "hoge" } else { "" }
    }
  }
}
```

**Comment by ong-yue-huei** [comment]
@AnthonyLatsis 
Thanks for the reply and the test case.
I've tried it with [swift-5.10-DEVELOPMENT-SNAPSHOT-2024-01-23-a](https://github.com/apple/swift/releases/tag/swift-5.10-DEVELOPMENT-SNAPSHOT-2024-01-23-a) snapshot and the swift compiler compiled without problem. 👍 
I'll close this issue since it is fixed in the latest snapshot. 
Once again, thanks! 🙇

**Comment by hamishknight** [comment]
FWIW this is a dupe of https://github.com/apple/swift/issues/71040
