### ISSUE TITLE
Wrong compiler error regarding conditional conformances that involve Sendable

### ISSUE THREAD

**Issue by groue** [swiftlang/swift#71544]
### Description

Hello,

The Swift 5.10 compiler (Xcode version 15.3 beta 2 (15E5188j)) produces a compiler error that I believe is unexpected when it compiles code that involves conditional conformances and the `Sendable` protocol.

### Reproduction

```swift
protocol A: Sendable { }
protocol B: Sendable { }
struct S<T> { }
extension S: A where T: A { }
extension S: B where T: B { } // ❌ 'B' requires that 'T' conform to 'A'
```

### Expected behavior

There is no compiler error.

---

Another way to look at the issue is to split the sample code into library code, and user code:

```swift
// Library code
public protocol A: Sendable { }
public protocol B: Sendable { }

// User code
struct S<T> { }
extension S: A where T: A { }
extension S: B where T: B { } // ❌ 'B' requires that 'T' conform to 'A'
```

In a previous version on the library, the protocols `A` and `B` did not conform to Sendable, and user code did compile smoothly:

```swift
// Previous version on the library did not involve Sendable:
public protocol A { }
public protocol B { }

// User code
struct S<T> { }
extension S: A where T: A { } // ✅
extension S: B where T: B { } // ✅
```

The error only appears when the library adds Sendable requirements. I was asked in the [Swift forums](https://forums.swift.org/t/is-adding-a-sendable-requirement-a-breaking-change/69957/7) to open an issue every time I see that adding a `Sendable` requirement could break user code, so here it is 😊 Indeed, the user can not fix those errors without adding possibly wrong conditions: this is a breaking change.

The reader has recognised in the reduced sample code the classic pattern in which a `RawRepresentable` type is augmented with conditional conformances (see an [example of this pattern](https://github.com/pointfreeco/swift-tagged/blob/e4955955e17abc8765a79f3e4f1e56864cc4f2b5/Sources/Tagged/Tagged.swift#L38)). The bug looks severe to me, because this pattern is quite frequent.

---

For the record, my "real" setup is a little it more complex that the reduced case exposed above. It exhibits some more weird compiler behaviors:

```swift
public protocol A: Sendable { }
public protocol B: Sendable { }
public protocol C: Sendable { }
public protocol D: A & B & C { }
public protocol E: C { }

struct S<T> { }
extension S: A where T: A { } // ✅
extension S: B where T: B { } // ❌ 'B' requires that 'T' conform to 'A'
extension S: C where T: C { } // ❌ 'C' requires that 'T' conform to 'A'
extension S: D where T: D { } // ✅
extension S: E where T: E { } // ✅
```

"Fixing" the first error by adding a condition does not remove the second error (that's somewhat expected, at least the compiler is consistently erroneous):

```swift
extension S: A where T: A { }     // ✅
extension S: B where T: B & A { } // ✅ "fixed"
extension S: C where T: C { }     // ❌ 'C' requires that 'T' conform to 'A'
extension S: D where T: D { }     // ✅
extension S: E where T: E { }     // ✅
```

But "fixing" the second error by adding a condition creates an error at another place 😅 :

```swift
extension S: A where T: A { }     // ✅
extension S: B where T: B { }     // ❌ 'B' requires that 'T' conform to 'A'
extension S: C where T: C & A { } // ✅ "fixed"
extension S: D where T: D { }     // ✅
extension S: E where T: E { }     // ❌ 'E' requires that 'T' conform to 'A'
```

I hope those examples are good food for regression tests.

### Environment

Swift 5.10 (Xcode version 15.3 beta 2 (15E5188j))

**Comment by xedin** [comment]
cc @slavapestov

**Comment by slavapestov** [comment]
Normally when you declare a conditional conformance you must explicitly declare the conformance to the inherited protocol, eg if you wanted your `S` to be `Hashable` you'd want to write something like this:

```
struct S<T> {}

extension S: Equatable where T: Equatable {}
extension S: Hashable where T: Hashable {}
```

This is because carrying over the bound to the inherited protocol (`extension S: Equatable where T: Hashable`) would be wrong.

However, an exception was made for Sendable to avoid breaking existing code; if some existing protocol is changed to inherit Sendable, and you conform to it conditionally, you get an implied Sendable conformance with the same conditional requirements.

You found the case where this rule doesn't work (which is why we don't want it in general, it's a backwards compatibility hack).

You can get around this by explicitly stating an unconditional Sendable conformance. The below type checks correctly for me:

```
protocol A: Sendable { }
protocol B: Sendable { }
struct S<T> { }
extension S: Sendable { }
extension S: A where T: A { }
extension S: B where T: B { }
```

**Comment by groue** [comment]
> Normally when you declare a conditional conformance you must explicitly declare the conformance to the inherited protocol

🤦‍♂️ How did I forget that? I was too much focused on the "no breaking change" and slightly mislead by diagnostic messages. I should have mentioned this in my report.

> However, an exception was made for Sendable to avoid breaking existing code.

Thank you for restating what Holly was saying in the forums.

> You found the case where this rule doesn't work (which is why we don't want it in general, it's a backwards compatibility hack).

I very much welcome the intent, because it lets me do my job of OSS maintainer obsessed with backward compatibility :-)

> You can get around this by explicitly stating an unconditional Sendable conformance.

Great 👍 This reduces the severity of the issue (for my own use case): if the issue still exists when Xcode 15.3 ships, I'll just mention the workaround in my documentation and guide users towards a solution.

Thank you very much @slavapestov!
