### ISSUE TITLE
`lldb` problems on Linux when using `swift repl`

### ISSUE THREAD

**Issue by MahdiBM** [swiftlang/swift#71543]
### Description

```bash
~ docker run --privileged --rm -it swiftlang/swift:nightly-5.10-jammy swift repl
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'lldb'
Welcome to Swift version 5.10-dev (LLVM dbfaba0078e9380, Swift 63c8b551eb2f613).
Type :help for assistance.
  1>
```
The 3 error lines are unexpected and should not be there just like when using `swift repl` installed on mac:
```bash
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'lldb'
```
On a Linux VPS, it throws a similar error:
```bash
~ swift repl
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/lldb/__init__.py", line 1399, in <module>
    eTraceInstructionControlFlowTypeInstruction = _lldb.eTraceInstructionControlFlowTypeInstruction
AttributeError: module '_lldb' has no attribute 'eTraceInstructionControlFlowTypeInstruction'
Welcome to Swift version 5.9.2 (swift-5.9.2-RELEASE).
Type :help for assistance.
  1> :q
~ uname -a
Linux ubuntu 5.15.0-91-generic #101-Ubuntu SMP 2023 x86_64 x86_64 x86_64 GNU/Linux
```

### Reproduction

[Described in previous section]

### Expected behavior

No errors, like on macOS.

### Environment

[Visible in the code blocks]

**Comment by AnthonyLatsis** [comment]
cc @shahmishal

**Comment by shahmishal** [comment]
@JDevlieghere @adrian-prantl

**Comment by adrian-prantl** [comment]
@JDevlieghere @bulbazord

**Comment by JDevlieghere** [comment]
There's two unrelated, but possibly related issues here: 

 - The first issue is Swift 5.10 not finding the lldb Python module. 
 - The second issue is LLDB  picking up the lldb Python module from the system which appears to be newer (and knows about `eTraceInstructionControlFlowTypeInstruction`) while the LLDB from Swift 5.9 doesn't. The Python module and LLDB need to be in sync. 

This stuff works pretty differently between macOS and Linux. I'd have to figure out what the expected behavior is and how the nightly toolchain is different here.

**Comment by MahdiBM** [comment]
@JDevlieghere I guess these could be 2 actual different problems, but the Docker images (the first case of the two) always just throw that error.
On a Linux VPS (second case) it could be many more things going on, so it could be another different (but kind of related) problem.

**Comment by MahdiBM** [comment]
Can no longer reproduce any of these errors:

```bash
root@dev ~# swift --version && uname -a
Swift version 6.0-dev (LLVM 44e9ac72b347ffd, Swift d8e5733a9004366)
Target: x86_64-unknown-linux-gnu
Linux dev 5.15.0-116-generic #126-Ubuntu SMP Mon Jul 1 10:14:24 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
root@dev ~# swift repl
Welcome to Swift version 6.0-dev (LLVM 44e9ac72b347ffd, Swift d8e5733a9004366).
Type :help for assistance.
  1> :q
root@dev ~# docker run --privileged --rm -it swiftlang/swift:nightly-5.10-jammy swift repl
Welcome to Swift version 5.10-dev (LLVM e98989b1092ff3a, Swift 0e5cb27c42ec3c7).
Type :help for assistance.
  1>
```
