### ISSUE TITLE
`@preconcurrency` fails to suppress concurrency warnings

### ISSUE THREAD

**Issue by tcldr** [swiftlang/swift#72182]
### Description

The Swift compiler fails to suppress concurrency warnings when using the `@preconcurrency` attribute.

### Reproduction

```swift
@preconcurrency import os // WARN: '@preconcurrency' attribute on module 'os' is unused

enum Log {
  // WARN: Static property 'shared' is not concurrency-safe because it is not either conforming to 'Sendable' or isolated to a global actor; this is an error in Swift 6
  static let shared = Logger(subsystem: "logging", category: "warnings")
}
```

### Expected behavior

The concurrency warning is suppressed.

### Environment

swift-driver version: 1.90.11.1 Apple Swift version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4)
Target: arm64-apple-macosx14.0

### Additional information

As originally flagged at: https://forums.swift.org/t/swift-5-10-concurrency-and-xctest/69929/11

**Comment by hborla** [comment]
This was fixed by https://github.com/swiftlang/swift/pull/73720

Also, `Logger` now conforms to `Sendable` in the Xcode 16 SDK, so this particular example no longer needs `@preconcurrency`.
