### ISSUE TITLE
@MainActor does not enforce execution on main thread.

### ISSUE THREAD

**Issue by sumuhans** [swiftlang/swift#72224]
### Description

Please note that the code example I have attached is a Xcode project and in some cases uses some Apple Frameworks but the bug I am referring to appears to be in the Swift compiler itself, as the swift compiler seems to fail to fulfil a guarantee made in Swift evolution proposals connected to swift concurrency. The `@MainActor` seems to fail to enforce execution on the main thread in some cases as detailed below.

Apple developer documentation describes MainActor as “A singleton actor whose executor is equivalent to the main dispatch queue”.  There are other documents and official materials which state that any code annotated with `@MainActor` would be executed on the Main thread. 

For example SE 0316 has the following text
“Note that the data in this view controller, as well as the method that performs the update of this data, is isolated to the `@MainActor`. That ensures that UI updates for this view controller only occur on the main thread, and any attempts to do otherwise will result in a compiler error.”

 Another example is the WWDC talk 'Eliminate data races using Swift Concurrency', which states 

[Isolation to the main actor ](https://developer.apple.com/videos/play/wwdc2022/110351/?time=1020)[is expressed with the MainActor attribute.](https://developer.apple.com/videos/play/wwdc2022/110351/?time=1021)
[This attribute can be applied to a function or closure ](https://developer.apple.com/videos/play/wwdc2022/110351/?time=1024)[to indicate that the code must run on the main actor.](https://developer.apple.com/videos/play/wwdc2022/110351/?time=1027)
[Then, we say that this code is isolated to the main actor.](https://developer.apple.com/videos/play/wwdc2022/110351/?time=1032)
[The Swift compiler will guarantee ](https://developer.apple.com/videos/play/wwdc2022/110351/?time=1036)[that main-actor-isolated code will only be executed ](https://developer.apple.com/videos/play/wwdc2022/110351/?time=1038)[on the main thread, using the same mechanism ](https://developer.apple.com/videos/play/wwdc2022/110351/?time=1041)[that ensures mutually exclusive access to other actors.](https://developer.apple.com/videos/play/wwdc2022/110351/?time=1044)

But it appears to me that this promise is not kept in some cases. The discussion here https://forums.swift.org/t/suggestion-runtime-warnings-in-debug-builds-if-mainactor-methods-vars-are-called-from-background-threads/61537/14 mentions a few examples. One of which is addressed in issue https://github.com/apple/swift/issues/63189 

However, there seems to be six other ways in which the `@MainActor` checks could be defeated. Five of which are described here https://blog.hobbyistsoftware.com/2022/11/five-ways-to-break-swift-concurrency/  and an additional one mentioned in the discussion  https://forums.swift.org/t/suggestion-runtime-warnings-in-debug-builds-if-mainactor-methods-vars-are-called-from-background-threads/61537

I have tried to collect all of this in a simple project that reproduces this issue. Which is attached. Here is a summery of cases where `@MainActor` does not seem to fail to enforce execution on the main thread.

1. When called through #selector 
2. When called through Objective C code
3. When triggered through Notifications which uses #selector 
4. When triggered through Notifications using a closure (produces a warning in this case , but I expected a compiler error based on the resource cited above)
5. When the call is included in a block that is passed to Objective C code
6. When triggered through a delegate call
7. When a call is triggered through the ’set’ of a binding 

### Reproduction

Please see attached project
[MainActorBehaviorCheck.zip](https://github.com/apple/swift/files/14559614/MainActorBehaviorCheck.zip)

### Expected behavior

In all of the above cases, the code is expected to run on the main thread.

### Environment

Apple Swift version 5.9.2 (swiftlang-5.9.2.2.56 clang-1500.1.0.2.5)
Target: arm64-apple-macosx13.0

**Comment by hborla** [comment]
All of the cases you list are cases where the code is interoperating with other code that does not have static data-race safety checking, e.g. because it's implemented in Objective-C or in the Swift 5 language mode. [SE-0423: Dynamic actor isolation enforcement from non-strict-concurrency contexts](https://github.com/swiftlang/swift-evolution/blob/main/proposals/0423-dynamic-actor-isolation.md) solve these gaps at runtime with dynamic actor isolation checking.
