### ISSUE TITLE
`import typealias` causes invalid error claiming the symbol is a protocol

### ISSUE THREAD

**Issue by tristanlabelle** [swiftlang/swift#72724]
### Description

Using `import typealias` to import a typealias that aliases a protocol with the existential `any` modifier causes a compilation error, with the compiler claiming that the symbol is a protocol instead of a typealias.

### Reproduction

```swift
// Module A
public protocol Protocol {}
public typealias TypeAlias = any Protocol

// Module B
import protocol A.TypeAlias // Succeeds, incorrectly
import typealias A.TypeAlias // Fails with "'TypeAlias' was imported as 'typealias', but is a protocol"
```

### Expected behavior

The first line of module B should fail and the second line should succeed.

For backwards compatibility though, the first line could succeed with a warning, but the second line should definitely succeed.

### Environment

```
compnerd.org Swift version 5.11-dev (LLVM 1bcf1d71b715d0d, Swift a1d70b6086b16bb)
Target: x86_64-unknown-windows-msvc
```

**Comment by tristanlabelle** [comment]
@AnthonyLatsis , @li3zhen1 , there might be an unfortunate side-effect to the fix: I think it's impossible to write code that works both with a compiler from before and after the fix. I tried using:

```swift
#if swift(>=6.1)
import typealias Module.ExistentialProtocolTypealias
#else
import protocol Module.ExistentialProtocolTypealias
#endif
```

However a compiler with the fix can either build in Swift 6 mode or in 5 mode, which is what `#if swift` tests for, but it will still exhibit the fixed behavior in Swift 5 mode. Should the fix be conditional to the swift language level?

(happy to file a follow-up bug if needed)

**Comment by AnthonyLatsis** [comment]
Thanks for raising this, Tristan. I suppose it makes sense to gate the fix behind Swift 6 mode to somewhat offset the source compatibility impact, but you would still need to check the compiler version because already released Swift 6 compilers (and their Swift 6 mode) have the old behavior.

@hborla Could you advise on this?
