### ISSUE TITLE
Variable i was never mutated in `.enumerated()` for var loop; needs fix-it to suggest `for case (let _, var _)`

### ISSUE THREAD

**Issue by peterkos** [swiftlang/swift#72811]
### Description

Hello!

When using a `for var (i, element) in elements.enumerated()` loop that only modifies `element`, I receive this warning:

```sh
warning: variable 'i' was never mutated; consider changing to 'let' constant
        for var (i, element) in elements.enumerated() { 
```

~However, there's no way to only mark `i` as `let`, meaning this warning is stuck forever. This feels like a bug, as (imo) there should be a way to indicate one element of the `EnumeratedSequence` tuple (is it a tuple?) is immutable, and one is mutable.~ ☂️(Edit: there is! From @AnthonyLatsis's comment below: `for case (let i, var element) ...`

I assumed `(i, element)` from `.enumerated()` worked as an "opaque" tuple, where the tuple is itself mutable, and modifying b in `(a, b)` constitutes modifying `(a, b)` vs. just `(b)`. 

### Reproduction

```swift

protocol ManuallyOrderable {
    var index: Int? { get set }
}

struct Reverser<T: ManuallyOrderable> {
    func reverse(elements: [T]) {
        // Writable local copy for ease of demo
        var elements = elements

        // Workaround
        for i in elements.indices {
            elements[i].index = i
        }

        // ⚠️ warning: variable `i` was never mutated
        for var (i, element) in elements.enumerated() {
            element.index = i
        }
    }
}
```

### Expected behavior

The warning could use a fix-it to suggest the proper syntax -- or, potentially, the syntax could allow the use of `let, var` directly without `case`.

```swift

// ⚠️ warning: variable `i` was never mutated
for var (i, element) in elements.enumerated() {
    element.index = i
}

// ✅ Correct syntax
for case (let i, var element) in elements.enumerated() {
    element.index = i
}

// 👀 Additional suggestion
for (let i, var element) in elements.enumerated() {
    element.index = i
}

```

### Environment

Apple Swift version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4)
Target: arm64-apple-macosx14.0

**Comment by AnthonyLatsis** [comment]
Reduced:
```swift
do {
  let s: [(Int, Int)]
  for var (_, x2) in s {
    _ = x2
  }
}
```

> However, there's no way to only mark `i` as `let`

There is, though not at all obvious because of how used we are to the `for x` (aka `for case let x`) pattern matching sugar in `for`-`in` statements: `for case (let i, var element)`

This needs a targeted fix-it.

**Comment by AnthonyLatsis** [comment]
This is a high-tier good first issue for someone fluent in Swift pattern matching.

**Comment by peterkos** [comment]
Ooh, thanks! I updated the issue desc / title to reflect that.

How feasible is it to enable the same sugar here, to allow `for (let _, var _)`?

**Comment by AnthonyLatsis** [comment]
> How feasible is it to enable the same sugar here, to allow `for (let _, var _)`?

Well, this *would need* to go through the Swift evolution process. We have two kinds of pattern sugar in `for`-`in` loops at present: `for x` (`for case let x`) and `for var x` (`for case var x`).

**Comment by Jamezzzb** [comment]
@AnthonyLatsis I'd like to work on this, can you assign it to me please?

**Comment by Jamezzzb** [comment]
@AnthonyLatsis @peterkos I noticed you can actually do:
```swift
do {
  let s: [(Int, Int)] = [(1, 2)]
  for (i, var x) in s {
    x = i
    // do something with x
    _ = x
  }
}

```
And `i` will be implicitly `let`.  Should this be the fix-it?

**Comment by AnthonyLatsis** [comment]
Cool, that’s even better!

**Comment by Jamezzzb** [comment]
I have ended up being a bit busier than I thought I would, my apologies, I am going to unassign myself.

**Comment by Anthony-Eid** [comment]
Could I please be assigned this issue? This seems like a great learning opportunity!

**Comment by pwongxy** [comment]
Hi @Anthony-Eid are you still working on this issue?
if not, I want to give it a try as my first issue.

**Comment by Anthony-Eid** [comment]
> Hi @Anthony-Eid are you still working on this issue? if not, I want to give it a try as my first issue.

I un assigned myself, so go ahead!

**Comment by pwongxy** [comment]
Hi @AnthonyLatsis , could you assign this to me? I would like to give it a try.

**Comment by AnthonyLatsis** [comment]
@pwongxy You’re welcome to! Did you get a notification of some sort for the assignment btw?

**Comment by pwongxy** [comment]
@AnthonyLatsis thanks. yes, I did get notified through through email for the assignment.

**Comment by AnthonyLatsis** [comment]
OK, good to know, thanks.
