### ISSUE TITLE
link error caused by conforming C++ type to Equatable

### ISSUE THREAD

**Issue by wtholliday** [swiftlang/swift#72826]
### Description

After conforming a C++ type to Equatable, I get a link error. This requires using attached project since it seems the extension needs to be in a separate translation unit.

[CompilerCrash.zip](https://github.com/apple/swift/files/14859774/CompilerCrash.zip)

```
duplicate symbol '_$sSo11SharedThingVMa' in:
    [redacted]/Build/Products/Debug/TestTarget2.o
    [redacted]/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrashApp.o
```

### Reproduction

```swift
let thing = SharedThing.create()
let array = [thing, thing]
```

```swift
extension SharedThing: Equatable {
    public static func == (lhs: SharedThing, rhs: SharedThing) -> Bool {
        true
    }
}
```

where SharedThing is:

```swift
#pragma once

#include "IntrusiveRefCounted.hpp"
#include <swift/bridging>

struct SharedThing : public IntrusiveRefCounted<SharedThing> {

    static SharedThing* _Nonnull create();

    ~SharedThing();

private:
} SWIFT_SHARED_REFERENCE(retainSharedThing, releaseSharedThing);

void retainSharedThing(SharedThing * _Nonnull);
void releaseSharedThing(SharedThing * _Nonnull);
```

### Expected behavior

No link error

### Environment

swift-driver version: 1.90.11.1 Apple Swift version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4)
Target: arm64-apple-macosx14.0

**Comment by MaxDesiatov** [comment]
cc @egorzhdan

**Comment by egorzhdan** [comment]
This was fixed by https://github.com/swiftlang/swift/pull/74208.
