### ISSUE TITLE
Warnings output for files inside preconcurrency imported library

### ISSUE THREAD

**Issue by radianttap** [swiftlang/swift#73075]
### Description

When importing [LiveChat](https://github.com/livechat/chat-window-ios) library into project with strict-concurrency-checking=complete, compiler correctly shows concurrency warning:

<img width="883" alt="Screenshot 2024-04-17 at 10 52 39" src="https://github.com/apple/swift/assets/80697/2dabe104-2806-4dcd-902f-ab797a4116fc">

Adding `@preconcurrency` removes that warning:

<img width="438" alt="Screenshot 2024-04-17 at 10 54 24" src="https://github.com/apple/swift/assets/80697/4b07ad23-fd0f-4fa1-8d15-db756f3fd8bf">

but it also shows warnings for the accessed code inside the library:

<img width="1217" alt="Screenshot 2024-04-17 at 10 54 11" src="https://github.com/apple/swift/assets/80697/26538d10-16b3-4bb2-bdc4-b9cac06d61ed">

### Reproduction

Attached is the super simple sample project that loads the LiveChat library and accesses this one parameter.
[Preconcurrency-LiveChat.zip](https://github.com/apple/swift/files/15008833/Preconcurrency-LiveChat.zip)

### Expected behavior

No warnings should be shown for the code inside the imported library.

(I'm not sure is some setting in the imported library is the culprit)

### Environment

```
swift-driver version: 1.90.11.1 Apple Swift version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4)
Target: x86_64-apple-macosx13.0
```

**Comment by hborla** [comment]
This should be fixed by https://github.com/swiftlang/swift/pull/74624
