### ISSUE TITLE
Possible miscompile that leads to runtime crash

### ISSUE THREAD

**Issue by mattmassicotte** [swiftlang/swift#73364]
### Description

I was debugging a runtime crash in my application, and I have traced it down to some code that seems like it should not compile. It appears related to opaque return types and `#available`.

### Reproduction

```swift
import SwiftUI

extension View {
	func plaformOnHover(perform action: @escaping (Bool) -> Void) -> some View {
		if #available(iOS 13.4, *) {
			return self.onHover(perform: action)
		}

		return self
	}
}
```

If I remove the `#available` check, I get this error, which seems expected:

```
Function declares an opaque return type 'some View', but the return statements in its body do not have matching underlying types
```

### Expected behavior

I would expect the code that includes the `#available` to also fail to compile.

### Environment

I can reproduce this with both Swift 5.10 and Swift 6 snapshot 2024-04-27.

**Comment by tshortli** [comment]
Opaque return types with limited availability were added to the language with [SE-0360](https://github.com/swiftlang/swift-evolution/blob/main/proposals/0360-opaque-result-types-with-availability.md) so it is not a mistake that the code compiles.

**Comment by tshortli** [comment]
@mattmassicotte I'm going to close this as "behaving correctly" since it's expected that the compiler accept the code in your example.

**Comment by mattmassicotte** [comment]
Thank you for the explaination. I'll have to read SE-0360 more closely!
