### ISSUE TITLE
Swift will not infer opaque return type of generic function

### ISSUE THREAD

**Issue by yosshi4486** [swiftlang/swift#73449]
#### NG Pattern
When using an opaque type as the return-value, the compiler says "Type 'Impl' does not conform to protocol 'X'".

```swift
import SwiftUI

protocol X {
    associatedtype Body: View
    func doSomething<T>(parameter: T) -> Body
}

struct Impl: X {
    // Type 'Impl' does not conform to protocol 'X'
    func doSomething<T>(parameter: T) -> some View {
        Text("Problem Occur")
    }
}
```

#### OK Pattern
When using a concrete type as the return-value, the compiler is silent.

```swift
import SwiftUI

protocol X {
    associatedtype Body: View
    func doSomething<T>(parameter: T) -> Body
}

struct Impl: X {
    func doSomething<T>(parameter: T) -> Text {
        Text("Problem Occur")
    }
}
```

### Expected behavior

`Impl` conform `X` even when it returns `some View`, and the compiler says nothing.

### Environment

swift-driver version: 1.90.11.1 Apple Swift version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4)
Target: arm64-apple-macosx14.0

### Additional information

Xcode 15.3 (15E204a)
macOS 14.4.1（23E224）

swift-forum discussion: https://forums.swift.org/t/swift-will-not-infer-opaque-return-type-of-generic-function/67233

**Comment by slavapestov** [comment]
This is correct behavior. The opaque return type of `Impl.doSomething()` depends on the generic parameter `T`, so it cannot witness an associated type requirement which can only depend on the generic parameters of the conforming type itself.
