### ISSUE TITLE
indices(of:) is only available in macOS 9999 or newer

### ISSUE THREAD

**Issue by TeamPuzel** [swiftlang/swift#73737]
### Description

<img width="691" alt="image" src="https://github.com/apple/swift/assets/94306330/777a6e31-0258-4d6a-b67a-f96d9ba0980c">

### Reproduction

```swift
let a = "%".indices(of: "%")
```

### Expected behavior

I would expect this method to be available sometime during my lifetime.

### Environment

Apple Swift version 6.0-dev (LLVM 3417addab6ff197, Swift d677b7c23fd6355)
Target: arm64-apple-macosx14.0

**Comment by hborla** [comment]
Fixed by https://github.com/swiftlang/swift/pull/74367
