### ISSUE TITLE
Specialized function are ignored in a generic context and swift unable to pick the proper specialization

### ISSUE THREAD

**Issue by llacroix** [swiftlang/swift#73842]
### Description

Swift is unable select the proper function to call in a generic context. When a unconstrained function is provided, all specialized functions will be ignored in the generic context but not in a non generic context. 

When no unconstrained function is provided, specialized functions are properly called in a non generic context but swift is unable to select the proper specialized function of a concrete generic type.

Commenting this in the reproduction code will make the code not compile and reproduce the second case in which swift cannot pick the proper specialization.

```swift
extension Updater {
    func apply() -> Subject {
        subject
    }
}
```

When removing the generic extension and one of the 2 specialized extension. It will complain that either Remove or Add cannot be converted to the other type since only 1 modifier type is implemented. This sounds like a proper behaviour. 

### Reproduction

```swift
struct Updater<Subject, Modifier> {
    let subject: Subject
    let modifier: Modifier

    init(_ subject: Subject, _ modifier: Modifier) {
        self.subject = subject
        self.modifier = modifier
    }
}

extension Updater {
    func apply() -> Subject {
        subject
    }
}

extension Updater where Subject == State, Modifier == Add {
    func apply() -> Subject {
        State(value: subject.value + modifier.value)
    }
}

extension Updater where Subject == State, Modifier == Remove {
    func apply() -> Subject {
        State(value: subject.value - modifier.value)
    }
}

struct State {
    let value: Int
}

struct Add {
    let value: Int
}

struct Remove {
    let value: Int
}


var state = State(value: 0)
print(state)
state = Updater(state, Add(value: 1)).apply()
print(state)
state = Updater(state, Remove(value: 1)).apply()
print(state)
state = Updater(state, Remove(value: 1)).apply()
print(state)

func apply_action<S, M>(_ state: S, _ modifier: M) -> S {
    let updater = Updater(state, modifier)
    print(updater)
    return updater.apply()
}

state = apply_action(state, Remove(value: 1))
print(state)
state = apply_action(state, Remove(value: 1))
print(state)

state = apply_action(state, Add(value: 1))
print(state)
state = apply_action(state, Add(value: 1))
print(state)
```

### Expected behavior

Swift should be able to call the specialized functions when the type matches the ones in the specialized functions. If the method was called with <State, Add>, it shouldn't get confused because there is an existing method declared in an extension with `where Modifier == Remove` since `Add` isn't `Remove`. 

A specialized function should be picked over a more generic one if available instead of just ignoring the specialized ones in the generic context but doing the complete opposite outside of the "non generic context". 

### Environment

Swift version 6.0-dev (LLVM cef183591317ec7, Swift 66e311074bff491)

### Additional information

My main goal here is to be able to eventually have a way to pass a generic Action type from a Queue/List and be able to implement specialized transformation of certain types instead of having to rely on a big function with:

```
if let action = modifier as? Add
if let action = modifier as? Remove
....
```

This way we can implement new behaviour without having to modify a big enum or big dispatch method.

**Comment by llacroix** [comment]
On the swift forums, it seems like this behaviour is caused mainly because at the moment of generating the code swift only look for local static types. So unfortunately, the following function doesn't have any knowledge of the type passed as `<S, M>`. 

```
func apply_action<S, M>(_ state: S, _ modifier: M) -> S {
    let updater = Updater(state, modifier)
    print(updater)
    return updater.apply()
}
```

So it's not like the generic function act more or less like a template where the static type are funnelled down from some calling point. 

As if calling `apply_action(State, Remove)` would generate a specialized version `apply_action(_ state: State, _ modifier: Remove)` so `Updater` could resolve the function properly knowing that it's really a `Updater<State, Remove>` type and nothing else.

**Comment by hborla** [comment]
Yes, this is a fundamental behavior of separate type checking for generic code, rather than requiring substitutions in order to type check like C++ templates. Instead of using overloading, you should implement specialization points as requirements of protocols that are imposed as constraints on the generic arguments, as protocol requirements are dynamically dispatched based on the generic argument at runtime. For example, implement the subtraction and addition operations on the `Remove` and `Add` types respectively, and call it via a protocol requirement on the `modifier` value.
