### ISSUE TITLE
ScrollPosition view modifier behaves unexpectedly when using (anchor = nil).

### ISSUE THREAD

**Issue by KhaledShehadeh** [swiftlang/swift#73918]
### Description

It seems when I put the anchor = nil, it behaves like anchor = .top.

This behaves different than the proxy.scrollTo() method from the scrollviewreader which takes same parameters as .scrollPosition() view modifier but behaves differently.

### Reproduction

```swift
ScrollView
{
  LazyVStack
  {
    ForEach(vm.posts)
    {
      comment in
							
      PostCell()
    }
  }
}
.scrollPosition(id: $scrollTo, anchor: nil)
```

The view scrolls but,
1. It always aligns element to .top

### Expected behavior

Like ScrollViewReader's proxy.scrollTo

```swift
ScrollView
{
  ScrollViewReader
  {
    proxy in
    LazyVStack
    {
	ForEach(vm.posts)
	{
	  comment in
							
	    PostCell()
	      .id(comment.id)
	 }
    }
    .onChange(of: scrollTo) { _, newValue in
	proxy.scrollTo(newValue, anchor: nil)
    }
  }
}
```

When nil is passed:
1. When element is in view, scrollviewreader does not scroll
2. When element is on above, scrollviewreader scrolls to element aligning it to the top
3. When element is below, scrollviewreader scrolls to element aligning it to the bottom

### Environment

Apple Swift version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4)
Target: x86_64-apple-darwin23.5.0

**Comment by hborla** [comment]
This is an issue with Apple's SwiftUI framework, not with the Swift compiler. Please file a bug report using [Apple Feedback Assistant](https://developer.apple.com/bug-reporting/).
