### ISSUE TITLE
Optional Checking of a Generic Type not working using swift 6.0  on Mac (swiftlang-6.0.0.3.300 clang-1600.0.20.10)

### ISSUE THREAD

**Issue by agiokas** [swiftlang/swift#74282]
### Description

When trying to check if a Type conforms to a protocol which is extending Optional it delivers wrong result.

Checking does not work when using swiftlang-6.0.0.3.300 clang-1600.0.20.10 with target MacOS

Code works as expected using swiftlang-6.0.0.3.300 clang-1600.0.20.10 with target iOS
Code works as expected using swiftlang-5.10.0.13 clang-1500.3.9.4 with target MacOS
Code works as expected using swiftlang-5.10.0.13 clang-1500.3.9.4 with target iOS

### Reproduction

```swift
// swift-tools-version: 5.9
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "OptionalCheck",
    products: [
        .library(name: "OptionalCheck", targets: ["OptionalCheck"]),
    ],
    targets: [
        .target(name: "OptionalCheck"),
        .testTarget(name: "OptionalCheckTests", dependencies: ["OptionalCheck"] ),
    ]
)
```

```swift
import XCTest

final class OptionalCheckTests: XCTestCase {
    func testExample() throws {
        XCTAssertFalse(isOptional(Int.self), "Int is not an Optional")
        XCTAssertTrue(isOptional(Int?.self), "Int? is an Optional")
    }
    
    func isOptional<R>(_ type: R.Type) -> Bool {
        R.self is OptionalProtocol.Type
    }
}

protocol OptionalProtocol {}
extension Optional: OptionalProtocol {}
```

### Expected behavior

using swiftlang-6.0.0.3.300 clang-1600.0.20.10 and target MacOS it should work like in swift 5.10 or like  target iOS

### Environment

swift-driver version: 1.109.2 Apple Swift version 6.0 (swiftlang-6.0.0.3.300 clang-1600.0.20.10)
Target: arm64-apple-macosx14.0

**Comment by xedin** [comment]
@mikeash This looks like a runtime problem and not type-checker one, output of Sema is identical between 5.10 and 6.0 in this case but runtime behavior is different.

**Comment by mikeash** [comment]
This specifically happens when using the new swiftc and running on an older OS. The new swiftc emits the conformance with an invertible protocol requirement. But the old runtime doesn't know how to handle that requirement. `checkGenericRequirement` bonks into this check:

```
  if (!req.hasKnownKind())
    return TypeLookupError("unknown kind");
```

And the check fails. @kavon how is this supposed to work when targeting an older OS version?

**Comment by kavon** [comment]
This should be fixed by https://github.com/swiftlang/swift/pull/74604

**Comment by kavon** [comment]
For release/6.0: https://github.com/swiftlang/swift/pull/74605
