### ISSUE TITLE
Creating a project with double quotation marks (") messes with strings in auto-generated code

### ISSUE THREAD

**Issue by 0osh** [swiftlang/swift#74379]
### Description

Upon creating a project with " in it, something called `#sourceLocation` has a string and Xcode does not properly escape the " in the project name, causing the line to look like
```java
#sourceLocation(file: "/path/to/file/project-with-"/project-with-"/ContentView.swift", line: 58)
```
where the string starts and stops. This prevents the preview from compiling even when no changes are made to the default hello world program.

### Reproduction

Create an app project with " in the name

### Expected behavior

For it to properly escape the " or replace it with a dash/hyphen -

### Environment

I foudn this bug in Xcode Version 15.4 (15F31d)

**Comment by hborla** [comment]
It sounds like this is an issue with Xcode project templates, not with the Swift compiler. Please file the issue using [Apple's Feedback Assistant](https://developer.apple.com/bug-reporting/).
