### ISSUE TITLE
@_noLocks doesn't work with Builtin.atomicload_{}

### ISSUE THREAD

**Issue by jcavar** [swiftlang/swift#74407]
### Description

The new Atomic type cannot be used with @_noLocks since a simple usage reports a violation. It seems that the issue is in the implementation of Atomic `load` and the use `Builtin.atomicload_{}` family of functions.

A simplified code sample is available below. Required settings:

```
swiftSettings: [
    .unsafeFlags(["-disable-availability-checking"]),
    .enableExperimentalFeature("StaticExclusiveOnly"),
    .enableExperimentalFeature("RawLayout"),
    .enableExperimentalFeature("BuiltinModule")
]
```

### Reproduction

```swift

import Builtin

public struct MyAtomic: ~Copyable {
  var rawAddress: Builtin.RawPointer {
    Builtin.unprotectedAddressOfBorrow(self)
  }
}

extension MyAtomic {
  @_noLocks
  public func load(ordering: AtomicLoadOrdering) -> Int {
    let result = Builtin.atomicload_monotonic_Int64(rawAddress) // error: this code pattern can cause locking
    return 1
  }
}

```

### Expected behavior

Atomic load doesn't cause locking and performance annotation doesn't report violation.

### Environment

Apple Swift version 6.0-dev (LLVM 57177aa1b91540b, Swift 3889ede01784b87)
Target: arm64-apple-macosx14.0

### Additional information

cc @eeckstein @Azoy

**Comment by Azoy** [comment]
Looks like we classify atomic instructions as locking:
```cpp
case BuiltinValueKind::Fence:
case BuiltinValueKind::CmpXChg:
case BuiltinValueKind::AtomicLoad:
case BuiltinValueKind::AtomicStore:
case BuiltinValueKind::AtomicRMW:
  return RuntimeEffect::Locking;
```

**Comment by jcavar** [comment]
Is there a reason for that? Can we mark them as `NoEffect`?

**Comment by jcavar** [comment]
Hey @Azoy and @eeckstein, just wanted to check in and see if there have been any updates on this issue?

**Comment by eeckstein** [comment]
Let's just fix this: https://github.com/swiftlang/swift/pull/75615

**Comment by jcavar** [comment]
Thank you! Works great!
