### ISSUE TITLE
Enum constructors aren't inferred to be Sendable

### ISSUE THREAD

**Issue by mattmassicotte** [swiftlang/swift#74485]
### Description

I *think* that [SE-0418](https://github.com/swiftlang/swift-evolution/blob/main/proposals/0418-inferring-sendable-for-methods.md) should apply to the following code, but this produces an error:

```
error: converting non-sendable function value to '@Sendable (Enum1) -> Enum2' may introduce data races
10 | 
11 | func test() {
12 |     testConvert(Enum2.bar)
   |                       `- error: converting non-sendable function value to '@Sendable (Enum1) -> Enum2' may introduce data races
13 | }
14 | 
```

### Reproduction

```swift
func testConvert<T, U>(_ transform: @Sendable @escaping (T) -> U) {}

enum Enum1 {
    case foo
}

enum Enum2 {
    case bar(Enum1)
}

func test() {
    testConvert({ @Sendable in Enum2.bar })
}
```

### Expected behavior

This should compile without error.

### Environment

Apple Swift version 6.0-dev (LLVM bf8bbb910874156, Swift a0bb875256e41ae)
Target: arm64-apple-macosx14.0

**Comment by xedin** [comment]
I think we already have a dupe for this (I'll try to find it), the problem here is not with initializer itself it's with how the partially applied access is modeled with autoclosures.

**Comment by hborla** [comment]
Fixed by https://github.com/swiftlang/swift/pull/74363
