### ISSUE TITLE
[SE-0425] `Int128` and `UInt128` APIs have different attributes

### ISSUE THREAD

**Issue by benrimmington** [swiftlang/swift#74481]
For the following APIs:

* [`Int128`](https://github.com/apple/swift/blob/main/stdlib/public/core/Int128.swift) uses either `@_transparent`, or `@inline(__always)`, or no attribute.

* [`UInt128`](https://github.com/apple/swift/blob/main/stdlib/public/core/UInt128.swift) uses `@inlinable` only.

| APIs                                      | `Int128`            | `UInt128`    |
| :---------------------------------------- | :------------------ | :----------- |
| `zero`, `min`, `max`                      | `@_transparent`     | `@inlinable` |
| `init(_builtinIntegerLiteral:)`           | `@_transparent`     | `@inlinable` |
| `addingReportingOverflow(_:)`             | `@_transparent`     | `@inlinable` |
| `subtractingReportingOverflow(_:)`        | `@_transparent`     | `@inlinable` |
| `multipliedReportingOverflow(by:)`        | `@inline(__always)` | `@inlinable` |
| `dividedReportingOverflow(by:)`           | `@inline(__always)` | `@inlinable` |
| `remainderReportingOverflow(dividingBy:)` | `@inline(__always)` | `@inlinable` |
| `*`, `/`, `%`                             |                     | `@inlinable` |
| `&=`, `\|=`, `^=`, `&>>=`, `&<<=`         |                     | `@inlinable` |
| `trailingZeroBitCount`                    |                     | `@inlinable` |
| `bitWidth`                                | `@_transparent`     | `@inlinable` |
| `nonzeroBitCount`                         |                     | `@inlinable` |
| `leadingZeroBitCount`                     |                     | `@inlinable` |
| `byteSwapped`                             |                     | `@inlinable` |

Should the attributes be the same, when the APIs have the same implementations?

(`main` and `release/6.0` branches.)

**Comment by Azoy** [comment]
I put up a PR to hopefully address this. I think all of these should just be `@_transparent` like their sister integer types are doing.
