### ISSUE TITLE
Fix-it to restate inherited '@unchecked Sendable' conformance

### ISSUE THREAD

**Issue by mattmassicotte** [swiftlang/swift#74500]
### Motivation

Given the scenario, I think it is very likely that developers will want to either just automatically re-state the conformance or opt into full checking (which doesn't currently work: https://github.com/apple/swift/issues/74498)

```swift
class A: @unchecked Sendable {
}

// warning: class 'B' must restate inherited '@unchecked Sendable' conformance
class B: A {
}
```

### Proposed solution

Fix it to add the `@unchecked Sendable`

**Comment by tplaymeow** [comment]
Hi! I'd like to take this issue
