### ISSUE TITLE
Bad diagnostic when constructor can't initialize isolated property

### ISSUE THREAD

**Issue by NachoSoto** [swiftlang/swift#74557]
### Description

The following code is not correct, but the diagnostic it produces is very misleading.

### Reproduction

```swift
public final class Data {
  // Return from initializer without initializing all stored properties
  init() { }

  @MainActor
  private let n: Int = f()
}

@MainActor
func f() -> Int { 0 }
```

### Expected behavior

The diagnostic should mention that the non-isolated `init` can't invoke the `@MainActor` isolated `f`.

### Environment

swift-driver version: 1.109.2 Apple Swift version 6.0 (swiftlang-6.0.0.3.300 clang-1600.0.20.10)
Target: arm64-apple-macosx14.0

**Comment by gottesmm** [comment]
@NachoSoto next time, can you please put the actual output from the compiler. Makes it easier to see exactly what is going on. That way we have something like this that shows where the source loc is/etc:

```
%   ./bin/swift-frontend test.swift -swift-version 6 -c                
test.swift:3:12: error: return from initializer without initializing all stored properties
 1 | public final class Data {
 2 |   // Return from initializer without initializing all stored properties
 3 |   init() { }
   |            `- error: return from initializer without initializing all stored properties
 4 | 
 5 |   @MainActor
 6 |   private let n: Int = f()
   |               `- note: 'self.n' not initialized
 7 | }
 8 | 
```

That being said... thank you for the test case! = ).

**Comment by NachoSoto** [comment]
Good to know, will do that moving forward!

**Comment by NachoSoto** [comment]
cc @hborla
