### ISSUE TITLE
What does it mean for nonisolated(unsafe) to be applied to functions?

### ISSUE THREAD

**Issue by mattmassicotte** [swiftlang/swift#74571]
### Description

I *think* SE-0412 is clear that the unsafe part of this attribute should apply only to storage.

### Reproduction

```swift
@MainActor
class MyClass {
    nonisolated(unsafe) func whatDoesThisMean() {

    }
}
```

### Expected behavior

I was expecting a warning with a fix-it to remove `unsafe`. 

### Environment

Apple Swift version 6.0-dev (LLVM 5f87d6ee2f8c800, Swift 5c01ca13866debd)
Target: arm64-apple-macosx14.0

**Comment by ktoso** [comment]
Thanks for reporting, we'll warn on this now
