### ISSUE TITLE
Swift's Windows installer is missing the features.json file for docc and clang

### ISSUE THREAD

**Issue by jakepetroules** [swiftlang/swift#74634]
### Description

I'd expect "features.json" to be present in the following directories:

%LOCALAPPDATA%\Programs\Swift\Toolchains\6.0.0+Asserts\usr\share\clang
%LOCALAPPDATA%\Programs\Swift\Toolchains\6.0.0+Asserts\usr\share\docc

Currently, it is only present in

%LOCALAPPDATA%\Programs\Swift\Toolchains\6.0.0+Asserts\usr\share\swift

### Reproduction

N/A

### Expected behavior

N/A

### Environment

Swift version 6.0-dev (LLVM e878388283d7b73, Swift eb92e6e50035d21)
Target: x86_64-unknown-windows-msvc

**Comment by compnerd** [comment]
DocC is not yet available due to this outstanding change: https://github.com/apple/swift-docc/pull/668

Adding in features.json should just be a matter of updating the manifest in https://github.com/apple/swift-installer-scripts
