### ISSUE TITLE
Unexpected behavior of Sequence.split(separator:maxSplits:omittingEmptySubsequences:)

### ISSUE THREAD

**Issue by schuelermine** [swiftlang/swift#74655]
### Description

I would expect
```swift
sequence.split(separator: separator, maxSplits: n)
```
to be equivalent to
```swift
sequence.split(separator: separator, maxSplits: n, omittingEmptySubsequences: false).filter { !$0.isEmpty }
```

But this is not the case! With `omittingEmptySubsequences`, `split` incorrectly strips all leading separators before splitting.
Here are a few examples, where we call `.split(separator: "/", maxSplits: 1)`:
| Input string | Expected result | Actual result | Without omission |
| ------------ | --------------- | ------------- | ---------------- |
| `"/a/"`      | `["a/"]`        | `["a"]`       | `["", "a/"]`     |
| `"/a/b"`     | `["a/b"]`       | `["a", "b"]`  | `["", "a/b"]`    |
| `"//a/"`     | `["/a/"]`       | `["a"]`       | `["", "/a/"]`    |
| `"//a/b"`    | `["/a/b"]`      | `["a", "b"]`  | `["", "/a/b"]`   |

### Reproduction

```swift
print("//a/b".split(separator: "/", maxSplits: 1))
// prints ["a", "b"]
```

### Expected behavior

printing `["/a/b"]`

### Environment

Swift version 5.10.1 (swift-5.10.1-RELEASE)
Target: x86_64-unknown-linux-gnu

**Comment by schuelermine** [comment]
I've just now realized it's possible to construe this as correct, but it was certainly unexpected.

**Comment by schuelermine** [comment]
I would expect the result from
```swift
["x/y/z", "/y/z", "x//y/z", "//y/z"].map {
    $0.split(separator: "/", maxSplits: 1, omittingEmptySubsequences: true)
}
```
to be one of
- `[["x", "y/z"], ["y/z"], ["x", "/y/z"], ["/y/z"]]`
- `[["x", "y/z"], ["y", "z"], ["x", "y/z"], ["y", "z"]]`
- `[["x", "y/z"], ["y/z"], ["x", "y/z"], ["y/z"]]`
but not `[["x", "y/z"], ["y", "z"], ["x", "/y/z"], ["y", "z"]]` which is what is currently output.

**Comment by natecook1000** [comment]
Hi @schuelermine – the behavior that you're seeing from `split` is the expected behavior. In particular, the code that you're expecting to be equivalent does _not_ match the intended behavior of `split`. Omitted empty subsequences do not count toward the number of splits when using a limiting `maxSplits` parameter. For example:

```swift
print("a////////b/c".split(separator: "/", maxSplits: 2))
// ["a", "b", "c"]
```

The interaction between those two parameters is definitely subtle and tricky! We could likely use some better documentation of how they interact when used together.

**Comment by schuelermine** [comment]
Hi,

in this case, I don’t understand why `"//a".split(separator: "/", maxSplits: 2)` is `["a"]`, and not `["/a"]`.
