### ISSUE TITLE
Parameter packs seem to interfere with region-based isolation

### ISSUE THREAD

**Issue by mattmassicotte** [swiftlang/swift#74688]
### Description

This code seems like it should be exactly the kind of thing that region-based isolation can prove is race-free.

```
test.swift:13:20: error: sending 'self'-isolated value of type 'Int' with later accesses to actor-isolated context risks causing data races
11 |     let value = 10
12 | 
13 |     await fooActor.message(value)
   |                    `- error: sending 'self'-isolated value of type 'Int' with later accesses to actor-isolated context risks causing data races
14 | }
15 | 
```

### Reproduction

```swift
actor FooActor<each T> {
    var messages: [(repeat each T)] = []

    func message(_ num: repeat each T) {
        messages.append((repeat each num))
    }
}

func foo() async {
    let fooActor = FooActor<Int>()
    let value = 10

    await fooActor.message(value)
}
```

### Expected behavior

I would expect this to compile without error.

### Environment

Apple Swift version 6.0-dev (LLVM 5b37bd4c1c578e9, Swift 54898ce105c7185)
Target: arm64-apple-macosx14.0

**Comment by gottesmm** [comment]
So what is happening here is that we are erroring on the pack box which is a Pack<Int>. But the diagnostic is just dropping the type info from the pack so it is just saying Int... even though it is Pack<Int>

**Comment by gottesmm** [comment]
There is something else around packs that is interesting here. For one, we are considering a specialized pack with just an Int to be non-Sendable. I would assume that it would be Sendable since it just contains an int and the stack location will not escape... hmm...

**Comment by mattmassicotte** [comment]
I actually love the train-of-thought updates here. So fascinating to hear about it from someone that actually undertandings what's going on 😅

**Comment by vanvoorden** [comment]
Hmm… this compiles for me with no warning and no error from `Xcode_16_beta_2`:

```text
swift-driver version: 1.110 Apple Swift version 6.0 (swiftlang-6.0.0.4.52 clang-1600.0.21.1.3)
Target: arm64-apple-macosx14.0
```

**Comment by twof** [comment]
@vanvoorden 
I'm on beta 2 as well and I've got it failing. Are you in Swift 6 mode?

**Comment by mattmassicotte** [comment]
Yeah just double-checked with swift-6.0-DEVELOPMENT-SNAPSHOT-2024-06-22. 6 mode, error. 5 mode, same thing as a warning.

**Comment by vanvoorden** [comment]
> I'm on beta 2 as well and I've got it failing. Are you in Swift 6 mode?

@twof Ahh… I see. I was building a SwiftPM package from Xcode. The package was using `swift-tools-version: 6.0`… which I thought would imply Swift 6. I built the package from the command line and that is where I see the error now.

**Comment by mattmassicotte** [comment]
This compiles correctly with 6.1-dev (LLVM 38c9bd4e92f23a7, Swift 91c6425a54ae3b3) !
