### ISSUE TITLE
term "non-isolated" appears in diagnostic

### ISSUE THREAD

**Issue by mattmassicotte** [swiftlang/swift#74749]
### Description

Per https://github.com/swiftlang/swift/issues/73982, the compiler seems to have standarized on using the spelling "nonisolated" in prose. However, here's an example where "non-isolated" is used.

```
test.swift:4:5: error: main actor-isolated var 'global' can not be mutated from a non-isolated context
1 | var global = 42
  |     `- note: mutation of this var is only permitted within the actor
2 | 
3 | func mutate() {
  |      `- note: add '@MainActor' to make global function 'mutate()' part of global actor 'MainActor'
4 |     global += 1
  |     `- error: main actor-isolated var 'global' can not be mutated from a non-isolated context
5 | }
6 | 
```

### Reproduction

```swift
var global = 42

func mutate() {
    global += 1
}
```

### Expected behavior

"nonisolated" should be used everywhere

### Environment

Apple Swift version 6.0-dev (LLVM 5b37bd4c1c578e9, Swift 54898ce105c7185)
Target: arm64-apple-macosx14.0

**Comment by mattmassicotte** [comment]
It's also not too late to take this opportunity to, instead, move to "non-isolated" everywhere outside source!

("nonisolated" is not in the en_US spelling dictionary that ships with macOS, and while I know that's an easy one to fix, still reads very weird to me)

**Comment by EngOmarElsayed** [comment]
@hborla I want to fix this issue. How can I start ?

**Comment by ktoso** [comment]
Thanks for wanting to contribute!

This specific issue I believe was already solved though:

```
ERROR(isolated_property_mutation_in_nonisolated_context,none,
      "actor-isolated %kind0 can not be %select{referenced|mutated}1 "
      "from a nonisolated context",
      (const ValueDecl *, bool))
```

Generally for messages you'd go look in the DiagnosticsSIL.def file and adjust them; and their use accordingly. this was fixed in 474aa47732f0de33115d877ac809d388c0682ded already though

**Comment by ktoso** [comment]
Please have a look at other good first issues though, thank you! @EngOmarElsayed !

**Comment by EngOmarElsayed** [comment]
@ktoso to you have anything in mind because all the issues I saw are open but have a open PR
