### ISSUE TITLE
Presentation different for identical concurrency note

### ISSUE THREAD

**Issue by mattmassicotte** [swiftlang/swift#74751]
### Motivation

I found two situations that are recommending the same thing, but in different ways.

input 1:

```swift
var global = 42
```

diagnostics 1:

```
test.swift:1:5: error: var 'global' is not concurrency-safe because it is non-isolated global shared mutable state
1 | var global = 42
  |     |- error: var 'global' is not concurrency-safe because it is non-isolated global shared mutable state
  |     |- note: convert 'global' to a 'let' constant to make 'Sendable' shared state immutable
  |     |- note: annotate 'global' with '@MainActor' if property should only be accessed from the main actor
  |     `- note: disable concurrency-safety checks if accesses are protected by an external synchronization mechanism
2 | 
```

Highlight:

`note: annotate 'global' with '@MainActor' if property should only be accessed from the main actor`

input 2:

```swift
var global = 42

func mutate() {
    global += 1
}
```

diagnostics 2:

```
test.swift:4:5: error: main actor-isolated var 'global' can not be mutated from a non-isolated context
1 | var global = 42
  |     `- note: mutation of this var is only permitted within the actor
2 | 
3 | func mutate() {
  |      `- note: add '@MainActor' to make global function 'mutate()' part of global actor 'MainActor'
4 |     global += 1
  |     `- error: main actor-isolated var 'global' can not be mutated from a non-isolated context
5 | }
6 | 
```

highlight: `note: add '@MainActor' to make global function 'mutate()' part of global actor 'MainActor'`

### Proposed solution

I think the second note seems like its more general-purpose. But, I think including "annotate" does help.

`note: annotate 'global' with '@MainActor' if property should only be accessed from the main actor`

could become:

`note: add '@MainActor' annotation to make property 'global' part of global actor 'MainActor'`

**Comment by rofle100lvl** [comment]
Hi! I'm interested in tackling this issue.

**Comment by AnthonyLatsis** [comment]
@rofle100lvl Go ahead!
