### ISSUE TITLE
Unexpected optional type in error message about non-Sendable AsyncStream element

### ISSUE THREAD

**Issue by Androp0v** [swiftlang/swift#74844]
### Description

Error message when iterating over an `AsyncStream` with a non-Sendable type that is on a different isolation context shows the element type as optional even when the `AsyncStream` element doesn't have optional type.

More so, iterating over an `AsyncStream` with an **optional** non-Sendable type that is on a different isolation context shows the element with **two** question marks (for example: `NonSendableFoo??`).

### Reproduction

Error message already mentions an (unexpectedly) optional element type for `AsyncStream` with non-optional element:
```swift
final class NonSendableFoo {
    var foo: String = ""
    init() {}
}

struct FooContainer {
    let stream: AsyncStream<NonSendableFoo> = AsyncStream { continuation in
        continuation.yield(NonSendableFoo())
    }
}

actor Actor {
    
    let container = FooContainer()
    
    init() {}
    
    func isolatedFoo() async {
        // ERROR (line below): Non-sendable type 'NonSendableFoo?' returned by implicitly
        // asynchronous call to nonisolated function cannot cross actor boundary
        for await number in container.stream {
            // ...
        }
    }
}
```
And for optional `AsyncStream` elements (changing `AsyncStream<NonSendableFoo>` for `AsyncStream<NonSendableFoo?>` in the code above) the compiler shows the following error:
> Non-sendable type 'NonSendableFoo??' returned by implicitly asynchronous call to nonisolated function cannot cross actor boundary
Where the `NonSendableFoo??` (notice the double question marks) is even more unexpected.

### Expected behavior

Error message should not refer to the type as optional in the first case (non-optional element type, see above) and should contain a single "?" in the second case (optional element type, see above).

### Environment

Swift 6.0 (I'm using Xcode 16)

**Comment by hborla** [comment]
I can't reproduce this error with a Swift 6 compiler.

> iterating over an AsyncStream with a non-Sendable type that is on a different isolation context shows

Iterating over an AsyncStream does not cross an isolation boundary. This behavior for iteration to stay on the actor was introduced with https://github.com/swiftlang/swift-evolution/blob/main/proposals/0421-generalize-async-sequence.md

**Comment by Androp0v** [comment]
Can't reproduce it anymore with Xcode 16 beta 4, so I'm closing the issue

**Comment by hborla** [comment]
Thank you for verifying!
