### ISSUE TITLE
Difference between generic and concrete sending behavior

### ISSUE THREAD

**Issue by mattmassicotte** [swiftlang/swift#74845]
### Description

It's entirely possible that I am just misunderstanding how region-based isolation works and/or `sending`. But, it really *feels* like these two situations are the same. When I use a concrete type, things are ok. But when I use a generic, the system thinks it has found a race.

I'm not certain this is the most minimal example, but I was having trouble reducing it further.

```
test.swift:23:9: error: sending 'records' risks causing data races
21 | 
22 |         // error: sending 'records' risks causing data races
23 |         return records
   |         |- error: sending 'records' risks causing data races
   |         `- note: task-isolated 'records' cannot be a 'sending' result. task-isolated uses may race with caller uses
24 |     }
25 | 
```

### Reproduction

```swift
protocol MyProtocol {
    init()
}

class NonSendable {
}

class MyClass {
    func makeValue<Record: MyProtocol>() -> sending Record {
        Record()
    }

    func consumeValue<Record: MyProtocol>() -> sending [Record] {
        var records = [Record]()

        // right here, I *think* the system believes that record has
        // a dependency on self, despite it being marked sending
        let record: Record = makeValue()
        
        records.append(record)

        // error: sending 'records' risks causing data races
        return records
    }

    func makeConcrete() -> sending NonSendable {
        NonSendable()
    }

    func consumeConcrete() -> sending [NonSendable] {
        var records = [NonSendable]()

        let record = makeConcrete()

        records.append(record)

        // No error!
        return records
    }
}
```

### Expected behavior

I would expect this code to be error-free

### Environment

Apple Swift version 6.0-dev (LLVM 5b37bd4c1c578e9, Swift 54898ce105c7185)
Target: arm64-apple-macosx14.0

**Comment by fritzt0** [comment]
+1

**Comment by gottesmm** [comment]
@mattmassicotte this is a perfect sized example. Thank you for creating it. The important thing is that the example is small enough for me to manipulate and test it in a standalone file.

**Comment by mattmassicotte** [comment]
@gottesmm that makes sense. And I'm happy to. Thanks so much for looking!

**Comment by gottesmm** [comment]
@mattmassicotte I just looked at this:

This was fixed in between git log tags/swift-DEVELOPMENT-SNAPSHOT-2024-08-21-a..tags/swift-DEVELOPMENT-SNAPSHOT-2024-08-26-a

This is 00519669af6b714699ae3a1d97b1d14216b1c838

**Comment by mattmassicotte** [comment]
Fantastic!!

**Comment by mattmassicotte** [comment]
Verified with 6.1 snapshot. Thank you so much!
