### ISSUE TITLE
Swift-Testing Swift 6 Strict Concurrency Legit Build Failure?

### ISSUE THREAD

**Issue by vanvoorden** [swiftlang/swift#74882]
### Description

https://forums.swift.org/t/swift-testing-swift-6-strict-concurrency-legit-build-failure/72824/1

Hi! I'm experimenting with `swift-testing` and Swift 6 strict concurrency checking. I'm seeing some not-super-clear build failure. Maybe this is something that should work and might be fixed later this year… or maybe it's a legit failure and I should rethink how this test is built.

Here is a test that builds (and passes) from Swift 6 strict concurrency:

```swift
func doSomething(_: Int) async throws {
  
}

@Suite actor Tests {
  let count = 0
}

extension Tests {
  @Test func exampleBuilds() async throws {
    let count = 0
    try await doSomething(count)
    await #expect(throws: Never.self) {
      try await doSomething(count)
    }
    try await doSomething(self.count)
  }
}
```

Here is a test that fails to build from Swift 6 strict concurrency:

```swift
extension Tests {
  @Test func exampleFails() async throws {
    await #expect(throws: Never.self) {
      try await doSomething(self.count)
    }
  }
}
```

Here is the failure:

```text
24 |     await #expect(throws: Never.self) {
25 |       try await doSomething(self.count)
26 |     }
   +--- macro expansion #expect ----------------------------------------
   |1 | Testing.__checkClosureCall(throws: Never.self, performing: {
   |  | `- error: sending 'self'-isolated value of type '() async throws -> ()' with later accesses to nonisolated context risks causing data races
   |2 |       try await doSomething(self.count)
   |3 |     }, expression: .__fromSyntaxNode("try await doSomething(self.count)"), comments: [], isRequired: false, sourceLocation: Testing.SourceLocation()).__expected()
   +--------------------------------------------------------------------
27 |   }
28 | }
```

Any ideas about what else I can do about that? I don't see this error when building from Swift 5 mode. Is this error legit? Should I rethink how I'm building this test? Any ideas about that would be great. Thanks!

### Environment

swift-driver version: 1.110 Apple Swift version 6.0 (swiftlang-6.0.0.4.52 clang-1600.0.21.1.3)
Target: arm64-apple-macosx14.0

**Comment by vanvoorden** [comment]
cc @grynspan

**Comment by vanvoorden** [comment]
```swift
extension Tests {
  @Test func exampleWorkaround() async throws {
    do {
      try await doSomething(self.count)
    } catch {
      #expect(false)
    }
  }
}
```

I'm unblocked with this workaround.

**Comment by gottesmm** [comment]
@vanvoorden I believe this is already fixed... can you try this with the latest snapshot or baring that, provide a full swift package that I can build that reproduces this?

**Comment by vanvoorden** [comment]
@gottesmm This looks fixed in `Xcode_16_beta_4`. Thanks!

**Comment by grynspan** [comment]
Thanks for confirming!

**Comment by vanvoorden** [comment]
@grynspan Ahh… actually the original test case was fixed… but this version still looks broken in `Xcode_16_beta_4`.

```swift
func doSomething(_: Int) async throws {
  
}

@Suite actor Tests {
  let count = 0
}

extension Tests {
  @Test func exampleFails() async throws {
    await #expect {
      try await doSomething(self.count)
    } throws: { _ in
      return true
    }
  }
}
```

With a similar error:

```text
   +--- macro expansion #expect ----------------------------------------
   |1 | Testing.__checkClosureCall(performing: {
   |  | `- error: sending 'self'-isolated value of type '() async throws -> ()' with later accesses to nonisolated context risks causing data races
   |2 |       try await doSomething(self.count)
   |3 |     }, throws: { _ in
   +--------------------------------------------------------------------
```

**Comment by grynspan** [comment]
D'oh!

**Comment by vanvoorden** [comment]
@grynspan FWIW I am still unblocked on this new test case with a similar workaround from before.

**Comment by vanvoorden** [comment]
> provide a full swift package that I can build that reproduces this

https://github.com/vanvoorden/2024-08-05/

@gottesmm Here is the new repro. Thanks!

**Comment by vanvoorden** [comment]
@gottesmm This looks fixed for me from `Xcode_16.1_beta_3`. Thanks!

**Comment by grynspan** [comment]
Yay!
