### ISSUE TITLE
Generic argument list incorrectly allowed on typealias metatype value

### ISSUE THREAD

**Issue by AnthonyLatsis** [swiftlang/swift#74895]
### Reproduction

```swift
typealias A = Int
func foo(_ meta: A.Type) {
  // No error.
  let _ = meta<Bool>.self
}
```

### Expected behavior

An error stating that parameter `meta` cannot be specialized. Or better yet, an error stating that only references to generic type and macro declarations may be specialized.

### Environment

Swift version 6.0-dev (LLVM c7c87ee42989d4b, Swift 8493312b06605f1)
Target: x86_64-apple-darwin23.5.0

**Comment by xedin** [comment]
Looks like this has been fixed by @gregomni's PR recently, main branch compiler produces `error: cannot specialize non-generic type 'A' (aka 'Int')`. Please use a recent main branch snapshot from swift.org to verify!
