### ISSUE TITLE
[stdlib] Add comparison overloads to {U}Int128 types

### ISSUE THREAD

**Issue by benrimmington** [swiftlang/swift#74931]
Do the {U}Int128 types also need the following overloads? (See #70041 and #70043).

https://github.com/swiftlang/swift/blob/d66f233839132fcf85fb74d1e4ad61e9863fca9c/stdlib/public/core/IntegerTypes.swift.gyb#L1718-L1757

**Comment by benrimmington** [comment]
@swiftlang/standard-librarians

**Comment by xwu** [comment]
I have just encountered this as well: it does appear to still be necessary, as in the current betas we get an error here because the RHS is defaulted to `Int`:

```swift
func f(_ x: UInt128) -> Bool {
  x <= 9_999_999_999_999_999_999_999_999_999_999_999
  // Error: integer literal '9999999999999999999999999999999999' overflows when stored into 'Int'
}
```
