### ISSUE TITLE
[Swift-Testing] Option rejected on Linux CLI

### ISSUE THREAD

**Issue by MahdiBM** [swiftlang/swift#75037]
### Description

`swift test` rejects usage of `--enable-swift-testing` on Linux but not on macOS.

### Reproduction

```bash
~ swift test --enable-swift-testing
error: Unknown option '--enable-swift-testing'
Usage: swift test <options> <subcommand>
  See 'test -help' for more information.
```

### Expected behavior

I expect an unified behavior on macOS and Linux.

### Environment

macOS: Xcode 16 beta 2 toolchain. macOS 15 beta 2.
linux: nightly jammy swift 6 Docker image.

### Additional information

EDIT:

This issue + the other issue I linked below were confusing and almost made me think swift-testing had yet to be supported on Linux.

**Comment by MahdiBM** [comment]
Related: https://github.com/swiftlang/swift-package-manager/issues/7763
cc @grynspan

**Comment by grynspan** [comment]
We haven't added Swift Testing to the open source toolchain yet. This is not a Swift issue.

**Comment by MahdiBM** [comment]
It does work though, it just doesn't accept the option.
The tests do run, and successfully.

**Comment by grynspan** [comment]
I understand the nature of the problem you're seeing. It's not a Swift issue. We have experimental package-based support for Swift Testing in SwiftPM. We need to add Swift Testing to the toolchain and then refactor the SwiftPM support to use that copy instead of looking for a package dependency.

**Comment by MahdiBM** [comment]
Ah hmm ok. Fine by me, I'm not trying to force issues on you, just trying to understand what's going on, and reporting the unexpected behaviors I see 😅

**Comment by grynspan** [comment]
I appreciate your enthusiasm. 🙂
