### ISSUE TITLE
Missing MainActor warning when MainActor is implied through inheritance

### ISSUE THREAD

**Issue by moreindirection** [swiftlang/swift#75063]
### Description

The included code is a reduction of an actual issue I had in a production app while migrating to Swift 6. I've made the example as small as possible.

If you compile the code as is (with Xcode 16 beta 2), it generates the following error on line 5:

`Main actor-isolated property 'delegate' can not be mutated from a non-isolated context`

This makes sense to me.

However, if I remove the explicit `@MainActor` annotation on line 5, the code then compiles successfully. But `UIView` (the parent class of `ThumbnailView`) is itself `@MainActor`, so `ThumbnailView` should automatically be `@MainActor`, and I should get this warning without having to annotate the class manually.

### Reproduction

```swift
import UIKit

protocol ThumbnailViewDelegate: AnyObject {}

@MainActor
class ThumbnailView: UIView {
  var delegate: ThumbnailViewDelegate? = nil
}

class Grid: UIViewController {
  private var thumbnailView: ThumbnailView!
  
  init() {
    self.thumbnailView = ThumbnailView(frame: .zero)
    
    super.init(nibName: nil, bundle: nil)
  }
  
  required init?(coder: NSCoder) {
    fatalError("init(coder:) has not been implemented")
  }
  
  deinit {
    self.thumbnailView?.delegate = nil
  }
}
```

### Expected behavior

I should get the same warning whether or not I add the redundant `@MainActor` annotation to `ThumbnailView` (because it inherits from a `MainActor`

### Environment

```
swift-driver version: 1.110 Apple Swift version 6.0 (swiftlang-6.0.0.4.52 clang-1600.0.21.1.3)
Target: arm64-apple-macosx14.0
```

### Additional information

Also reported as FB14237108

**Comment by hborla** [comment]
@moreindirection are you compiling with `-strict-concurrency=complete`? This is expected behavior under minimal concurrency checking, because the `@MainActor` annotation on `UIView` is considered to be `@preconcurrency`.

**Comment by hborla** [comment]
I see the reported behavior only with minimal checking. When you turn on complete checking or Swift 6 mode, the diagnostic comes back. This is expected behavior because `UIView` is imported from ObjC, so it is considered `@preconcurrency`. Diagnostics from `@preconcurrency @MainActor` annotations are suppressed in minimal checking.

**Comment by moreindirection** [comment]
Thanks @hborla. I was using minimal checking only. I thought turning on Swift 6 mode and the "Upcoming Features" settings was basically turning on complete checking, but now I see that it doesn't.

I can confirm that the problem goes away under complete checking - thanks for responding!
