### ISSUE TITLE
RBI: Pattern that the region based isolation checker does not understand how to check

### ISSUE THREAD

**Issue by Jnosh** [swiftlang/swift#75098]
### Description

The following snippet produces a warning in Swift 5 mode with strict concurrency checking enabled, or an error in Swift 6 mode respectively.

Passing the isolation from `run` to `_run` explicitly does not produce an error.

### Reproduction

```swift
// swiftc -swift-version 6 rbi.swift
struct Foo {
    func run<Success>(
        isolation: isolated (any Actor)? = #isolation,
        body: () async -> sending Success
    ) async -> Success {
        // error: pattern that the region based isolation checker does not understand how to check. Please file a bug
        await _run(body: body)

        // no error
        // await _run(isolation: isolation, body: body)
    }

    func _run<Success>(
        isolation _: isolated (any Actor)? = #isolation,
        body: () async -> sending Success
    ) async -> Success {
        await body()
    }
}
```

### Expected behavior

The snippet should compile successfully.

### Environment

Xcode 16 beta 3 toolchain

swift-driver version: 1.111.2 Apple Swift version 6.0 (swiftlang-6.0.0.5.15 clang-1600.0.22.6)
Target: arm64-apple-macosx15.0

**Comment by craigwrong** [comment]
I think it may have to do with default parameters. I'm having the same issue here, which I worked around by overloading the function to achieve the same default parameter behavior.

https://github.com/swift-bitcoin/swift-bitcoin/blob/931e39a848b047ad190e2549f1d0c65f14ab04c9/src/bitcoin/service/BitcoinService.swift#L252

**Comment by Manuel-Kehl** [comment]
I also encountered this earlier and while trying to narrow down the problem also came to the same conclusion as @craigwrong: it seems to be related to default parameters in general and is not limited to `#isolated` (although that's where I also first encountered it).

I wanted to share my minimal repro example and a few additional observations I made, in case this may be useful?

### Observations

1. Specifying a default parameter in the definition is **not** the problem (see example below). The error only occurs when called without a specific value, i.e. when the default value is *actually used*
2. Related to 1.: When overloading the function, as suggested by @craigwrong, it does not matter if the original function has a default value or not (as long as the overloaded variant is present)
3. For some reason, I am getting a different error? (see below)
> Sending 'self'-isolated value of type 'String' with later accesses to actor-isolated context risks causing data races; this is an error in the Swift 6 language mode

### Minimal Code Example
```Swift
actor TestActor {
    func reproBug() async {
        let actorWithDefaultValue = ActorWithDefaultValue()
        let actorWithOverload = ActorWithOverload()
        
        // Error: Sending 'self'-isolated value of type 'String' with later accesses to actor-isolated context risks causing data races; this is an error in the Swift 6 language mode
        await actorWithDefaultValue.test()
        
        // No error: As long as a value is specified for the parameter it works fine
        await actorWithDefaultValue.test(with: "Not using default value")
        
        // No error: The overload variant also works fine
        await actorWithOverload.test()
    }
}

actor ActorWithDefaultValue {
    func test(with someParameter: String = "Default Value") {
        print("Hello \(someParameter)")
    }
}

actor ActorWithOverload {
    func test() {
        test(with: "Default Value")
    }
    
    // Note: it does not matter if a default value is defined here or not as long as the overloaded variant of test() is present
    func test(with someParameter: String) {
        print("Hello \(someParameter)")
    }
}
```

**Comment by Jnosh** [comment]
My original snippet appears to be fixed in the Xcode 16.0 beta 4 toolchain.

@craigwrong @Manuel-Kehl
Could you check if your cases are fixed as well?

**Comment by Manuel-Kehl** [comment]
Interesting, for me the issue still reproduces after updating to Xcode 16.0 beta 4.
So maybe it *is* a different issue after all? Should I file a separate issue in that case?

**Comment by gottesmm** [comment]
@Manuel-Kehl your example works in the 07/27 swift snapshot.

**Comment by Manuel-Kehl** [comment]
Great, glad to hear! Thanks for confirming, @gottesmm 🙏

**Comment by Jnosh** [comment]
Great to hear, in that case I'll close this issue.
