### ISSUE TITLE
Improve performance of creating a C++ `std::string` from a contiguous UTF-8 `Swift.String`

### ISSUE THREAD

**Issue by kylesluder** [swiftlang/swift#75110]
### Motivation

Currently [the implementation of `std::string(swift::String)`](https://github.com/swiftlang/swift/blob/dfc5321ca60ec09a03fd71630d98304d84bdc37a/stdlib/public/Cxx/std/String.swift#L22
) naïvely loops over the Swift string’s UTF-8 characters and pushes them back onto the C++ string one-by-one:

```
public init(_ string: String) {
  self.init()
  let utf8 = string.utf8
  self.reserve(utf8.count)
  for char in utf8 {
    self.push_back(value_type(bitPattern: char))
  }
}
```

 It would be much more efficient to use the `std::string(const CharT*, size_type count)` constructor when the Swift string’s `isContiguousUTF8` property is true.

### Proposed solution

Something like:

```
public init(_ string: String) {
  let utf8 = string.utf8
  if string.isContiguousUTF8 {
    self = utf8.withContiguousStorageIfAvailable { buf in
      Self(buf.baseAddress.unsafelyUnwrapped, buf.count)
    }
  } else {
    self.init()
    self.reserve(utf8.count)
    for char in utf8 {
      self.push_back(value_type(bitPattern: char))
    }
  }
}
```

**Comment by egorzhdan** [comment]
@kylesluder thanks, this is a totally correct observation. Would you mind creating a pull request with the more optimal implementation of this initializer that you've shared?

**Comment by kylesluder** [comment]
Do I need to (re)build the compiler to test out the PR?

**Comment by egorzhdan** [comment]
Yes, you would need to build the compiler locally for this change. Here's a guide on how to do that: https://github.com/swiftlang/swift/blob/main/docs/HowToGuides/GettingStarted.md#building-the-project-for-the-first-time
Feel free to ask if you run into issues!

**Comment by egorzhdan** [comment]
Fixed in https://github.com/swiftlang/swift/pull/75608.
