### ISSUE TITLE
pattern that the region based isolation checker does not understand how to check. Please file a bug

### ISSUE THREAD

**Issue by jasonbobier** [swiftlang/swift#75128]
### Description

I'm getting these issues regarding an actor property on a main actor isolated class.

bluetoothCentralManager is the actor property in the following code

### Reproduction

```swift

// This line causes the issue:

return await bluetoothCentralManager.retrieveConnectedPeripherals(with: [Bluetooth.HumanInterfaceDeviceService.self]).compactMap { device(for: $0) }
```

```swift

// But if I add this line above it, it works fine:

let bluetoothCentralManager = bluetoothCentralManager

return await bluetoothCentralManager.retrieveConnectedPeripherals(with: [Bluetooth.HumanInterfaceDeviceService.self]).compactMap { device(for: $0) }
```

### Expected behavior

Region isolation should understand this.

### Environment

Xcode Version 16.0 beta 3 (16A5202i)

**Comment by gottesmm** [comment]
@cyrilzakka I believe that this may already be fixed. Can you try with the newest 6.0 snapshot? Otherwise, can you please provide a full test case that shows the behavior?

**Comment by jasonbobier** [comment]
This seems to be fixed in Xcode 16 b5 for me. @cyrilzakka how about you?

**Comment by gottesmm** [comment]
I am going to close this. I believe it is fixed. If an additional issue occurs, please file another issue.
