### ISSUE TITLE
Invalid gradient / pullback for optional let

### ISSUE THREAD

**Issue by asl** [swiftlang/swift#75167]
### Description

The following code prints `(0.0, 1.0)`. The reason is that the following SIL is provided to autodiff:
```llvm
// sum(x:y:)
sil hidden [ossa] @$s3opt3sum1x1ySdSgAE_AEtF : $@convention(thin) (Optional<Double>, Optional<Double>) -> Optional<Double> {
// %0 "x"                                         // users: %7, %4, %2
// %1 "y"                                         // users: %12, %11, %8, %3
bb0(%0 : $Optional<Double>, %1 : $Optional<Double>):
  debug_value %0 : $Optional<Double>, let, name "x", argno 1 // id: %2
  debug_value %1 : $Optional<Double>, let, name "y", argno 2 // id: %3
  switch_enum %0 : $Optional<Double>, case #Optional.some!enumelt: bb1, case #Optional.none!enumelt: bb2 // id: %4

// %5                                             // user: %6
bb1(%5 : $Double):                                // Preds: bb0
  debug_value %5 : $Double, let, name "x"         // id: %6
  br bb5(%0 : $Optional<Double>)                  // id: %7

bb2:                                              // Preds: bb0
  switch_enum %1 : $Optional<Double>, case #Optional.some!enumelt: bb3, case #Optional.none!enumelt: bb4 // id: %8

// %9                                             // user: %10
bb3(%9 : $Double):                                // Preds: bb2
  debug_value %9 : $Double, let, name "y"         // id: %10
  br bb5(%1 : $Optional<Double>)                  // id: %11

bb4:                                              // Preds: bb2
  br bb5(%1 : $Optional<Double>)                  // id: %12

// %13                                            // user: %14
bb5(%13 : $Optional<Double>):                     // Preds: bb4 bb3 bb1
  return %13 : $Optional<Double>                  // id: %14
} // end sil function '$s3opt3sum1x1ySdSgAE_AEtF'
```

So, the code was turned into
```swift
@differentiable(reverse)
func sum(x: Double?, y: Double?) -> Double? {
  if let x { return x }
  if let y { return y }

  return y
}
```

This even produces the same result, but certainly yields different gradients / pullbacks.

The main question – what to do with this? :)

### Reproduction

```swift
import _Differentiation

@differentiable(reverse)
func sum(x: Double?, y: Double?) -> Double? {
  if let x { return x }
  if let y { return y }

  return nil
}

let vwpb = valueWithPullback(at: nil, nil, of: sum)
let pullbackResult = vwpb.pullback(.init(1.0))
print(pullbackResult)
```

### Expected behavior

`(0.0, 0.0)` is printed

### Environment

Swift version 6.0-dev (LLVM 76ba61e88550d3b, Swift 9db059cfa080600)
Target: arm64-apple-macosx13.0

**Comment by asl** [comment]
Tagging @rxwei 

The transformation is quite correct, it always gives correct result. But gradients / pullback value is wrong :)

**Comment by asl** [comment]
Tagging @JaapWijnen

**Comment by asl** [comment]
The code after silgen is correct:
```llvm
// sum(x:y:)
sil hidden [ossa] @$s3opt3sum1x1ySdSgAE_AEtF : $@convention(thin) (Optional<Double>, Optional<Double>) -> Optional<Double> {
// %0 "x"                                         // users: %4, %2
// %1 "y"                                         // users: %9, %3
bb0(%0 : $Optional<Double>, %1 : $Optional<Double>):
  debug_value %0 : $Optional<Double>, let, name "x", argno 1 // id: %2
  debug_value %1 : $Optional<Double>, let, name "y", argno 2 // id: %3
  switch_enum %0 : $Optional<Double>, case #Optional.some!enumelt: bb1, case #Optional.none!enumelt: bb2 // id: %4

// %5                                             // users: %7, %6
bb1(%5 : $Double):                                // Preds: bb0
  debug_value %5 : $Double, let, name "x"         // id: %6
  %7 = enum $Optional<Double>, #Optional.some!enumelt, %5 : $Double // user: %8
  br bb5(%7 : $Optional<Double>)                  // id: %8

bb2:                                              // Preds: bb0
  switch_enum %1 : $Optional<Double>, case #Optional.some!enumelt: bb3, case #Optional.none!enumelt: bb4 // id: %9

// %10                                            // users: %12, %11
bb3(%10 : $Double):                               // Preds: bb2
  debug_value %10 : $Double, let, name "y"        // id: %11
  %12 = enum $Optional<Double>, #Optional.some!enumelt, %10 : $Double // user: %13
  br bb5(%12 : $Optional<Double>)                 // id: %13

bb4:                                              // Preds: bb2
  %14 = enum $Optional<Double>, #Optional.none!enumelt // user: %15
  br bb5(%14 : $Optional<Double>)                 // id: %15

// %16                                            // user: %17
bb5(%16 : $Optional<Double>):                     // Preds: bb4 bb3 bb1
  return %16 : $Optional<Double>                  // id: %17
} // end sil function '$s3opt3sum1x1ySdSgAE_AEtF'
```

The change is further performed by SILGenCleanup pass that in turns canonicalizes SIL via InstSimplifier. The transformation itself is done by `InstSimplifier::visitEnumInst(EnumInst *EI)`:
```
  // Simplify enum insts to the value from a switch_enum when possible, e.g.
  // for
  //   switch_enum %0 : $Bool, case #Bool.true!enumelt: bb1
  // bb1:
  //   %1 = enum $Bool, #Bool.true!enumelt
  //
  // we'll return %0
```

**Comment by asl** [comment]
@rxwei I guess this is something that should be documented as "known pitfalls"? Here `nil` is a bit special. Looks like the workaround is to return definite output when possible (e.g. returning 0.0 helps). Not sure if this would be possible in all cases though...

**Comment by asl** [comment]
Ok. Thinking of this a bit more: mathematically the function is having discontinuity at `nil` and it is not possible to extend the function by continuity into `nil`. As a result, the derivatives at `nil` do not exist, so any gradient / pullback value is correct.

We might think how it would be better to diagnose such situations, though I do not see a generic way for doing this.

**Comment by JaapWijnen** [comment]
Hmm I feel this is quite problematic. But also raises a question. If that's the case, why is the `Optional.TangentVector` an optional in that case? We could just limit it to `Wrapped.TangentVector` since it's invalid in the .none case anyway. Similar to what we discussed recently around the `Result` type in a way the nil path is just an error path with a `Void` error type. 

I do think this is problematic though. And definitely unexpected for users of optionals wrt autodiff. Shouldn't it behave similarly to control flow? 

It would be weird to expect the following to behave similarly right? technically you could simplify that by doing the same transformation as you mentioned.
```swift
@differentiable(reverse)
func sum(x: Double, y: Double) -> Double? {
  if x != 0 { return x }
  if y != 0 { return y }
  return 0
}

let vwpb = valueWithPullback(at: 0, 0, of: sum)
let pullbackResult = vwpb.pullback(.init(1.0))
print(pullbackResult) // (0.0, 0.0) whereas the optional version returned (0.0, 1.0)
```

**Comment by asl** [comment]
> I do think this is problematic though. And definitely unexpected for users of optionals wrt autodiff. Shouldn't it behave similarly to control flow?

Derivatives at the points of discontinuity is always "fun". As essentially we are providing some arbitrary value as it happens. In this particular case both `(0.0, 0.0)`, `(1.0, 0)` and `(0.0, 1.0)` pullback results are correct as these are all the same programs:

```swift
@differentiable(reverse)
func sum(x: Double?, y: Double?) -> Double? {
  if let x { return x }
  if let y { return y }

  return y
}
```

```swift
@differentiable(reverse)
func sum(x: Double?, y: Double?) -> Double? {
  if let x { return x }
  if let y { return y }

  return x
}
```

```swift
@differentiable(reverse)
func sum(x: Double?, y: Double?) -> Double? {
  if let x { return x }
  if let y { return y }

  return nil
}
```

The situation is quite similar to control flow, think of e.g. something like this:
```swift
@differentiable(reverse)
func sum(x: Double) -> Double {
   if (x == 0) {
     return x;
   }
   ...
}
```

Here we can certainly return `0` at the discontinuity point as well, but this changes the "gradient" value.

One way of thinking is to consider for a moment a set of convex functions. Those are not differentiable in general, however, we can definite a subdifferential here. However, we cannot return the whole set of subderivatives, so we only return a single representative. It could be different depending on the optimizations / transformations and even code around though.

**Comment by JaapWijnen** [comment]
I understand that. The difference is though that right now we're forced into using (or knowing) about this compiler behaviour. Whereas if that transformation wasn't applied we ourselves as developers could chose which side of the limit of the derivative we'd like to use instead of being forced to use the one that the compiler forces on us due to a code transformation that isn't clear from the source written by the developer. 
We could "pick" our vjp by writing the code as one of those functions you demonstrated that have the exact same outcome for all values but do signal a slightly different vjp definition for the discontinuity. I'm just hoping we can make the behaviour at the discontinuity either predictable or let the user be able to make a choice in it's behaviour.

**Comment by asl** [comment]
> The difference is though that right now we're forced into using (or knowing) about this compiler behaviour.

It is not about the compiler behavior. Consider three different functions:
```swift
@differentiable(reverse)
func sum(x: Double) -> Double {
   if (x < 0) {
      return -x;
   }
   return x;
}
```

```swift
@differentiable(reverse)
func sum(x: Double) -> Double {
   if (x <= 0) {
      return -x;
   }
   return x;
}
```

```swift
@differentiable(reverse)
func sum(x: Double) -> Double {
   if (x < 0) {
      return -x;
   }
   if (x > 0) {
     return x;
   }
   return 0;
}
```

They all are identical – they produce the same values on all domain where they are defined. One can freely transformed into any other. However, the computed derivative at zero will be different in all cases.  +1 in the first case, -1 in the second case and zero in the third. Is this a bug? Not quite. The derivative is not defined at zero. Even in the broader term (tangent) – any value in the range -1 ... +1 would yield a proper tangent.

The situation is same as with other undefined behavior – the result is undefined. So it could be arbitrary (here we have a bonus that the result does make sense) and it could change with optimizations enabled, etc.

So yes, when asking for undefined value, one should be prepared that the value could be arbitrary.
