### ISSUE TITLE
Pattern that the region based isolation checker does not understand how to check

### ISSUE THREAD

**Issue by akbashev** [swiftlang/swift#75238]
### Description

Get `Pattern that the region based isolation checker does not understand how to check. Please file a bug` when two actors involved and the second actor defined as `var`.

### Reproduction

```swift
struct Client: Sendable {
  let fetch: @Sendable () async throws -> [String]
}

actor Waiter {
    
  func process(
    by id: String,
    work: @Sendable () async throws -> [String]
  ) async throws -> [String] {
    return []
  }
  
  init() {}
}

actor Service {
  
  let client: Client
  
  private var waiter = Waiter() // happens, cause it's var here.
  
  private func fetch(
    key: String
  ) async throws -> [String] {
    try await self.waiter.process(by: key) { // Pattern that the region based isolation checker does not understand how to check. Please file a bug
      try await self.client.fetch()
    }
  }
  
  init(client: Client) {
    self.client = client
  }
}
```

### Expected behavior

Region based isolation check works properly

### Environment

Xcode 16 Beta 3 (16A5202i)

**Comment by akbashev** [comment]
Ok, was playing now a bit and found out this is happening cause `waiter` in Service is `var`. If you change it to `let`—it compiles successfully.

**Comment by akbashev** [comment]
Based on other issues about regions isolation will tag @gottesmm sorry if not 🤔

**Comment by gottesmm** [comment]
@akbashev this doesn't reproduce with the latest nightly snapshot. I believe it is already fixed.

**Comment by gottesmm** [comment]
That is the specific snapshot I tested: swift-DEVELOPMENT-SNAPSHOT-2024-07-27-a.

**Comment by akbashev** [comment]
@gottesmm just checked on 2024-07-29-a, can confirm, don't see an error anymore
