### ISSUE TITLE
Region based checker does not understand call across global actors

### ISSUE THREAD

**Issue by andykent** [swiftlang/swift#75279]
### Description

I am seeing 

> Pattern that the region based isolation checker does not understand how to check. Please file a bug; this is an error in the Swift 6 language mode

In a project where we have a custom global actor. I have managed to narrow it down to a slightly contrived but reproducible example.

### Reproduction

```swift
// swiftc -swift-version 6 foo.swift

@globalActor actor FooActor: GlobalActor {
    static let shared = FooActor()
}

@FooActor
class Foo {
  func doFoo() {}
}

@MainActor
class Bar {
  @FooActor
  var foo = Foo()
  
  @FooActor
  func reachFoo() {
    foo.doFoo()
  }
}

```

Note that either of the following 2 changes cause the code to compile successfully:

1. change `foo.doFoo()` to `let f = foo; f.doFoo()`
2. change `var foo = Foo()` to `let foo = Foo()`

### Expected behavior

I expected the code to compile, or if I am mis-understanding and the code is not safe then for a more helpful error message. 😄 

### Environment

```
swift-driver version: 1.111.2 Apple Swift version 6.0 (swiftlang-6.0.0.5.15 clang-1600.0.22.6)
Target: arm64-apple-macosx15.0
```

**Comment by andykent** [comment]
Looking through other Issues here I wonder if this could be a duplicate of: https://github.com/swiftlang/swift/issues/75238

**Comment by gottesmm** [comment]
@andykent this doesn't reproduce with the latest nightly snapshot. I believe it is already fixed.

**Comment by gottesmm** [comment]
That is: swift-DEVELOPMENT-SNAPSHOT-2024-07-27-a
