### ISSUE TITLE
String type is still unavailable in Embedded Swift despite documentation stating otherwise

### ISSUE THREAD

**Issue by SebastianOsinski** [swiftlang/swift#75281]
### Description

According to [Embedded Swift Status document](https://github.com/swiftlang/swift/blob/main/docs/EmbeddedSwift/EmbeddedSwiftStatus.md) Strings should be supported by Embedded Swift, however trying to compile code which uses `String` type throws error: `'String' is unavailable: unavailable in embedded Swift`. 

### Reproduction

Create `test.swift` file with contents:
```swift
let test: String = "Hello World"
print(test)
```

Try to compile:

```sh
swiftc test.swift -enable-experimental-feature Embedded -wmo
```

Output:
```
test.swift:1:11: error: 'String' is unavailable: unavailable in embedded Swift
1 | let test: String = "Hello World"
  |           `- error: 'String' is unavailable: unavailable in embedded Swift
2 | print(test)
3 |

Swift.String:2:15: note: 'String' has been explicitly marked unavailable here
1 | @available(*, unavailable, message: "unavailable in embedded Swift")
2 | public struct String : Hashable {
  |               `- note: 'String' has been explicitly marked unavailable here
3 |     public var utf8CString: ContiguousArray<CChar> { get }
4 |     public init()

test.swift:1:20: error: 'String' is unavailable: unavailable in embedded Swift
1 | let test: String = "Hello World"
  |                    `- error: 'String' is unavailable: unavailable in embedded Swift
2 | print(test)
3 |

Swift.String:2:15: note: 'String' has been explicitly marked unavailable here
1 | @available(*, unavailable, message: "unavailable in embedded Swift")
2 | public struct String : Hashable {
  |               `- note: 'String' has been explicitly marked unavailable here
3 |     public var utf8CString: ContiguousArray<CChar> { get }
4 |     public init()
```

### Expected behavior

Code should successfully compile and running `./test` should print `Helo World` to stdout

### Environment

Tested on macOS Sonoma 14.5 with:
```
Apple Swift version 6.0-dev (LLVM a41678ee19c803d, Swift ce381e7b159dfac)
Target: arm64-apple-macosx14.0
```

and Ubuntu 22.04.4 LTS with:
```
Swift version 6.0-dev (LLVM a41678ee19c803d, Swift 97ef6739c064b9a)
Target: x86_64-unknown-linux-gnu
```

with the same results

**Comment by benrimmington** [comment]
#70446 and #73585 haven't been cherry-picked to the `release/6.0` branch.

Are you using a recent `main` branch toolchain from the [install](https://www.swift.org/install/) page?

**Comment by SebastianOsinski** [comment]
You're right. For some reason I assumed that `release/6.0` would contain those changes. I tried with `main` branch toolchain and it indeed works. Thank you for pointing it out!

**Comment by alkozin** [comment]
Thank you for adding Strings support. 
If somebody will try to find docs like me ☺️:
https://docs.swift.org/embedded/documentation/embedded/strings
