### ISSUE TITLE
[cxx-interop] Specializations of `std::function<...>` don't support automatic/implicit type conversion (`String` <> `std::string`)

### ISSUE THREAD

**Issue by mrousavy** [swiftlang/swift#75403]
### Description

When specializing functions (e.g. `std::function<void(std::string)>`), automatic type conversions (e.g. Swift's `String` to C++ `std::string`) don't work anymore (unless they are string literals)

### Reproduction

C++:

```cpp
#include <string>
#include <functional>

using SomeFunc = std::function<void(std::string)>;
```

Swift:

```swift
func dummy(callback: SomeFunc) {
  callback("Hello!") // ✅ works!
  let str = "Hello!"
  callback(str) // ❌ Cannot convert value of type 'String' to expected argument type 'std.__1.basic_string<CChar, char_traits<CChar>, allocator<CChar>>'
}
```

### Expected behavior

I expect the above code to work, and the Swift String `"Hello"` to be automatically converted to the C++ `std::string`.

However **this fails to build** with the following error:

```diff
- Cannot convert value of type 'String' to expected argument type 'std.__1.basic_string<CChar, char_traits<CChar>, allocator<CChar>>'
```

### Environment

swift-driver version: 1.90.11.1 Apple Swift version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4)
Target: arm64-apple-macosx14.0

### Additional information

This doesn't only apply to `std::string` - no implicit type conversions work anymore. Int32 <-> Int don't work either.

**Comment by ludwwwig** [comment]
Hi again @mrousavy,

How are you calling ```dummy```? I copied your code and I seem to have no problem to get it running.

**Comment by mrousavy** [comment]
Hi again @ludwwwig 😄 

I'm sorry I copy & pasted this wrong here. String literals work fine, but variables don't implicitly convert:

```swift
func dummy(callback: SomeFunc) {
  callback("Hello!") // ✅ works!
  let str = "Hello!"
  callback(str) // ❌ Cannot convert value of type 'String' to expected argument type 'std.__1.basic_string<CChar, char_traits<CChar>, allocator<CChar>>'
}
```

Calling `dummy` doesn't matter I think as it's a compiler error - but I call it from the same C++ file that defines the function.

**Comment by mrousavy** [comment]
Actually I am not sure if this should even work, this also doesn't work for `std.string` value initialization - maybe I confused this?

**Comment by ludwwwig** [comment]
> Actually I am not sure if this should even work, this also doesn't work for `std.string` value initialization - maybe I confused this?
> 
> ```swift
> let string1 = "hello!"
> let string2: std.string = string1 // ❌ Cannot convert value of type 'String' to expected argument type 'std....'
> ```
> 
> I think if it is intentional that this doesn't work implicitly then we can close the issue - sorry for the confusion!

You first need to convert the Swift ```String``` to an ```std.string```. 

```swift
func dummy(callback: SomeFunc) {
    callback("Hello!") // ✅
    let str = "Hello!"
    callback(std.string(str)) // ✅
    let str2: std.string = str // ❌
}
```

However, this will not work for all Swift strings, see below:

https://github.com/swiftlang/swift/issues/69870#issuecomment-2078195515

**Comment by mrousavy** [comment]
Yup the `std.string` conversion works fine, thanks.

I'll figure out how to properly bridge those things - I'm building an API that allows user to write modules that are exposed to JavaScript using a C++ bridge, and I don't want my users to use `std.string`, I want them to use `String` (same for `Int` vs `Int32`, and so on)

**Comment by ludwwwig** [comment]
@mrousavy How about you send an ```swift::String``` to your function and then convert it to an ```std::string``` inside of your C++ function. That should work, right?

See here for more info: https://www.swift.org/documentation/cxx-interop/#using-swift-string-in-c

**Comment by mrousavy** [comment]
I tried to do that, but unfortunately I got all kinds of build errors (class X not found, class Y not found, func dummy not found, etc) due to the cyclic includes again - Swift depends on the C++ header, and the C++ header depends on the Swift file - all in the same Pod.

It gets even trickier when I tried to include the Pod from outside (e.g. the app or another Pod), because then the `"X-Swift.h"` header couldn't be found either.

**Comment by ludwwwig** [comment]
Hmm, allow me a few hours. I'll have a look when I get off work.

**Comment by mrousavy** [comment]
DM me on Twitter if you want to get paid for your efforts :)

I also have the same issue with array buffers - I want to expose `Data` to a C++ class somehow but I can't manage to do that without creating copies.

**Comment by ludwwwig** [comment]
@mrousavy Hi Marc, I'm back. I needed the weekend to think about this. 

I had a look at Stackoverflow and it seems like you're not the first to discover this cyclic dependency issue. At the moment, I don't see any solution, but a workaround might be to use C instead.

As you can see [here](https://developer.apple.com/documentation/swift/string/utf8view), it is possible to pass a Swift ```String``` to a C function without any conversion. The same goes for [other types](https://developer.apple.com/documentation/swift/using-imported-c-functions-in-swift). You could then create a C API to call your C++ code from your C code. 

I tried with a small project and it seems to be running just fine.

### main.swift

```swift
import Foundation

print("Hello, World!")

func dummy(callback: string_to_void) {
    let str = "Hello!"
    callback(str);
}

dummy(callback: print_string)

func dummy2(callback: int_to_void) {
    let number : Int32 = 12;
    callback(number);
}

dummy2(callback: print_int)
```

### library.h
```c
void print_string(const char *input);
typedef typeof(print_string) string_to_void;

void print_int(const int input);
typedef typeof(print_int) int_to_void;
```

### library.c
```c
#include "library.h"
#include <stdio.h>

void print_string(const char *input)
{
    printf("%s\n", input);
}

void print_int(const int input)
{
    printf("%d\n", input);
}
```

Now, unfortunately, you have to use ```Int32``` instead of ```Int```, however both ```String``` and ```Float``` do not need to be converted. 

I hope this helps! 😁

**Comment by mrousavy** [comment]
This is pretty cool! I think I'll try to go that route thx!

**Comment by ludwwwig** [comment]
> DM me on Twitter if you want to get paid for your efforts :)
> 
> I also have the same issue with array buffers - I want to expose `Data` to a C++ class somehow but I can't manage to do that without creating copies.

I just realised that I hadn't mentioned the most obvious solution... Most of the ```Foundation``` types, such as ```Data``` are bridged to ```NSData``` ([link](https://developer.apple.com/documentation/foundation/nsdata)). If you are comfortable writing Objective-C++ code then that would probably be the cleanest solution. You can then call your C++ library from the Obj-C++ side.

**Comment by mrousavy** [comment]
Ah yes, true - didn't think about that either!

I was trying to avoid Objective-C for my bridge in general to avoid ObjC objects and ObjC methods/selectors in hopes of my architecture becoming simpler, and potentially also more efficient/faster.

So far I achieved good speedups with using bare `Int`s instead of `NSNumber`, and std.string is also much faster than `NSString`. I haven't benchmarked Swift objects yet (those are wrapped in additional C++ objects since I cannot inherit from a C++ instance), but they are definitely not simpler in their structure, lol.
