### ISSUE TITLE
[6.0] error: 'retroactive' attribute does not apply; 'Equatable' is declared in this module

### ISSUE THREAD

**Issue by MahdiBM** [swiftlang/swift#75412]
### Description

```
#if compiler(>=6.0)
extension DiscordHTTPResponse: @retroactive Equatable {
                        `- error: 'retroactive' attribute does not apply; 'Equatable' is declared in this module
public static func == (lhs: DiscordHTTPResponse, rhs: DiscordHTTPResponse) -> Bool {
```

> 'Equatable' is declared in this module

I certainly haven't re-declared a protocol named `Equatable`. Is it meant to mention the type's name instead?

* The [GitHub Actions run](https://github.com/DiscordBM/DiscordBM/actions/runs/9806851100/job/27786983144).
* The logs of a failed run, [uploaded here](https://github.com/user-attachments/files/16345355/15_main-tests._.linux-unit.swiftlang_swiftnightly-6.0-jammy.txt) for convenience.

### Reproduction

Run the tests of `7865b015f9135d8e1799a0f406be0174e4b04d85` revision of [DiscordBM](https://github.com/DiscordBM/DiscordBM/).

### Expected behavior

Better error, or no error?

### Environment

`swiftlang/swift:nightly-6.0-jammy@sha256:488383d2e634098bed1742e32f80d96164cbe07b3be34fd8c7b724658f838569`

### Additional information

DiscordBM does declare a [Package@swift-6.0.swift](https://github.com/DiscordBM/DiscordBM/blob/main/Package%40swift-6.0.swift) file since from the beginning it was built with strict-concurrency turned on and it's compatible with Swift 6 (not counting this error).

**Comment by mattmassicotte** [comment]
I am also encountering this issue, and can reproduce it like this:

Package.swift
```swift
// swift-tools-version: 6.0

import PackageDescription

let package = Package(
	name: "RetroactiveBug",
	products: [
		.library(name: "RetroactiveBug", targets: ["NonSendableClient"]),
	],
	targets: [
		.target(name: "NonSendable"),
		.target(name: "NonSendableClient", dependencies: ["NonSendable"]),
	]
)
```

NonSendable/NonSendableStruct.swift
```swift
public struct NonSendableStruct {
	public init() {}
}
```

NonSendableClient/NonSendableClient.swift
```swift
import NonSendable

// ERROR: 'retroactive' attribute does not apply; 'Sendable' is declared in this module
extension NonSendableStruct: @retroactive @unchecked Sendable {
}
```

**Comment by AnthonyLatsis** [comment]
cc @harlanhaskins

**Comment by harlanhaskins** [comment]
Is this possibly fallout from the `package` relaxation?

**Comment by tshortli** [comment]
This is fixed by https://github.com/swiftlang/swift/pull/76189.

**Comment by tshortli** [comment]
> Is this possibly fallout from the package relaxation?

Yes, the diagnostics didn't quite keep up with the relaxation and therefore come out a bit non-sensical.
