### ISSUE TITLE
KeyPaths with Sendable Root to non-isolated but Sendable properties are not Sendable

### ISSUE THREAD

**Issue by Supereg** [swiftlang/swift#75420]
### Description

If you create a KeyPath with a Sendable root type, that points to a property that is non-isolated but returns a Sendable type, the KeyPath is not considered sendable. Below is a minimal code example that triggers the warning/error.

Am I missing something why this would be considered non-sendable?

### Reproduction

```swift
final class TestClass: Sendable {
    var test: Bool {
        false
    }
}

let keyPath: KeyPath<TestClass, Bool> & Sendable = \.test // warning: Type 'KeyPath<TestClass, Bool>' does not conform to the 'Sendable' protocol; this is an error in the Swift 6 language mode
```

### Expected behavior

I would expect passing around a KeyPath that points to a Sendable Root type with a property of Sendable type to be Sendable. Especially in the above example it is not obvious why this wouldn't be the case.

### Environment

swift-driver version: 1.112.3 Apple Swift version 6.0 (swiftlang-6.0.0.6.8 clang-1600.0.23.1)
Target: arm64-apple-macosx14.0

Xcode 16 Beta 4 (16A5211f)

complete concurrency checking enabled

**Comment by Supereg** [comment]
cc: @xedin You seem to be mentioned with most KeyPath/Sendable related changes.

**Comment by xedin** [comment]
I think this behaves correctly. I can reproduce this only if I use `-strict-concurrency=complete` with swift language version 5. If you want do that you'd need to enable upcoming feature explicitly by using `-Xfrontend -enable-upcoming-feature -Xfrontend InferSendableFromCaptures`, this feature is enabled by default in swift language version 6.

**Comment by Supereg** [comment]
My bad. I didn't know this was still behind a feature flag. Thank you 🎉

**Comment by xedin** [comment]
No worries!
