### ISSUE TITLE
(6.0) cannot `consume self` from a closure inside a `consuming` method

### ISSUE THREAD

**Issue by tayloraswift** [swiftlang/swift#75487]
### Description

this snippet causes an error on Swift 6, even though it compiled on Swift 5.10

### Reproduction

```swift
extension AsyncSequence where Element:Sendable
{
    consuming
    func iterate() async
    {
        await withTaskGroup(of: Void.self)
        {
            _ in
            var _:AsyncIterator = self.makeAsyncIterator()
        }
    }
}
```

```text
error: missing reinitialization of inout parameter 'self' after consume
 2 | {
 3 |     consuming
 4 |     func iterate() async
   |          `- error: missing reinitialization of inout parameter 'self' after consume
 5 |     {
 6 |         await withTaskGroup(of: Void.self)
 7 |         {
 8 |             _ in
 9 |             var _:AsyncIterator = self.makeAsyncIterator()
   |                                        `- note: consumed here
10 |         }
11 |     }
```

### Expected behavior

it really should compile, unless there was something inherently wrong with the original code.

### Environment

$ /swift/swift-6.0-DEVELOPMENT-SNAPSHOT-2024-07-24-a-amazonlinux2/usr/bin/swift --version
Swift version 6.0-dev (LLVM 723ba90c22d3da1, Swift ae7e24dc658e067)
Target: x86_64-unknown-linux-gnu

**Comment by kavon** [comment]
There actually was something wrong with this code prior to Swift 6. AsyncSequence defines makeAsyncIterator as:
```
__consuming func makeAsyncIterator() -> AsyncIterator
```

So it is actually trying to copy the explicitly-ownership-annotated `self` when its invoked. This code is suppose to be correct only if you add an explicit copy like this:

```
(copy self).makeAsyncIterator()
```

**Comment by kavon** [comment]
This change came as part of this miscompile fix:

https://github.com/swiftlang/swift/pull/73395

We have [a test covering](https://github.com/swiftlang/swift/pull/73395/files#r1704667151) this sort of case, where the `consuming self` parameter is captured by a closure and consumed within that closure.
