### ISSUE TITLE
source compatibility project penny-bot fails with a compiler error

### ISSUE THREAD

**Issue by eeckstein** [swiftlang/swift#75500]
### Description

```
/build/swift-source-compat-suite/project_cache/penny-bot/Sources/Penny/Services/AutoPingsService/DefaultPingsService.swift:20:44: error: reference to generic type 'Expression' requires arguments in <...>
 18 |     var _cachedItems: S3AutoPingItems?
 19 |     /// `[ExpressionHash: Expression]`
 20 |     var _cachedExpressionsHashTable: [Int: Expression]?
    |                                            `- error: reference to generic type 'Expression' requires arguments in <...>
 21 |     var resetItemsTask: Task<(), Never>?
 22 | 
```

### Reproduction

builds:
https://ci.swift.org/job/swift-6.0-source-compat-suite-debug-ubuntu-2004/121/
https://ci.swift.org/job/swift-6.0-source-compat-suite-ubuntu-2004/121/
https://ci.swift.org/job/swift-source-compat-suite-debug-ubuntu-2004/499/
https://ci.swift.org/job/swift-source-compat-suite-ubuntu-2004/599/

log: https://ci.swift.org/job/swift-6.0-source-compat-suite-debug-ubuntu-2004/121/artifact/build/swift-source-compat-suite/FAIL_penny-bot_5.10_BuildSwiftPackage.log

### Expected behavior

should build fine

### Environment

CI

### Additional information

Note: in recent builds this might be hidden by another problem:
```
/Users/ec2-user/jenkins/workspace/swift-main-source-compat-suite/swift-source-compat-suite/project_cache/penny-bot/.build/checkouts/DiscordBM/Sources/DiscordModels/Types/Permission.swift:3:1: error: cannot specialize non-generic type '() -> ()'
 1 | 
 2 | /// https://discord.com/developers/docs/topics/permissions#permissions-bitwise-permission-flags
 3 | @UnstableEnum<UInt>
   | `- error: cannot specialize non-generic type '() -> ()'
 4 | public enum Permission: Sendable, Codable {
 5 |     case createInstantInvite // 0
```

which should be fixed with the revert https://github.com/swiftlang/swift/pull/75489

**Comment by AnthonyLatsis** [comment]
Ditto https://github.com/swiftlang/swift/issues/75499#issuecomment-2252438935. [Link to file](https://github.com/vapor/penny-bot/blob/eb29963b6ef5a956087a31a1825bfbbdc0f73edf/Sources/Penny/Services/AutoPingsService/DefaultPingsService.swift#L22).
