### ISSUE TITLE
False positive warning about closure isolation but only when not using trailing closure syntax

### ISSUE THREAD

**Issue by groue** [swiftlang/swift#75521]
### Description

The compiler changes its diagnostic depending on whether a closure is explicitly provided, or with the trailing closure syntax.

### Reproduction

```swift
struct SUT {
    func run(completion: sending @escaping () -> Void) { }
}

@MainActor
func test_run() {
    let sut = SUT()

    // No warning
    sut.run { }

    // Warning: Main actor-isolated value of type '() -> ()' passed
    // as a strongly transferred parameter; later accesses could race.
    sut.run(completion: { })
}
```

This is very confusing.

### Expected behavior

No warning in both cases.

### Environment

% swiftc -version
swift-driver version: 1.112.3 Apple Swift version 6.0 (swiftlang-6.0.0.6.8 clang-1600.0.23.1)
Target: arm64-apple-macosx14.0

**Comment by gottesmm** [comment]
This was fixed in swift-DEVELOPMENT-SNAPSHOT-2024-08-28-a..swift-DEVELOPMENT-SNAPSHOT-2024-08-29-a. With ToT, we also do not reproduce.
