### ISSUE TITLE
Cannot use protocol with primary associated type requirement in protocol composition

### ISSUE THREAD

**Issue by ahoppen** [swiftlang/swift#75602]
The following doesn’t compile. I would expect it to. Otherwise I don’t see any way of specifying any kind of `String` collection that’s sendable.

```swift
let x: any Collection<String> & Sendable = [] // error: Non-protocol, non-class type 'Collection<String>' cannot be used within a protocol-constrained type
```

rdar://132374933

**Comment by slavapestov** [comment]
Yeah, this is a known limitation.

**Comment by slavapestov** [comment]
Dupe of https://github.com/swiftlang/swift/issues/63877
