### ISSUE TITLE
Swift 6 regression overriding initializers due to Swift Concurrency

### ISSUE THREAD

**Issue by NachoSoto** [swiftlang/swift#75732]
### Description

It used to be possible to override a class like `UIView`/`NSView` to provide a new designated initializer that delegated to the parent's designated initializer. It no longer is with `swiftlang-6.0.0.7.6`.

### Reproduction

```swift
class A: NSView {
  // Call to main actor-isolated initializer 'init(frame:)' in a synchronous nonisolated context
  init() {
    super.init(frame: .zero)
  }

  // It's 2024 and I still have to write this lol but anyway that's not what this bug is about
  required init?(coder: NSCoder) {
    fatalError("init(coder:) has not been implemented")
  }
}
```

### Expected behavior

This compiles like it's done for many versions of Swift.

### Actual behavior:
> Call to main actor-isolated initializer 'init(frame:)' in a synchronous nonisolated context

No other variant works either:
```swift
class A: NSView {
  // Main actor-isolated initializer 'init()' has different actor isolation from nonisolated overridden declaration
  @MainActor
  init() {
    super.init(frame: .zero)
  }

  required init?(coder: NSCoder) {
    fatalError("init(coder:) has not been implemented")
  }
}
```

This one is particularly puzzling. Why would `init()` on a `@MainActor` type be nonisolated? This seems like a serious regression too:
```swift
@MainActor
class A: NSView {
  init() {
    // Call to main actor-isolated initializer 'init(frame:)' in a synchronous nonisolated context
    super.init(frame: .zero)
  }

  required init?(coder: NSCoder) {
    fatalError("init(coder:) has not been implemented")
  }
}
```

### Environment

```
swift-driver version: 1.113 Apple Swift version 6.0 (swiftlang-6.0.0.7.6 clang-1600.0.24.1)
Target: arm64-apple-macosx14.0
```

### Additional information

It's also completely impossible to figure out what actor isolation the class / constructors have. CMD+Click on Xcode to show the interface does not show any actor isolation information:

<img width="557" alt="Screenshot 2024-08-06 at 14 53 28" src="https://github.com/user-attachments/assets/fa9babc8-dd7c-4503-bd86-ef8b33ae8a95">

**Comment by NachoSoto** [comment]
cc @hborla

**Comment by hborla** [comment]
This is the same problem as https://github.com/swiftlang/swift/issues/75733. It was caused by https://github.com/swiftlang/swift/pull/74238 which addressed the data-race safety hole described in https://github.com/swiftlang/swift/issues/72238.

I believe the problem here is that the `init()` that's being overridden isn't from the `@MainActor`-isolated superclass, it's from `NSObject`, which is `nonisolated`.

**Comment by hborla** [comment]
I think the right tradeoff between usability and safety here is to rely on dynamic isolation checking in the override thunk. Direct calls will behave as they normally will for a `@MainActor`-isolated init, and calls through the vtable will assert a`MainActor` precondition before making the call.

**Comment by noahlit** [comment]
Try this:
```

class A: NSView {
  init(isolation: MainActor = #isolation) {
    super.init(frame: .zero)
  }

  required init?(coder: NSCoder) {
    fatalError("init(coder:) has not been implemented")
  }
}

```

**Comment by NachoSoto** [comment]
@hborla just filed #75815 with a different version of this issue that makes it impossible to test `@MainActor` types.

**Comment by Jon889** [comment]
Is the fix PR just special casing NSObject so other root objective-c classes will have the same issue?

**Comment by hborla** [comment]
>Is the fix PR just special casing NSObject so other root objective-c classes will have the same issue?

Yes. See https://forums.swift.org/t/swift-6-from-xcode-16b5-overridden-function-and-isolation/73862/3 for more information.
