### ISSUE TITLE
Type inference for closure with typed throws function doesn't seem to work

### ISSUE THREAD

**Issue by mattmassicotte** [swiftlang/swift#76165]
### Description

I came across this code, and it certainly *looks* like it should compile. But, it actually cannot unless you explicitly include the type information for the closure. This leads to me to believe that type inference cannot figure this out because typed throws are involved.

### Reproduction

```swift
enum AppError: Error {
    case failure
}

func f(_ i: Int) throws(AppError) -> Int { return 0 }

extension Result where Failure == AppError {
    static func wrap(_ f: () throws(AppError) -> Success) -> Self {
        do throws(AppError) {
            return .success(try f())
        } catch {
            return .failure(error)
        }
    }
}

// do not work
let r1 = Result<Int, AppError> { try f(0) }
let r2 = Result<Int, AppError>.wrap { try f(0) }

// work
let r3 = Result<Int, AppError> { () throws(AppError) -> Int in try f(0) }
let r4 = Result<Int, AppError>.wrap { () throws(AppError) -> Int in try f(0) }
```

### Expected behavior

I would expect the first two variations to also compile.

### Environment

Apple Swift version 6.0-dev (LLVM c3efe9282719c35, Swift e26305bb70cce53)
Target: arm64-apple-macosx14.0

**Comment by finestructure** [comment]
Possibly related? https://github.com/swiftlang/swift/issues/76169

**Comment by hborla** [comment]
Thrown error type inference for closures is part of the `FullTypedThrows` upcoming feature that was subsetted out of [SE-0413](https://github.com/swiftlang/swift-evolution/blob/main/proposals/0413-typed-throws.md).

**Comment by mattmassicotte** [comment]
Ah ha! Thank you!
