### ISSUE TITLE
UIDevice is still on MainActor, causing issues on non-mainactor codebase

### ISSUE THREAD

**Issue by yasali** [swiftlang/swift#76478]
### Description

We are migrating the App to `strict concurrency` in order to start using `swift 6`. We are able to solve most of the warnings but the `UIDevice` is causing some issues. In our Networking module we are using `URLSession`, `URLRequest` etc and they are all `Sendable`. Also we use `Bundle` to get bundle information which is also `Sendable`. But `UIDevice` is on the `MainActor` and we need the `UIDevice` in order to retrieve `model` and `systemVersion` to pass in user agent.
We feel that `UIDevice` should be `Sendable` and not on MainActor, please look into it.

### Reproduction

```
    let currentModel = UIDevice.current.model
    let osVersion = UIDevice.current.systemVersion
```
![Screenshot 2024-09-15 at 21 31 17](https://github.com/user-attachments/assets/67357a62-457e-4ff7-9bfb-d821d3f73c5b)

### Expected behavior

```
    let currentModel = UIDevice.current.model
    let osVersion = UIDevice.current.systemVersion
```
Should not be on MainActor.

### Environment

5.10

### Additional information

There is ongoing topic I opened on swift forums where suggestion is that UIDevice should be on MainActor.
https://forums.swift.org/t/main-actor-isolated-property-error-in-non-isolated-context/74616/6

**Comment by AnthonyLatsis** [comment]
@yasali Please report this to Apple’s feedback assistant too — UIKit is closed source and outside the scope of the Swift project.

**Comment by yasali** [comment]
Thanks @AnthonyLatsis it is now reported to Apple's feedback assistant as well.

**Comment by AnthonyLatsis** [comment]
Thanks. I am going to close this, but please feel free to leave the FB number as a reference for maintainers.

**Comment by yasali** [comment]
FB number for above `FB15144636`
