### ISSUE TITLE
Result builder misplacement error message should mention subscripts

### ISSUE THREAD

**Issue by AnthonyLatsis** [swiftlang/swift#76475]
### Description

This is the error message template:

https://github.com/swiftlang/swift/blob/09b54318780309300865ce96dc48e186dd2a6019/include/swift/AST/DiagnosticsSema.def#L7264-L7266

### Reproduction

```swift
@resultBuilder struct Builder {
  static func buildBlock() {}
}

@Builder struct Test {}
```

### Expected behavior

The enumeration in this message should be made exhaustive by including subscripts.

### Environment

Swift version 6.1-dev (614e8aa79a84486)

### Additional information

Make sure to also update any verifications (occurrences) of this error in tests.

**Comment by saehejkang** [comment]
Solution above ^
