### ISSUE TITLE
Response files created by "swift-frontend.exe" on Windows include "/LIB" which causes linking failures

### ISSUE THREAD

**Issue by sienkewits** [swiftlang/swift#76548]
### Description

On Windows, when compiling/linking many files, the swiftc compiler ends up putting the command line parameters for the link step into a temporary response file. The first linker parameter in the response file is "/LIB", which (according to the linker) is supposed to be the first parameter of the linker command. However, because "/LIB" is in the response file, it is not interpreted properly by the linker as the first parameter, and the link step fails. If "/LIB" is taken out of the response file, and put onto the linker command line, then the link step works as expected.

### Reproduction

A reproducible testcase can be found at:
https://github.com/sienkewits/swiftc-link-issue

### Expected behavior

The provided testcase should compile and link successfully.

### Environment

This issue has been reproduced with swiftc version 5.8.1 and 5.10.1 on Windows.

**Comment by cgweeder** [comment]
Greetings -

I have seen this incorrect behavior as well, on Windows.  Hopefully someone from the Swift team can take a look at this ticket and triage.

Regards,
C

**Comment by compnerd** [comment]
What version of swift are you using? This shouldn't be happening on the development snapshots at the very least if it didn't already make it into 6.0.

**Comment by sienkewits** [comment]
Hi there! 
I originally tried with swift 5.8.1 and 5.10.1 on Windows.  This morning, I ran with swift 6.0 and it looks like this issue is resolved.  Could you point me to the commit (or commits) that fix it?
Thank you!

**Comment by compnerd** [comment]
I don't remember the commit, but it was in swift-driver and mirrored into the C++ driver. I had to special case the `/LIB` option in the response file generation.
