### ISSUE TITLE
Linux/Swift 6: executable target fails to run when processing/copying `resources` (worked in `v5.[9/10]`)

### ISSUE THREAD

**Issue by KevinVitale** [swiftlang/swift#76659]
### Description

I have a cross-platform (macOS & Linux) game project.

For resources I need at runtime (images, fonts, sfx), I specify them via the `Package.targets[\.executableTarget.resources]` array (usually, I specify `.copy(_ path:)`.

I just upgraded to `v6.0.0`, and any inclusion of valid _Resources_ causes the build to fail. See **Stack Dump**

Previously building on Linux (specifically, _Ubuntu 22.04_) this has worked (`v5.9.0`, and `v5.10.0`). It worked—and continues to work—on _macOS_ (specifically, `.v11`, and now `.v13`).

I can remove all `Resource` references from the `.executableTarget` (in `Package.swift`), and the Linux target compiles and runs; however, unhandled runtime exceptions when loading said resources are thrown (expected for my own code, at the moment).

### Reproduction

This would work previously. Now it causes the Linux build to fail (`NSCocoaErrorDomain Code=512`):
```swift
      .executableTarget(
        name: "NextExample",
        dependencies: ["SDL2"],
        path: "Examples/NextExample",
        resources: [
          .copy("Resources/terrain_center.png")
        ]
      )
```

I attempted specifying a single _Resources_ folder (as I do in some other targets). This doesn't work either:
```swift
      .executableTarget(
        name: "NextExample",
        dependencies: ["SDL2"],
        path: "Examples/NextExample",
        resources: [
          .copy("Resources")
        ]
      )
```

### Stack dump

```text
warning: you may be able to install sdl2_ttf using your system-packager:
    apt-get install libsdl2-ttf-dev
warning: you may be able to install sdl2_image using your system-packager:
    apt-get install libsdl2-mixer-dev
warning: you may be able to install sdl2_image using your system-packager:
    apt-get install libsdl2-image-dev
warning: prohibited flag(s): -D_REENTRANT, -Wl,-rpath,/usr/local/lib, -Wl,--enable-new-dtags
warning: you may be able to install sdl2_gfx using your system-packager:
    apt-get install libsdl2_gfx-dev
warning: you may be able to install sdl2_ttf using your system-packager:
    apt-get install libsdl2_ttf-dev
warning: you may be able to install sdl2_mixer using your system-packager:
    apt-get install libsdl2_mixer-dev
warning: you may be able to install sdl2_image using your system-packager:
    apt-get install libsdl2_image-dev
Building for debugging...
Write auxiliary file /media/psf/SwiftSDL/.build/aarch64-unknown-linux-gnu/debug/swift-version-78C14A5BD304591E.txt
Write auxiliary file /media/psf/SwiftSDL/.build/aarch64-unknown-linux-gnu/debug/NextExample.build/sources
Copying /media/psf/SwiftSDL/Examples/NextExample/Resources
error: Error Domain=NSCocoaErrorDomain Code=512 "(null)"
```

### Expected behavior

Compiling on Linux should properly copy the resources, as was the behavior in prior releases.

### Environment

Swift version 6.0 (swift-6.0-RELEASE)
Target: aarch64-unknown-linux-gnu

**Comment by tbkka** [comment]
If this is a build-time failure, then I suspect this is really a SwiftPM issue, not really a problem with the Swift language and/or runtime.

**Comment by KevinVitale** [comment]
@tbkka Understood. Thank you.

I've opened an issue on the SPM repo: https://github.com/swiftlang/swift-package-manager/issues/7996
