### ISSUE TITLE
Return from initializer without initializing all stored properties error for optional type

### ISSUE THREAD

**Issue by soumyamahunt** [swiftlang/swift#76791]
### Description

If type of property is noted as `Type?` or `Type!`, and the property is declared as `var` compiler allows such properties to be skipped for initialization. But if type of property is noted as `Optional<Type>`, then skipping such properties during initialization creates error:

> Return from initializer without initializing all stored properties

### Reproduction

- Create a new swift project/package.
- Add the following code and see error
  ```swift
  struct SomeOptionalType {
      var val: Optional<String>
  
      init() {}
  }
  ```
- Replacing `Optional<String>` with `String?` or `String!` resolves error.

### Expected behavior

Code should behave same as scenario with `Type?` or `Type!` declaration.

### Environment

swift-driver version: 1.115 Apple Swift version 6.0 (swiftlang-6.0.0.9.10 clang-1600.0.26.2)
Target: x86_64-apple-macosx14.0

**Comment by AnthonyLatsis** [comment]
NB: https://github.com/swiftlang/swift/pull/26160/commits/25e4ca9a602cedd455df673563fa38900459658c#diff-5a9439f8a77b136c97b430596bfc4263de54fbf7c0616656bbfa75ff2d10d145L2454-L2475

**Comment by hamishknight** [comment]
Duplicate of #53322
