### ISSUE TITLE
Undefined symbols for architecture arm64 (protocol witness table)

### ISSUE THREAD

**Issue by tayloraswift** [swiftlang/swift#77171]
### Description

compiling this test project: https://github.com/tayloraswift/swift-mongodb-test 

produces an error resembling the following:

```
Undefined symbols for architecture arm64:
  "protocol witness table for (extension in MongoQL):Mongo.Mongo.Create<A> : (extension in MongoCommands):Mongo.Mongo.Command in MongoQL", referenced from:

ld: symbol(s) not found for architecture arm64
```

this was also discussed on slack here: https://app.slack.com/client/T5FT3K01G/C5FAE2LL9

this seems to be closely related to setting a platform minimum of `.macOS(.v15)` in Package.swift, and never seems to happen on Linux.

### Reproduction

```
git clone https://github.com/tayloraswift/swift-mongodb-test 
cd swift-mongodb-test 
swift build
```

### Expected behavior

it should compile successfully

### Environment

Swift 6.0 that comes with the latest Xcode on macOS 15.0.1 Sequoia

**Comment by weissi** [comment]
probably related to https://github.com/swiftlang/swift/pull/76384

**Comment by DougGregor** [comment]
This was fixed by https://github.com/swiftlang/swift/pull/76384
