### ISSUE TITLE
Synthesized `Equatable` conformance for enum with associated values uses String comparison

### ISSUE THREAD

**Issue by colemancda** [swiftlang/swift#77681]
### Description

While developing a Bluetooth LE peripheral for Embedded Swift on the Pico W, I came across unexpected compiler behavior. The compiler was emitting calls to `_stringCompareFastUTF8()`, which in turn relies on the Unicode data which I did not want to link due to code size. Adding an [explicit `Equatable` implementation](https://github.com/apple/swift-embedded-examples/pull/74/commits/e0e8857c2f662fb6a2f3fea5cc82d0d49f9486a9) for my enum solved this issue.

### Reproduction

```swift
@frozen
public enum BluetoothUUID: Hashable, Sendable {
    
    case bit16(UInt16)
    case bit32(UInt32)
    case bit128(UInt128)
}
```
Links against `_stringCompareFastUTF8` and `_swift_stdlib_getNormData`

Adding an explicit Equatable implementation removes the dependency on String.

```
extension BluetoothUUID: Equatable {
    
    public static func == (lhs: BluetoothUUID, rhs: BluetoothUUID) -> Bool {
        switch (lhs, rhs) {
        case let (.bit16(lhsValue), .bit16(rhsValue)):
            return lhsValue == rhsValue
        case let (.bit32(lhsValue), .bit32(rhsValue)):
            return lhsValue == rhsValue
        case let (.bit128(lhsValue), .bit128(rhsValue)):
            return lhsValue == rhsValue
        default:
            return false
        }
    }
}
```

### Expected behavior

`Equatable` conformance for enums with associated values should not rely on any `String` or Unicode functions.

### Environment

```
Apple Swift version 6.1-dev (LLVM 9d655fdc6103926, Swift 0d16cbf5d5ef6f9)
Target: arm64-apple-macosx14.0
```

Targeting the Pico W with the following flags:
```
-target armv6m-none-none-eabi -Xcc -mfloat-abi=soft -Xcc -fshort-enums
-Xfrontend -function-sections -enable-experimental-feature Embedded -wmo -parse-as-library
```

**Comment by colemancda** [comment]
@rauhul My `BluetoothUUID` type declares a `RawRepresentable` conformance with `String` as the `RawValue`. Is there some protocol extension to `RawRepresentable` in the StdLib that is triggering the error?

e.g. 
```swift
extension RawRepresentable where Self: Equatable, RawValue: Equatable {
static func ==(lhs: Self, rhs: Self) -> {
lhs.rawValue == rhs.rawValue
}
}
```

**Comment by colemancda** [comment]
@rauhul I think this is the culprit https://github.com/swiftlang/swift/blob/753cbcd2af4cf61a92f7b89e42e40bb3762fd22c/stdlib/public/core/CompilerProtocols.swift#L154

**Comment by rauhul** [comment]
@colemancda Hmm the stdlib is doing the correct thing here. You what's the goal of using RawRepresentable here? It seems like you actually want `CustomStringConvertible` + `LosslessStringConvertible`

**Comment by colemancda** [comment]
I want it used as `RawRepresentable` for `Codable` usage. The fact that's it's a simple value stored on the stack is an implementation detail, the use is almost always gonna be creating UUIDs from strings.

**Comment by colemancda** [comment]
@rauhul 
In my case, `description` != `rawValue`, in addition to using the StdLib `Coddle` conformance to `RawRepresentable` where the rawValue is a String.

```
// MARK: - CustomStringConvertible

extension BluetoothUUID: CustomStringConvertible {
    
    public var description: String {
        #if !os(WASI) && !hasFeature(Embedded)
        if let name = self.name {
            return "\(rawValue) (\(name))"
        } else {
            return rawValue
        }
        #else
        return rawValue
        #endif
    }
}
```

If the UUID is in the Bluetooth SIG database I want to print its associated name, e.g. "Primary Service".
