### ISSUE TITLE
Unexpected "error: expression is 'async' but is not marked with 'await'"

### ISSUE THREAD

**Issue by hjyamauchi** [swiftlang/swift#77751]
### Description

We see unexpected compiler behavior differences between `5.10`, `6.0` and `main (6.1-dev)` regarding the necessity of `await` in front of a non-async call (`lock.unlock()` below)

This is what I locally see
```
### 5.10.1 (The latest 5.10 release)
# Without await: error: expression is 'async' but is not marked with 'await'
# With await   : success

### 6.0.2 (The latest 6.0 release)
# Without await: success
# With await   : warning: no 'async' operations occur within 'await' expression

### Main dev snapshot (6.1-dev)
# Without await: error: expression is 'async' but is not marked with 'await'
# With await   : success
```

But what's expected is that the `await` isn't necessary at version `6.0` or later, including `main` but in reality `main` is behaving like `5.10` instead. Is this a bug?

### Reproduction

An example

Command
```
swiftc await.swift
```
Source file (`await.swift`)
```swift
public actor AsyncLock {
    public func lock() async {
    }
    public func unlock() {
    }
}
public struct Result {}
public struct Client: Sendable {
     public var foo: @Sendable @MainActor () async -> Result
}
@MainActor
final class ClientImpl {
    @MainActor
    @Sendable
    func foo() async -> Result {
        .init()
    }
}
extension Client {
    @MainActor
    public static var liveValue: Client = {
        var lock: AsyncLock = .init()
        return .init(foo: { [lock] () in
            await lock.lock()
            let result = await ClientImpl().foo()
            //await lock.unlock()  // with await <------------- Alternate between these two lines
            lock.unlock()          // without await
            return result
        })
    }()
}
```

### Expected behavior

The source file without `await` compiles successfully with `main` (`6.1-dev`). That is, the `await` isn't necessary at version `6.0` or later including `main`. 

### Environment

The Mac and Windows 5.10.1, 6.0.2, main builds from swift.org

**Comment by hjyamauchi** [comment]
CC @ahoppen @DougGregor @compnerd

**Comment by hjyamauchi** [comment]
@ahoppen @DougGregor Do you have a time to take a quick look at this issue?

**Comment by DougGregor** [comment]
The 6.0 behavior is incorrect: this call requires a hop to the actor (which means that it needs `await`). The compiler generates code correctly, but incorrectly diagnosed the need for an await. The bug about the `await` not being required was reported in https://github.com/swiftlang/swift/issues/73892 and fixed in https://github.com/swiftlang/swift/pull/76988.

**Comment by hjyamauchi** [comment]
Thank you @DougGregor
