### ISSUE TITLE
Content does not display when using PreviewModifier with .sheet

### ISSUE THREAD

**Issue by eucalyptus-viminalis** [swiftlang/swift#77842]
### Description

A structure conforming to `PreviewModifier` that places the content inside a sheet does not display the content.

### Reproduction

```swift
// PreviewModifiers.swift
import SwiftUI

// FIXME: Doesn't display content in preview
@available(iOS 17.0, *)
struct AsSheet: PreviewModifier {
    func body(content: Content, context: Void) -> some View {
        @Previewable @State var present = true
        Color.blue
            .sheet(isPresented: $present) {
                content    // Content is not displayed in preview
            }
    }
}

@available(iOS 17.0, *)
struct AsSheetWithExplicitlyDefinedContent: PreviewModifier {
    func body(content: Content, context: Void) -> some View {
        @Previewable @State var present = true
        Color.blue
            .sheet(isPresented: $present) {
                /**
                 Any views manually placed here _does_ display in preview.
                 */
                Text("Example text")
            }
    }
}
```

```swift
// ContentView.swift
import SwiftUI

struct ContentView: View {
    var body: some View {
        VStack {
            Image(systemName: "globe")
                .imageScale(.large)
                .foregroundColor(.accentColor)
            Text("Hello, world!")
        }
    }
}

@available(iOS 18.0, *)
#Preview("Implicit", traits: .modifier(AsSheet())) {
    ContentView()
}

@available(iOS 18.0, *)
#Preview("Explicit", traits: .modifier(AsSheetWithExplicitlyDefinedContent())) {
    ContentView()
}
```

## Content to display

<img width="380" alt="image" src="https://github.com/user-attachments/assets/dabaa566-3872-4f52-88c2-5b90fa2413ce">

## "Implicit" preview

- should display above content but preview is blank

<img width="380" alt="image" src="https://github.com/user-attachments/assets/54b3b67b-cb0c-4dfa-b4e6-93f8470d1d5b">

## "Explicit" preview

- explicitly defined views in custom PreviewModifier _does_ show up in Xcode previews

<img width="380" alt="image" src="https://github.com/user-attachments/assets/55630dce-5817-446d-9c10-9c9a6e715107">

### Expected behavior

The content placed in `.sheet` view modifier should be displayed in Xcode previews.

### Environment

swift-driver version: 1.115 Apple Swift version 6.0.2 (swiftlang-6.0.2.1.2 clang-1600.0.26.4)
Target: arm64-apple-macosx15.0

**Comment by AnthonyLatsis** [comment]
Hi, thanks for reporting! Would you mind reporting this to https://feedbackassistant.apple.com instead? This repository concerns the Swift compiler and standard libraries.
