### ISSUE TITLE
docs: broken links in "Migrating to Swift 6" 

### ISSUE THREAD

**Issue by Bogdanp** [swiftlang/swift#77884]
### Description

Apologies if this isn't the right place to post this, but the links under [this heading](https://www.swift.org/migration/documentation/swift-6-concurrency-migration-guide/incrementaladoption/#Dependencies) are broken.

### Reproduction

See above.

### Expected behavior

The links should not be broken.

### Environment

N/A

**Comment by AnthonyLatsis** [comment]
@hamishknight Are you able to transfer this?

**Comment by hamishknight** [comment]
Unfortunately not, seems like GitHub doesn't let you migrate issues across repos owned by different orgs. @Bogdanp can you please [file this issue here](https://github.com/apple/swift-migration-guide/issues/new/choose)?
