### ISSUE TITLE
Swift URLSession Response headers missing

### ISSUE THREAD

**Issue by johnmai-dev** [swiftlang/swift#77882]
### Description

I can't get the X-Repo-Commit from the header through Swift URLSession, but it is present when capturing HTTP traffic.
I can only switch to using `libcurl` to solve this problem now.

## URLSession
![image](https://github.com/user-attachments/assets/56e67ef2-0708-43e5-9458-fe98afce676f)

## libcurl
![image](https://github.com/user-attachments/assets/a9f58329-e84b-49a1-8380-1058802cf753)

## curl
<img width="762" alt="image" src="https://github.com/user-attachments/assets/0c6857f4-d929-4005-9c8b-dfbccea30fe6">

### Reproduction

```swift
    @Test
    func example() async throws {
        var request = URLRequest(url: URL(string: "https://huggingface.co/HuggingFaceTB/SmolLM2-135M-Instruct/resolve/5a33ba103645800d7b3790c4448546c1b73efc71/model.safetensors")!)
        request.httpMethod = "HEAD"
        
        let (_,response) = try await URLSession.shared.data(for: request)
        
        print(response)
        guard let httpResponse = response as? HTTPURLResponse else {
            throw URLError(.badServerResponse)
        }
        
        print(httpResponse.allHeaderFields)
        print(httpResponse.allHeaderFields.debugDescription)
    }
```

```bash
curl -I "https://huggingface.co/HuggingFaceTB/SmolLM2-135M-Instruct/resolve/5a33ba103645800d7b3790c4448546c1b73efc71/model.safetensors"
```

### Expected behavior

Get `x-repo-commit: 5a33ba103645800d7b3790c4448546c1b73efc71`

### Environment

swift-driver version: 1.115 Apple Swift version 6.0.2 (swiftlang-6.0.2.1.2 clang-1600.0.26.4)
Target: arm64-apple-macosx15.0

**Comment by johnmai-dev** [comment]
https://github.com/Alamofire/Alamofire/issues/1192

**Comment by AnthonyLatsis** [comment]
cc @itingliu
