### ISSUE TITLE
Swift Compiler crash when building swift-testing with cmake

### ISSUE THREAD

**Issue by Kyle-Ye** [swiftlang/swift#78058]
### Description

Following the `Using CMake to build the project for macOS` in `CONTRIBUTING.md`.

I got some compiler crash using Xcode 16.0.0's default Swift toolchain or the latest open source Swift 6.0.2 toolchain.

### Expected behavior

Compile fine.

### Actual behavior

Crash:

```
error: compile command failed due to signal 6 (use -v to see invocation)
Begin Error in Function: '$s7Testing13ConfigurationV15exitTestHandleryAA04ExitD9ArtifactsVAA0fD0VYaYbKcvpfiAfHYaYbKcfU_'
Found outside of lifetime use?!
Value:   %2 = load_borrow %1 : $*ExitTest                // users: %8, %4, %3
Consuming User:   end_borrow %2 : $ExitTest                       // id: %4
Non Consuming User:   debug_value %2 : $ExitTest, let, name "_0", argno 1 // id: %8
Block: bb0

End Error in Function: '$s7Testing13ConfigurationV15exitTestHandleryAA04ExitD9ArtifactsVAA0fD0VYaYbKcvpfiAfHYaYbKcfU_'
Found ownership error?!
triggering standard assertion failure routine
UNREACHABLE executed at /Users/ec2-user/jenkins/workspace/oss-swift-6.0.2-package-macos/swift/lib/SIL/Verifier/LinearLifetimeCheckerPrivate.h:211!
Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the crash backtrace.
```

Full log file

[log.txt](https://github.com/user-attachments/files/18062062/log.txt)

### Steps to reproduce

```shell
gh repo clone swiftlang/swift-testing
cd swift-testing
# export CMAKE_Swift_COMPILER='/Library/Developer/Toolchains/swift-6.0.2-RELEASE.xctoolchain/usr/bin/swiftc'
cmake -G Ninja -B build
cmake --build build
```

### swift-testing version/commit hash

a4ed760ce69261101fefffd1abf78ea663a4a44c

### Swift & OS version (output of `swift --version ; uname -a`)

swift-driver version: 1.115 Apple Swift version 6.0 (swiftlang-6.0.0.9.10 clang-1600.0.26.2)
Target: arm64-apple-macosx15.0
Darwin Kyle-MiniMax.local 24.1.0 Darwin Kernel Version 24.1.0: Thu Oct 10 21:03:11 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T6020 arm64

### CMake version

cmake version 3.30.5

CMake suite maintained and supported by Kitware (kitware.com/cmake).

**Comment by grynspan** [comment]
Transferred because of the compiler crash. Thanks for filing!

**Comment by stmontgomery** [comment]
I was about to transfer as well and agree. Note that the `-swift-version` compiler flag is `6` as expected, that "effective version" is misleading.

**Comment by Kyle-Ye** [comment]
Is there any suggested easy way to workaround it temporary? (Have tried to reset the HEAD into the 6 days ago, still not work)

I'm playing with some swift-testing patch and I'd like to verify it with the cmake build.

**Comment by stmontgomery** [comment]
You could try a `release/6.1` or `main` branch snapshot toolchain instead. Trying one of those and posting the result here might help narrow down the issue, too.

**Comment by Kyle-Ye** [comment]
> You could try a `release/6.1` or `main` branch snapshot toolchain instead. Trying one of those and posting the result here might help narrow down the issue, too.

The issue is originally happening on the latest main branch. Tried with release/6.1 branch, it is the same crash issue.

**Comment by Kyle-Ye** [comment]
It seems the crash has been fixed with the latest commit for swift-testing. e2ec0411e5f7407fc2d325c9feea8f0ac10a60e2
