### ISSUE TITLE
split() function not accepting empty space as a part of separator/

### ISSUE THREAD

**Issue by adityagi02** [swiftlang/swift#78218]
### Reproduction

![Screenshot 2024-12-16 at 10 18 38 PM](https://github.com/user-attachments/assets/5846faa8-327f-4a22-81ad-c89594a7db4e)

But working fine without empty space🤷🏻‍♂️
![Screenshot 2024-12-16 at 10 18 49 PM](https://github.com/user-attachments/assets/a31cec47-529f-4d95-88e5-4b60531662cf)

### Expected behavior

It should accept that separator text.

### Environment

```
swift-driver version: 1.115 
Apple Swift version 6.0 (swiftlang-6.0.0.9.10 clang-1600.0.26.2)
Target: arm64-apple-macosx15.0
```

**Comment by AnthonyLatsis** [comment]
`" - "` is no longer a character. The first example resolves to a [newer overload](https://github.com/swiftlang/swift-experimental-string-processing/blob/f6c6eb132d33f865239bae9a3c3a48f6a29aed97/Sources/_StringProcessing/Algorithms/Algorithms/Split.swift#L146) overload that accepts a collection of the same element type. The second example resolves to [this](https://github.com/swiftlang/swift/blob/b633c8156e62ea37dbb494f7b571fc9028b50a5d/stdlib/public/core/Collection.swift#L1547) overload, which accepts an element (a `Character` for `String`).

**Comment by adityagi02** [comment]
> `" - "` is no longer a character. The first example resolves to a [newer overload](https://github.com/swiftlang/swift-experimental-string-processing/blob/f6c6eb132d33f865239bae9a3c3a48f6a29aed97/Sources/_StringProcessing/Algorithms/Algorithms/Split.swift#L146) that accepts a collection of the same element type. The second example resolves to [this](https://github.com/swiftlang/swift/blob/b633c8156e62ea37dbb494f7b571fc9028b50a5d/stdlib/public/core/Collection.swift#L1547) overload, which accepts an element (a `Character` for `String`).
> 
> 

Got it/ thanks a lot for explaining nicely!!
